import type { LanguageCode } from '@/core/types'
import type { NewCardRecordInput } from '@/core/db'

/**
 * Boshlang'ich to'plamlar — har tildan 10 ta so'z.
 *
 * Har so'zga qisqa jumla biriktirilgan: u "jumla qurish" mashqi uchun
 * ishlatiladi va bir vaqtning o'zida kontekstli kirish beradi
 * (Krashen, "comprehensible input i+1").
 *
 * VAQTINCHALIK: TZ 7-bo'limiga ko'ra Faza 5'da har til uchun 3 daraja
 * (A1/A2/B1) va ~100 so'zlik to'liq JSON kontent qo'shiladi.
 */
const EN: NewCardRecordInput[] = [
  {
    word: 'hello',
    translation: 'salom',
    language: 'en',
    topic: 'Salomlashish',
    level: 'A1',
    sentence: 'Hello my friend',
    sentenceTranslation: "Salom, do'stim",
  },
  {
    word: 'thank you',
    translation: 'rahmat',
    language: 'en',
    topic: 'Salomlashish',
    level: 'A1',
    sentence: 'Thank you very much',
    sentenceTranslation: 'Katta rahmat',
  },
  {
    word: 'water',
    translation: 'suv',
    language: 'en',
    topic: 'Ovqat',
    level: 'A1',
    sentence: 'I drink water',
    sentenceTranslation: 'Men suv ichaman',
  },
  {
    word: 'bread',
    translation: 'non',
    language: 'en',
    topic: 'Ovqat',
    level: 'A1',
    sentence: 'The bread is fresh',
    sentenceTranslation: 'Non yangi',
  },
  {
    word: 'friend',
    translation: "do'st",
    language: 'en',
    topic: 'Oila',
    level: 'A1',
    sentence: 'She is my friend',
    sentenceTranslation: "U mening do'stim",
  },
  {
    word: 'house',
    translation: 'uy',
    language: 'en',
    topic: 'Oila',
    level: 'A1',
    sentence: 'This is my house',
    sentenceTranslation: 'Bu mening uyim',
  },
  {
    word: 'book',
    translation: 'kitob',
    language: 'en',
    topic: 'Maktab',
    level: 'A1',
    sentence: 'I read a book',
    sentenceTranslation: "Men kitob o'qiyman",
  },
  {
    word: 'morning',
    translation: 'ertalab',
    language: 'en',
    topic: 'Vaqt',
    level: 'A1',
    sentence: 'Good morning',
    sentenceTranslation: 'Xayrli tong',
  },
  {
    word: 'road',
    translation: "yo'l",
    language: 'en',
    topic: 'Sayohat',
    level: 'A1',
    sentence: 'The road is long',
    sentenceTranslation: "Yo'l uzoq",
  },
  {
    word: 'city',
    translation: 'shahar',
    language: 'en',
    topic: 'Sayohat',
    level: 'A1',
    sentence: 'The city is big',
    sentenceTranslation: 'Shahar katta',
  },
]

const RU: NewCardRecordInput[] = [
  {
    word: 'привет',
    translation: 'salom',
    language: 'ru',
    topic: 'Salomlashish',
    level: 'A1',
    sentence: 'Привет мой друг',
    sentenceTranslation: "Salom, do'stim",
  },
  {
    word: 'спасибо',
    translation: 'rahmat',
    language: 'ru',
    topic: 'Salomlashish',
    level: 'A1',
    sentence: 'Большое спасибо',
    sentenceTranslation: 'Katta rahmat',
  },
  {
    word: 'вода',
    translation: 'suv',
    language: 'ru',
    topic: 'Ovqat',
    level: 'A1',
    sentence: 'Я пью воду',
    sentenceTranslation: 'Men suv ichaman',
  },
  {
    word: 'хлеб',
    translation: 'non',
    language: 'ru',
    topic: 'Ovqat',
    level: 'A1',
    sentence: 'Хлеб свежий',
    sentenceTranslation: 'Non yangi',
  },
  {
    word: 'друг',
    translation: "do'st",
    language: 'ru',
    topic: 'Oila',
    level: 'A1',
    sentence: 'Он мой друг',
    sentenceTranslation: "U mening do'stim",
  },
  {
    word: 'дом',
    translation: 'uy',
    language: 'ru',
    topic: 'Oila',
    level: 'A1',
    sentence: 'Это мой дом',
    sentenceTranslation: 'Bu mening uyim',
  },
  {
    word: 'книга',
    translation: 'kitob',
    language: 'ru',
    topic: 'Maktab',
    level: 'A1',
    sentence: 'Я читаю книгу',
    sentenceTranslation: "Men kitob o'qiyman",
  },
  {
    word: 'утро',
    translation: 'ertalab',
    language: 'ru',
    topic: 'Vaqt',
    level: 'A1',
    sentence: 'Доброе утро',
    sentenceTranslation: 'Xayrli tong',
  },
  {
    word: 'дорога',
    translation: "yo'l",
    language: 'ru',
    topic: 'Sayohat',
    level: 'A1',
    sentence: 'Дорога длинная',
    sentenceTranslation: "Yo'l uzoq",
  },
  {
    word: 'город',
    translation: 'shahar',
    language: 'ru',
    topic: 'Sayohat',
    level: 'A1',
    sentence: 'Город большой',
    sentenceTranslation: 'Shahar katta',
  },
]

const AR: NewCardRecordInput[] = [
  {
    word: 'مَرْحَبًا',
    translation: 'salom',
    language: 'ar',
    topic: 'Salomlashish',
    level: 'A1',
    sentence: 'مرحبا يا صديقي',
    sentenceTranslation: "Salom, do'stim",
  },
  {
    word: 'شُكْرًا',
    translation: 'rahmat',
    language: 'ar',
    topic: 'Salomlashish',
    level: 'A1',
    sentence: 'شكرا جزيلا',
    sentenceTranslation: 'Katta rahmat',
  },
  {
    word: 'مَاء',
    translation: 'suv',
    language: 'ar',
    topic: 'Ovqat',
    level: 'A1',
    sentence: 'أشرب الماء',
    sentenceTranslation: 'Men suv ichaman',
  },
  {
    word: 'خُبْز',
    translation: 'non',
    language: 'ar',
    topic: 'Ovqat',
    level: 'A1',
    sentence: 'الخبز طازج',
    sentenceTranslation: 'Non yangi',
  },
  {
    word: 'صَدِيق',
    translation: "do'st",
    language: 'ar',
    topic: 'Oila',
    level: 'A1',
    sentence: 'هو صديقي',
    sentenceTranslation: "U mening do'stim",
  },
  {
    word: 'بَيْت',
    translation: 'uy',
    language: 'ar',
    topic: 'Oila',
    level: 'A1',
    sentence: 'هذا بيتي',
    sentenceTranslation: 'Bu mening uyim',
  },
  {
    word: 'كِتَاب',
    translation: 'kitob',
    language: 'ar',
    topic: 'Maktab',
    level: 'A1',
    sentence: 'أقرأ الكتاب',
    sentenceTranslation: "Men kitob o'qiyman",
  },
  {
    word: 'صَبَاح',
    translation: 'ertalab',
    language: 'ar',
    topic: 'Vaqt',
    level: 'A1',
    sentence: 'صباح الخير',
    sentenceTranslation: 'Xayrli tong',
  },
  {
    word: 'طَرِيق',
    translation: "yo'l",
    language: 'ar',
    topic: 'Sayohat',
    level: 'A1',
    sentence: 'الطريق طويل',
    sentenceTranslation: "Yo'l uzoq",
  },
  {
    word: 'مَدِينَة',
    translation: 'shahar',
    language: 'ar',
    topic: 'Sayohat',
    level: 'A1',
    sentence: 'المدينة كبيرة',
    sentenceTranslation: 'Shahar katta',
  },
]

export const STARTER_DECKS: Record<LanguageCode, NewCardRecordInput[]> = {
  en: EN,
  ru: RU,
  ar: AR,
}
