import type { NewCardRecordInput } from '@/core/db'
import type { LevelCode } from '@/core/types'

/**
 * Arab tili to'plami, CEFR darajalari bo'yicha.
 *
 * Tushunchalar ingliz va rus to'plamlari bilan bir xil: foydalanuvchi
 * tillar o'rtasida almashganda bir xil mavzular ketma-ketligini ko'radi.
 *
 * So'zlar HARAKAT bilan yoziladi (`مَدِينَة`) — to'g'ri talaffuz uchun.
 * `normalize.ts` javob tekshirishda harakatlarni tushiradi, shuning uchun
 * foydalanuvchi harakatsiz yozsa ham javob to'g'ri sanaladi. Jumlalarda
 * harakat qo'yilmaydi — o'qishga xalaqit bermasligi uchun.
 */
export const AR_DECK: Record<LevelCode, NewCardRecordInput[]> = {
  A1: [
    {
      word: 'مَرْحَبًا',
      translation: 'salom',
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'مَرْحَبًا يَا صَدِيقِي',
      sentenceTranslation: "Salom, do'stim",
    },
    {
      word: 'شُكْرًا',
      translation: 'rahmat',
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'شُكْرًا جَزِيلًا',
      sentenceTranslation: 'Katta rahmat',
    },
    {
      word: 'مَعَ السَّلَامَة',
      translation: 'xayr',
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'مَعَ السَّلَامَةِ، إِلَى اللِّقَاءِ',
      sentenceTranslation: "Xayr, ko'rishguncha",
    },
    {
      word: 'مِنْ فَضْلِكَ',
      translation: 'iltimos',
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'مِنْ فَضْلِكَ سَاعِدْنِي',
      sentenceTranslation: 'Iltimos, menga yordam bering',
    },
    {
      word: 'آسِف',
      translation: 'kechirasiz',
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'آسِفٌ، أَنَا مُتَأَخِّرٌ',
      sentenceTranslation: 'Kechirasiz, men kechikdim',
    },
    {
      word: 'نَعَم',
      translation: 'ha',
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'نَعَمْ، أَنَا جَاهِزٌ',
      sentenceTranslation: 'Ha, men tayyorman',
    },
    {
      word: 'لَا',
      translation: "yo'q",
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'لَا، شُكْرًا',
      sentenceTranslation: "Yo'q, rahmat",
    },
    {
      word: 'صَدِيق',
      translation: "do'st",
      language: 'ar',
      topic: 'Oila',
      level: 'A1',
      sentence: 'هُوَ صَدِيقِي',
      sentenceTranslation: "U mening do'stim",
    },
    {
      word: 'بَيْت',
      translation: 'uy',
      language: 'ar',
      topic: 'Oila',
      level: 'A1',
      sentence: 'هَذَا بَيْتِي',
      sentenceTranslation: 'Bu mening uyim',
    },
    {
      word: 'أُمّ',
      translation: 'ona',
      language: 'ar',
      topic: 'Oila',
      level: 'A1',
      sentence: 'أُمِّي فِي الْبَيْتِ',
      sentenceTranslation: 'Onam uyda',
    },
    {
      word: 'أَب',
      translation: 'ota',
      language: 'ar',
      topic: 'Oila',
      level: 'A1',
      sentence: 'أَبِي يَعْمَلُ هُنَا',
      sentenceTranslation: 'Otam shu yerda ishlaydi',
    },
    {
      word: 'طِفْل',
      translation: 'bola',
      language: 'ar',
      topic: 'Oila',
      level: 'A1',
      sentence: 'الطِّفْلُ صَغِيرٌ',
      sentenceTranslation: 'Bola kichkina',
    },
    {
      word: 'وَاحِد',
      translation: 'bir',
      language: 'ar',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'عِنْدِي كِتَابٌ وَاحِدٌ',
      sentenceTranslation: 'Menda bitta kitob bor',
    },
    {
      word: 'اِثْنَان',
      translation: 'ikki',
      language: 'ar',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'اثْنَانِ مِنَ الطُّلَّابِ هُنَا',
      sentenceTranslation: 'Talabalardan ikkitasi shu yerda',
    },
    {
      word: 'ثَلَاثَة',
      translation: 'uch',
      language: 'ar',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'عِنْدَنَا ثَلَاثُ غُرَفٍ',
      sentenceTranslation: 'Bizda uchta xona bor',
    },
    {
      word: 'أَرْبَعَة',
      translation: "to'rt",
      language: 'ar',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'أَرْبَعَةُ أَشْخَاصٍ هُنَا',
      sentenceTranslation: "To'rt kishi shu yerda",
    },
    {
      word: 'خَمْسَة',
      translation: 'besh',
      language: 'ar',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'خَمْسُ دَقَائِقَ مِنْ فَضْلِكَ',
      sentenceTranslation: 'Besh daqiqa, iltimos',
    },
    {
      word: 'عَشَرَة',
      translation: "o'n",
      language: 'ar',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'عَشَرَةُ طُلَّابٍ هُنَا',
      sentenceTranslation: "O'n talaba shu yerda",
    },
    {
      word: 'مَاء',
      translation: 'suv',
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'أَشْرَبُ الْمَاءَ',
      sentenceTranslation: 'Men suv ichaman',
    },
    {
      word: 'خُبْز',
      translation: 'non',
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'الْخُبْزُ طَازَجٌ',
      sentenceTranslation: 'Non yangi',
    },
    {
      word: 'حَلِيب',
      translation: 'sut',
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'الْحَلِيبُ بَارِدٌ',
      sentenceTranslation: 'Sut sovuq',
    },
    {
      word: 'تُفَّاحَة',
      translation: 'olma',
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'هَذِهِ التُّفَّاحَةُ حُلْوَةٌ',
      sentenceTranslation: 'Bu olma shirin',
    },
    {
      word: 'أَرُزّ',
      translation: 'guruch',
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'نَأْكُلُ الْأَرُزَّ الْيَوْمَ',
      sentenceTranslation: 'Biz bugun guruch yeymiz',
    },
    {
      word: 'لَحْم',
      translation: "go'sht",
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'اللَّحْمُ جَاهِزٌ',
      sentenceTranslation: "Go'sht tayyor",
    },
    {
      word: 'شَاي',
      translation: 'choy',
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'أُحِبُّ الشَّايَ الْأَخْضَرَ',
      sentenceTranslation: "Menga ko'k choy yoqadi",
    },
    {
      word: 'مِلْح',
      translation: 'tuz',
      language: 'ar',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'أَضِفْ قَلِيلًا مِنَ الْمِلْحِ',
      sentenceTranslation: "Ozgina tuz qo'shing",
    },
    {
      word: 'أَحْمَر',
      translation: 'qizil',
      language: 'ar',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'التُّفَّاحَةُ حَمْرَاءُ',
      sentenceTranslation: 'Olma qizil',
    },
    {
      word: 'أَزْرَق',
      translation: "ko'k",
      language: 'ar',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'السَّمَاءُ زَرْقَاءُ',
      sentenceTranslation: "Osmon ko'k",
    },
    {
      word: 'أَخْضَر',
      translation: 'yashil',
      language: 'ar',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'الْعُشْبُ أَخْضَرُ',
      sentenceTranslation: "O't yashil",
    },
    {
      word: 'أَسْوَد',
      translation: 'qora',
      language: 'ar',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'عِنْدِي حِذَاءٌ أَسْوَدُ',
      sentenceTranslation: 'Menda qora tufli bor',
    },
    {
      word: 'أَبْيَض',
      translation: 'oq',
      language: 'ar',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'الْبَيْتُ أَبْيَضُ',
      sentenceTranslation: 'Uy oq',
    },
    {
      word: 'أَصْفَر',
      translation: 'sariq',
      language: 'ar',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'الشَّمْسُ صَفْرَاءُ',
      sentenceTranslation: 'Quyosh sariq',
    },
    {
      word: 'يَأْكُل',
      translation: 'yemoq',
      language: 'ar',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'نَأْكُلُ مَعًا',
      sentenceTranslation: 'Biz birga yeymiz',
    },
    {
      word: 'يَشْرَب',
      translation: 'ichmoq',
      language: 'ar',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'أَشْرَبُ مَاءً بَارِدًا',
      sentenceTranslation: 'Men sovuq suv ichaman',
    },
    {
      word: 'يَذْهَب',
      translation: 'bormoq',
      language: 'ar',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'أَذْهَبُ إِلَى الْمَدْرَسَةِ',
      sentenceTranslation: 'Men maktabga boraman',
    },
    {
      word: 'يَأْتِي',
      translation: 'kelmoq',
      language: 'ar',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'يَجِبُ أَنْ يَأْتِيَ مُبَكِّرًا',
      sentenceTranslation: 'U erta kelishi kerak',
    },
    {
      word: 'يَرَى',
      translation: "ko'rmoq",
      language: 'ar',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'أَرَى صَدِيقِي',
      sentenceTranslation: "Men do'stimni ko'raman",
    },
    {
      word: 'يَنَام',
      translation: 'uxlamoq',
      language: 'ar',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'الْأَطْفَالُ يَنَامُونَ مُبَكِّرًا',
      sentenceTranslation: 'Bolalar erta uxlaydi',
    },
    {
      word: 'كِتَاب',
      translation: 'kitob',
      language: 'ar',
      topic: 'Maktab',
      level: 'A1',
      sentence: 'أَقْرَأُ الْكِتَابَ',
      sentenceTranslation: "Men kitob o'qiyman",
    },
    {
      word: 'صَبَاح',
      translation: 'ertalab',
      language: 'ar',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'صَبَاحُ الْخَيْرِ',
      sentenceTranslation: 'Xayrli tong',
    },
    {
      word: 'طَرِيق',
      translation: "yo'l",
      language: 'ar',
      topic: 'Sayohat',
      level: 'A1',
      sentence: 'الطَّرِيقُ طَوِيلٌ',
      sentenceTranslation: "Yo'l uzoq",
    },
    {
      word: 'مَدِينَة',
      translation: 'shahar',
      language: 'ar',
      topic: 'Sayohat',
      level: 'A1',
      sentence: 'الْمَدِينَةُ كَبِيرَةٌ',
      sentenceTranslation: 'Shahar katta',
    },
    {
      word: 'قِطَّة',
      translation: 'mushuk',
      language: 'ar',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'الْقِطَّةُ صَغِيرَةٌ',
      sentenceTranslation: 'Mushuk kichkina',
    },
    {
      word: 'كَلْب',
      translation: 'it',
      language: 'ar',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'الْكَلْبُ يَجْرِي بِسُرْعَةٍ',
      sentenceTranslation: 'It tez yuguradi',
    },
    {
      word: 'طَائِر',
      translation: 'qush',
      language: 'ar',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'الطَّائِرُ يُغَرِّدُ',
      sentenceTranslation: 'Qush sayraydi',
    },
    {
      word: 'سَمَك',
      translation: 'baliq',
      language: 'ar',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'السَّمَكُ يَسْبَحُ',
      sentenceTranslation: 'Baliq suzadi',
    },
    {
      word: 'بَقَرَة',
      translation: 'sigir',
      language: 'ar',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'الْبَقَرَةُ تُعْطِي الْحَلِيبَ',
      sentenceTranslation: 'Sigir sut beradi',
    },
    {
      word: 'يَد',
      translation: "qo'l",
      language: 'ar',
      topic: 'Tana',
      level: 'A1',
      sentence: 'رَفَعْتُ يَدِي',
      sentenceTranslation: "Men qo'limni ko'tardim",
    },
    {
      word: 'عَيْن',
      translation: "ko'z",
      language: 'ar',
      topic: 'Tana',
      level: 'A1',
      sentence: 'أَغْمِضْ عَيْنَيْكَ',
      sentenceTranslation: "Ko'zingizni yuming",
    },
    {
      word: 'رَأْس',
      translation: 'bosh',
      language: 'ar',
      topic: 'Tana',
      level: 'A1',
      sentence: 'رَأْسِي يُؤْلِمُنِي',
      sentenceTranslation: 'Boshim og’riyapti',
    },
    {
      word: 'قَدَم',
      translation: 'oyoq',
      language: 'ar',
      topic: 'Tana',
      level: 'A1',
      sentence: 'قَدَمِي بَارِدَةٌ',
      sentenceTranslation: 'Oyog’im sovuq',
    },
    {
      word: 'أُذُن',
      translation: 'quloq',
      language: 'ar',
      topic: 'Tana',
      level: 'A1',
      sentence: 'الْأُذُنُ تَسْمَعُ الصَّوْتَ',
      sentenceTranslation: 'Quloq tovushni eshitadi',
    },
  ],

  A2: [
    {
      word: 'مَطَار',
      translation: 'aeroport',
      language: 'ar',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'الْمَطَارُ بَعِيدٌ',
      sentenceTranslation: 'Aeroport uzoqda',
    },
    {
      word: 'تَذْكَرَة',
      translation: 'chipta',
      language: 'ar',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'اِشْتَرَيْتُ تَذْكِرَةً',
      sentenceTranslation: 'Men chipta sotib oldim',
    },
    {
      word: 'قِطَار',
      translation: 'poyezd',
      language: 'ar',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'الْقِطَارُ مُتَأَخِّرٌ',
      sentenceTranslation: 'Poyezd kechikmoqda',
    },
    {
      word: 'فُنْدُق',
      translation: 'mehmonxona',
      language: 'ar',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'الْفُنْدُقُ نَظِيفٌ',
      sentenceTranslation: 'Mehmonxona toza',
    },
    {
      word: 'حَقِيبَة',
      translation: 'chamadon',
      language: 'ar',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'حَقِيبَتِي ثَقِيلَةٌ',
      sentenceTranslation: "Chamadonim og'ir",
    },
    {
      word: 'خَرِيطَة',
      translation: 'xarita',
      language: 'ar',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'اُنْظُرْ إِلَى الْخَرِيطَةِ',
      sentenceTranslation: 'Xaritaga qarang',
    },
    {
      word: 'مَتْجَر',
      translation: "do'kon",
      language: 'ar',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'الْمَتْجَرُ مَفْتُوحٌ',
      sentenceTranslation: "Do'kon ochiq",
    },
    {
      word: 'مَال',
      translation: 'pul',
      language: 'ar',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'أَحْتَاجُ مَالًا أَكْثَرَ',
      sentenceTranslation: "Menga ko'proq pul kerak",
    },
    {
      word: 'سِعْر',
      translation: 'narx',
      language: 'ar',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'السِّعْرُ مُرْتَفِعٌ',
      sentenceTranslation: 'Narx baland',
    },
    {
      word: 'يَشْتَرِي',
      translation: 'sotib olmoq',
      language: 'ar',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'أُرِيدُ أَنْ أَشْتَرِيَ خُبْزًا',
      sentenceTranslation: 'Men non sotib olmoqchiman',
    },
    {
      word: 'رَخِيص',
      translation: 'arzon',
      language: 'ar',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'هَذَا الْقَمِيصُ رَخِيصٌ',
      sentenceTranslation: "Bu ko'ylak arzon",
    },
    {
      word: 'غَالٍ',
      translation: 'qimmat',
      language: 'ar',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'هَذِهِ السَّيَّارَةُ غَالِيَةٌ',
      sentenceTranslation: 'Bu mashina qimmat',
    },
    {
      word: 'عَمَل',
      translation: 'ish',
      language: 'ar',
      topic: 'Ish',
      level: 'A2',
      sentence: 'عَمَلِي مُمْتِعٌ',
      sentenceTranslation: 'Mening ishim qiziqarli',
    },
    {
      word: 'مَكْتَب',
      translation: 'ofis',
      language: 'ar',
      topic: 'Ish',
      level: 'A2',
      sentence: 'الْمَكْتَبُ مُغْلَقٌ',
      sentenceTranslation: 'Ofis yopiq',
    },
    {
      word: 'مُعَلِّم',
      translation: "o'qituvchi",
      language: 'ar',
      topic: 'Ish',
      level: 'A2',
      sentence: 'مُعَلِّمُنَا طَيِّبٌ',
      sentenceTranslation: "O'qituvchimiz mehribon",
    },
    {
      word: 'طَبِيب',
      translation: 'shifokor',
      language: 'ar',
      topic: 'Ish',
      level: 'A2',
      sentence: 'الطَّبِيبُ مَشْغُولٌ',
      sentenceTranslation: 'Shifokor band',
    },
    {
      word: 'اِجْتِمَاع',
      translation: 'uchrashuv',
      language: 'ar',
      topic: 'Ish',
      level: 'A2',
      sentence: 'الِاجْتِمَاعُ يَبْدَأُ الْآنَ',
      sentenceTranslation: 'Uchrashuv hozir boshlanadi',
    },
    {
      word: 'شَرِكَة',
      translation: 'kompaniya',
      language: 'ar',
      topic: 'Ish',
      level: 'A2',
      sentence: 'الشَّرِكَةُ جَدِيدَةٌ',
      sentenceTranslation: 'Kompaniya yangi',
    },
    {
      word: 'صِحَّة',
      translation: 'salomatlik',
      language: 'ar',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'الصِّحَّةُ مُهِمَّةٌ',
      sentenceTranslation: 'Salomatlik muhim',
    },
    {
      word: 'دَوَاء',
      translation: 'dori',
      language: 'ar',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'خُذْ هَذَا الدَّوَاءَ',
      sentenceTranslation: 'Bu dorini iching',
    },
    {
      word: 'مُسْتَشْفَى',
      translation: 'kasalxona',
      language: 'ar',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'الْمُسْتَشْفَى قَرِيبٌ',
      sentenceTranslation: 'Kasalxona yaqin',
    },
    {
      word: 'أَلَم',
      translation: "og'riq",
      language: 'ar',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'الْأَلَمُ ذَهَبَ',
      sentenceTranslation: "Og'riq o'tdi",
    },
    {
      word: 'مُتْعَب',
      translation: 'charchagan',
      language: 'ar',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'أَنَا مُتْعَبٌ جِدًّا',
      sentenceTranslation: 'Men juda charchaganman',
    },
    {
      word: 'طَقْس',
      translation: 'ob-havo',
      language: 'ar',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'الطَّقْسُ جَمِيلٌ',
      sentenceTranslation: 'Ob-havo yaxshi',
    },
    {
      word: 'مَطَر',
      translation: "yomg'ir",
      language: 'ar',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'تَوَقَّفَ الْمَطَرُ',
      sentenceTranslation: "Yomg'ir to'xtadi",
    },
    {
      word: 'ثَلْج',
      translation: 'qor',
      language: 'ar',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'الثَّلْجُ غَطَّى الْمَدِينَةَ',
      sentenceTranslation: 'Qor shaharni qopladi',
    },
    {
      word: 'رِيح',
      translation: 'shamol',
      language: 'ar',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'الرِّيحُ قَوِيَّةٌ',
      sentenceTranslation: 'Shamol kuchli',
    },
    {
      word: 'شَمْس',
      translation: 'quyosh',
      language: 'ar',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'الشَّمْسُ دَافِئَةٌ',
      sentenceTranslation: 'Quyosh iliq',
    },
    {
      word: 'بَارِد',
      translation: 'sovuq',
      language: 'ar',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'الْمَاءُ بَارِدٌ',
      sentenceTranslation: 'Suv sovuq',
    },
    {
      word: 'أُسْبُوع',
      translation: 'hafta',
      language: 'ar',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'أَعْمَلُ كُلَّ أُسْبُوعٍ',
      sentenceTranslation: 'Men har hafta ishlayman',
    },
    {
      word: 'سَنَة',
      translation: 'yil',
      language: 'ar',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'هَذِهِ السَّنَةُ أَفْضَلُ',
      sentenceTranslation: 'Bu yil yaxshiroq',
    },
    {
      word: 'سَاعَة',
      translation: 'soat',
      language: 'ar',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'اِنْتَظِرْ سَاعَةً وَاحِدَةً',
      sentenceTranslation: 'Bir soat kuting',
    },
    {
      word: 'يَوْم',
      translation: 'kun',
      language: 'ar',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'كَانَ الْيَوْمُ طَوِيلًا',
      sentenceTranslation: "Kun uzoq bo'ldi",
    },
    {
      word: 'غَدًا',
      translation: 'ertaga',
      language: 'ar',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'نَلْتَقِي غَدًا',
      sentenceTranslation: 'Biz ertaga uchrashamiz',
    },
    {
      word: 'دَائِمًا',
      translation: 'doim',
      language: 'ar',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'هِيَ تُسَاعِدُ دَائِمًا',
      sentenceTranslation: 'U doim yordam beradi',
    },
    {
      word: 'بَاب',
      translation: 'eshik',
      language: 'ar',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'أَغْلِقِ الْبَابَ',
      sentenceTranslation: "Eshikni yoping",
    },
    {
      word: 'نَافِذَة',
      translation: 'deraza',
      language: 'ar',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'اِفْتَحِ النَّافِذَةَ',
      sentenceTranslation: 'Derazani oching',
    },
    {
      word: 'طَاوِلَة',
      translation: 'stol',
      language: 'ar',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'الطَّاوِلَةُ نَظِيفَةٌ',
      sentenceTranslation: 'Stol toza',
    },
    {
      word: 'كُرْسِيّ',
      translation: 'stul',
      language: 'ar',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'اِجْلِسْ عَلَى الْكُرْسِيِّ',
      sentenceTranslation: "Stulga o'tiring",
    },
    {
      word: 'مِفْتَاح',
      translation: 'kalit',
      language: 'ar',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'فَقَدْتُ الْمِفْتَاحَ',
      sentenceTranslation: "Kalitimni yo'qotdim",
    },
    {
      word: 'قَمِيص',
      translation: "ko'ylak",
      language: 'ar',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'هَذَا الْقَمِيصُ جَدِيدٌ',
      sentenceTranslation: "Bu ko'ylak yangi",
    },
    {
      word: 'حِذَاء',
      translation: 'poyabzal',
      language: 'ar',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'حِذَائِي أَسْوَدُ',
      sentenceTranslation: 'Poyabzalim qora',
    },
    {
      word: 'قُبَّعَة',
      translation: 'shapka',
      language: 'ar',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'هُوَ يَلْبَسُ قُبَّعَةً',
      sentenceTranslation: 'U shapka kiyadi',
    },
    {
      word: 'مِعْطَف',
      translation: 'palto',
      language: 'ar',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'الْمِعْطَفُ دَافِئٌ',
      sentenceTranslation: 'Palto issiq',
    },
    {
      word: 'فُسْتَان',
      translation: 'libos',
      language: 'ar',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'فُسْتَانُهَا أَحْمَرُ',
      sentenceTranslation: 'Uning libosi qizil',
    },
  ],

  B1: [
    {
      word: 'قَرَار',
      translation: 'qaror',
      language: 'ar',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'كَانَ قَرَارًا صَعْبًا',
      sentenceTranslation: 'Bu qiyin qaror edi',
    },
    {
      word: 'رَأْي',
      translation: 'fikr',
      language: 'ar',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'قُلْ رَأْيَكَ',
      sentenceTranslation: 'Fikringizni ayting',
    },
    {
      word: 'يُوَافِق',
      translation: "rozi bo'lmoq",
      language: 'ar',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'أُوَافِقُكَ الرَّأْيَ',
      sentenceTranslation: 'Men siz bilan roziman',
    },
    {
      word: 'يَشْرَح',
      translation: 'tushuntirmoq',
      language: 'ar',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'مِنْ فَضْلِكَ اشْرَحِ الْقَاعِدَةَ',
      sentenceTranslation: 'Iltimos, qoidani tushuntiring',
    },
    {
      word: 'يَقْتَرِح',
      translation: 'taklif qilmoq',
      language: 'ar',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'أَقْتَرِحُ خُطَّةً أُخْرَى',
      sentenceTranslation: 'Men boshqa reja taklif qilaman',
    },
    {
      word: 'سَعِيد',
      translation: 'baxtli',
      language: 'ar',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'هِيَ سَعِيدَةٌ الْيَوْمَ',
      sentenceTranslation: 'U bugun baxtli',
    },
    {
      word: 'حَزِين',
      translation: 'xafa',
      language: 'ar',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'كَانَ حَزِينًا',
      sentenceTranslation: 'U xafa edi',
    },
    {
      word: 'خَوْف',
      translation: "qo'rquv",
      language: 'ar',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'الْخَوْفُ يُوقِفُ كَثِيرِينَ',
      sentenceTranslation: "Qo'rquv ko'p odamni to'xtatadi",
    },
    {
      word: 'فَرَح',
      translation: 'quvonch',
      language: 'ar',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'فَرَحُهَا كَانَ حَقِيقِيًّا',
      sentenceTranslation: 'Uning quvonchi chin edi',
    },
    {
      word: 'دَهْشَة',
      translation: 'hayrat',
      language: 'ar',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'الْخَبَرُ سَبَّبَ دَهْشَةً',
      sentenceTranslation: "Yangilik hayrat uyg'otdi",
    },
    {
      word: 'مُجْتَمَع',
      translation: 'jamiyat',
      language: 'ar',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'الْمُجْتَمَعُ يَتَغَيَّرُ بِبُطْءٍ',
      sentenceTranslation: "Jamiyat sekin o'zgaradi",
    },
    {
      word: 'قَانُون',
      translation: 'qonun',
      language: 'ar',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'الْقَانُونُ وَاضِحٌ',
      sentenceTranslation: 'Qonun aniq',
    },
    {
      word: 'حُكُومَة',
      translation: 'hukumat',
      language: 'ar',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'الْحُكُومَةُ وَضَعَتْ قَوَاعِدَ',
      sentenceTranslation: 'Hukumat qoidalar chiqardi',
    },
    {
      word: 'مُوَاطِن',
      translation: 'fuqaro',
      language: 'ar',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'لِكُلِّ مُوَاطِنٍ وَاجِبَاتٌ',
      sentenceTranslation: 'Har bir fuqaroning burchi bor',
    },
    {
      word: 'حُرِّيَّة',
      translation: 'erkinlik',
      language: 'ar',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'الْحُرِّيَّةُ تَتَطَلَّبُ مَسْؤُولِيَّةً',
      sentenceTranslation: "Erkinlik mas'uliyat talab qiladi",
    },
    {
      word: 'حَاسُوب',
      translation: 'kompyuter',
      language: 'ar',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'حَاسُوبِي بَطِيءٌ',
      sentenceTranslation: 'Kompyuterim sekin',
    },
    {
      word: 'شَبَكَة',
      translation: 'tarmoq',
      language: 'ar',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'الشَّبَكَةُ لَا تَعْمَلُ',
      sentenceTranslation: 'Tarmoq ishlamayapti',
    },
    {
      word: 'بَيَانَات',
      translation: "ma'lumot",
      language: 'ar',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'فَقَدْنَا الْبَيَانَاتِ',
      sentenceTranslation: "Biz ma'lumotni yo'qotdik",
    },
    {
      word: 'شَاشَة',
      translation: 'ekran',
      language: 'ar',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'الشَّاشَةُ مُضِيئَةٌ',
      sentenceTranslation: 'Ekran yorqin',
    },
    {
      word: 'جِهَاز',
      translation: 'qurilma',
      language: 'ar',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'هَذَا الْجِهَازُ مُفِيدٌ',
      sentenceTranslation: 'Bu qurilma foydali',
    },
    {
      word: 'فِكْرَة',
      translation: "g'oya",
      language: 'ar',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'هَذِهِ فِكْرَةٌ جَيِّدَةٌ',
      sentenceTranslation: "Bu yaxshi g'oya",
    },
    {
      word: 'سَبَب',
      translation: 'sabab',
      language: 'ar',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'قُلْ لِي السَّبَبَ',
      sentenceTranslation: 'Menga sababni ayting',
    },
    {
      word: 'خِبْرَة',
      translation: 'tajriba',
      language: 'ar',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'الْخِبْرَةُ تُعَلِّمُنَا',
      sentenceTranslation: "Tajriba bizni o'rgatadi",
    },
    {
      word: 'مَعْرِفَة',
      translation: 'bilim',
      language: 'ar',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'الْمَعْرِفَةُ تَنْمُو بِبُطْءٍ',
      sentenceTranslation: "Bilim sekin o'sadi",
    },
    {
      word: 'تَغْيِير',
      translation: "o'zgarish",
      language: 'ar',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'التَّغْيِيرُ يَحْتَاجُ وَقْتًا',
      sentenceTranslation: "O'zgarish vaqt talab qiladi",
    },
    {
      word: 'شَجَرَة',
      translation: 'daraxt',
      language: 'ar',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'الشَّجَرَةُ طَوِيلَةٌ',
      sentenceTranslation: 'Daraxt baland',
    },
    {
      word: 'نَهْر',
      translation: 'daryo',
      language: 'ar',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'النَّهْرُ عَمِيقٌ',
      sentenceTranslation: 'Daryo chuqur',
    },
    {
      word: 'جَبَل',
      translation: "tog'",
      language: 'ar',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'الْجَبَلُ عَالٍ',
      sentenceTranslation: "Tog' baland",
    },
    {
      word: 'بَحْر',
      translation: 'dengiz',
      language: 'ar',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'الْبَحْرُ هَادِئٌ',
      sentenceTranslation: 'Dengiz tinch',
    },
    {
      word: 'غَابَة',
      translation: "o'rmon",
      language: 'ar',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'الْغَابَةُ خَضْرَاءُ',
      sentenceTranslation: "O'rmon yashil",
    },
    {
      word: 'جَامِعَة',
      translation: 'universitet',
      language: 'ar',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'هِيَ تَدْرُسُ فِي الْجَامِعَةِ',
      sentenceTranslation: 'U universitetda o’qiydi',
    },
    {
      word: 'طَالِب',
      translation: 'talaba',
      language: 'ar',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'الطَّالِبُ مُجْتَهِدٌ',
      sentenceTranslation: 'Talaba tirishqoq',
    },
    {
      word: 'اِمْتِحَان',
      translation: 'imtihon',
      language: 'ar',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'الِامْتِحَانُ صَعْبٌ',
      sentenceTranslation: 'Imtihon qiyin',
    },
    {
      word: 'سُؤَال',
      translation: 'savol',
      language: 'ar',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'عِنْدِي سُؤَالٌ',
      sentenceTranslation: 'Menda savol bor',
    },
    {
      word: 'جَوَاب',
      translation: 'javob',
      language: 'ar',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'جَوَابُكَ صَحِيحٌ',
      sentenceTranslation: "Javobingiz to'g'ri",
    },
  ],
}
