import type { NewCardRecordInput } from '@/core/db'
import type { LevelCode } from '@/core/types'

/**
 * Ingliz tili to'plami, CEFR darajalari bo'yicha.
 *
 * Har yozuvda qisqa jumla bor: u "jumla qurish" mashqi uchun ishlatiladi
 * va kontekstli kirish beradi (Krashen, i+1). Jumla bo'lmasa, o'sha mashq
 * turi bu karta uchun yaratilmaydi.
 *
 * Tarjimalar ATAYLAB bir ma'noli tanlangan va o'zaro takrorlanmaydi:
 * mashq generatori chalg'ituvchi variantlarni shu tildagi boshqa
 * so'zlardan oladi, shuning uchun ikki so'zning tarjimasi bir xil bo'lsa
 * savolning to'g'ri javobi noaniq bo'lib qolardi.
 */
export const EN_DECK: Record<LevelCode, NewCardRecordInput[]> = {
  A1: [
    {
      word: 'hello',
      translation: 'salom',
      language: 'en',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Hello my friend',
      sentenceTranslation: "Salom, do'stim",
    },
    {
      word: 'thank you',
      translation: 'rahmat',
      language: 'en',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Thank you very much',
      sentenceTranslation: 'Katta rahmat',
    },
    {
      word: 'goodbye',
      translation: 'xayr',
      language: 'en',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Goodbye, see you soon',
      sentenceTranslation: "Xayr, ko'rishguncha",
    },
    {
      word: 'please',
      translation: 'iltimos',
      language: 'en',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Please help me',
      sentenceTranslation: 'Iltimos, menga yordam bering',
    },
    {
      word: 'sorry',
      translation: 'kechirasiz',
      language: 'en',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Sorry, I am late',
      sentenceTranslation: 'Kechirasiz, men kechikdim',
    },
    {
      word: 'yes',
      translation: 'ha',
      language: 'en',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Yes, I am ready',
      sentenceTranslation: 'Ha, men tayyorman',
    },
    {
      word: 'no',
      translation: "yo'q",
      language: 'en',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'No, thank you',
      sentenceTranslation: "Yo'q, rahmat",
    },
    {
      word: 'friend',
      translation: "do'st",
      language: 'en',
      topic: 'Oila',
      level: 'A1',
      sentence: 'She is my friend',
      sentenceTranslation: "U mening do'stim",
    },
    {
      word: 'house',
      translation: 'uy',
      language: 'en',
      topic: 'Oila',
      level: 'A1',
      sentence: 'This is my house',
      sentenceTranslation: 'Bu mening uyim',
    },
    {
      word: 'mother',
      translation: 'ona',
      language: 'en',
      topic: 'Oila',
      level: 'A1',
      sentence: 'My mother is home',
      sentenceTranslation: 'Onam uyda',
    },
    {
      word: 'father',
      translation: 'ota',
      language: 'en',
      topic: 'Oila',
      level: 'A1',
      sentence: 'My father works here',
      sentenceTranslation: 'Otam shu yerda ishlaydi',
    },
    {
      word: 'child',
      translation: 'bola',
      language: 'en',
      topic: 'Oila',
      level: 'A1',
      sentence: 'The child is small',
      sentenceTranslation: 'Bola kichkina',
    },
    {
      word: 'one',
      translation: 'bir',
      language: 'en',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'I have one book',
      sentenceTranslation: 'Menda bitta kitob bor',
    },
    {
      word: 'two',
      translation: 'ikki',
      language: 'en',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Two friends are waiting',
      sentenceTranslation: "Ikki do'st kutmoqda",
    },
    {
      word: 'three',
      translation: 'uch',
      language: 'en',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'We have three rooms',
      sentenceTranslation: 'Bizda uchta xona bor',
    },
    {
      word: 'four',
      translation: "to'rt",
      language: 'en',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Four people are here',
      sentenceTranslation: "To'rt kishi shu yerda",
    },
    {
      word: 'five',
      translation: 'besh',
      language: 'en',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Five minutes, please',
      sentenceTranslation: 'Besh daqiqa, iltimos',
    },
    {
      word: 'ten',
      translation: "o'n",
      language: 'en',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Ten students are here',
      sentenceTranslation: "O'n talaba shu yerda",
    },
    {
      word: 'water',
      translation: 'suv',
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'I drink water',
      sentenceTranslation: 'Men suv ichaman',
    },
    {
      word: 'bread',
      translation: 'non',
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'The bread is fresh',
      sentenceTranslation: 'Non yangi',
    },
    {
      word: 'milk',
      translation: 'sut',
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'The milk is cold',
      sentenceTranslation: 'Sut sovuq',
    },
    {
      word: 'apple',
      translation: 'olma',
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'This apple is sweet',
      sentenceTranslation: 'Bu olma shirin',
    },
    {
      word: 'rice',
      translation: 'guruch',
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'We eat rice today',
      sentenceTranslation: 'Biz bugun guruch yeymiz',
    },
    {
      word: 'meat',
      translation: "go'sht",
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'The meat is ready',
      sentenceTranslation: "Go'sht tayyor",
    },
    {
      word: 'tea',
      translation: 'choy',
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'I like green tea',
      sentenceTranslation: "Menga ko'k choy yoqadi",
    },
    {
      word: 'salt',
      translation: 'tuz',
      language: 'en',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Add a little salt',
      sentenceTranslation: "Ozgina tuz qo'shing",
    },
    {
      word: 'red',
      translation: 'qizil',
      language: 'en',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'The apple is red',
      sentenceTranslation: 'Olma qizil',
    },
    {
      word: 'blue',
      translation: "ko'k",
      language: 'en',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'The sky is blue',
      sentenceTranslation: "Osmon ko'k",
    },
    {
      word: 'green',
      translation: 'yashil',
      language: 'en',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'The grass is green',
      sentenceTranslation: "O't yashil",
    },
    {
      word: 'black',
      translation: 'qora',
      language: 'en',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'I have black shoes',
      sentenceTranslation: 'Menda qora tufli bor',
    },
    {
      word: 'white',
      translation: 'oq',
      language: 'en',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'The house is white',
      sentenceTranslation: 'Uy oq',
    },
    {
      word: 'yellow',
      translation: 'sariq',
      language: 'en',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'The sun is yellow',
      sentenceTranslation: 'Quyosh sariq',
    },
    {
      word: 'eat',
      translation: 'yemoq',
      language: 'en',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'We eat together',
      sentenceTranslation: 'Biz birga yeymiz',
    },
    {
      word: 'drink',
      translation: 'ichmoq',
      language: 'en',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'I drink cold water',
      sentenceTranslation: 'Men sovuq suv ichaman',
    },
    {
      word: 'go',
      translation: 'bormoq',
      language: 'en',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'I go to school',
      sentenceTranslation: 'Men maktabga boraman',
    },
    {
      word: 'come',
      translation: 'kelmoq',
      language: 'en',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Please come with me',
      sentenceTranslation: 'Iltimos, men bilan keling',
    },
    {
      word: 'see',
      translation: "ko'rmoq",
      language: 'en',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'I see my friend',
      sentenceTranslation: "Men do'stimni ko'raman",
    },
    {
      word: 'sleep',
      translation: 'uxlamoq',
      language: 'en',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Children sleep early',
      sentenceTranslation: 'Bolalar erta uxlaydi',
    },
    {
      word: 'book',
      translation: 'kitob',
      language: 'en',
      topic: 'Maktab',
      level: 'A1',
      sentence: 'I read a book',
      sentenceTranslation: "Men kitob o'qiyman",
    },
    {
      word: 'morning',
      translation: 'ertalab',
      language: 'en',
      topic: 'Vaqt',
      level: 'A1',
      sentence: 'Good morning',
      sentenceTranslation: 'Xayrli tong',
    },
    {
      word: 'road',
      translation: "yo'l",
      language: 'en',
      topic: 'Sayohat',
      level: 'A1',
      sentence: 'The road is long',
      sentenceTranslation: "Yo'l uzoq",
    },
    {
      word: 'city',
      translation: 'shahar',
      language: 'en',
      topic: 'Sayohat',
      level: 'A1',
      sentence: 'The city is big',
      sentenceTranslation: 'Shahar katta',
    },
  ],

  A2: [
    {
      word: 'airport',
      translation: 'aeroport',
      language: 'en',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'The airport is far',
      sentenceTranslation: 'Aeroport uzoqda',
    },
    {
      word: 'ticket',
      translation: 'chipta',
      language: 'en',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'I bought a ticket',
      sentenceTranslation: 'Men chipta sotib oldim',
    },
    {
      word: 'train',
      translation: 'poyezd',
      language: 'en',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'The train is late',
      sentenceTranslation: 'Poyezd kechikmoqda',
    },
    {
      word: 'hotel',
      translation: 'mehmonxona',
      language: 'en',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'The hotel is clean',
      sentenceTranslation: 'Mehmonxona toza',
    },
    {
      word: 'suitcase',
      translation: 'chamadon',
      language: 'en',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'My suitcase is heavy',
      sentenceTranslation: "Chamadonim og'ir",
    },
    {
      word: 'map',
      translation: 'xarita',
      language: 'en',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'Look at the map',
      sentenceTranslation: 'Xaritaga qarang',
    },
    {
      word: 'shop',
      translation: "do'kon",
      language: 'en',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'The shop is open',
      sentenceTranslation: "Do'kon ochiq",
    },
    {
      word: 'money',
      translation: 'pul',
      language: 'en',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'I need more money',
      sentenceTranslation: "Menga ko'proq pul kerak",
    },
    {
      word: 'price',
      translation: 'narx',
      language: 'en',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'The price is high',
      sentenceTranslation: 'Narx baland',
    },
    {
      word: 'buy',
      translation: 'sotib olmoq',
      language: 'en',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'I want to buy bread',
      sentenceTranslation: 'Men non sotib olmoqchiman',
    },
    {
      word: 'cheap',
      translation: 'arzon',
      language: 'en',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'This bag is cheap',
      sentenceTranslation: 'Bu sumka arzon',
    },
    {
      word: 'expensive',
      translation: 'qimmat',
      language: 'en',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'That car is expensive',
      sentenceTranslation: 'U mashina qimmat',
    },
    {
      word: 'work',
      translation: 'ish',
      language: 'en',
      topic: 'Ish',
      level: 'A2',
      sentence: 'My work is interesting',
      sentenceTranslation: 'Mening ishim qiziqarli',
    },
    {
      word: 'office',
      translation: 'ofis',
      language: 'en',
      topic: 'Ish',
      level: 'A2',
      sentence: 'The office is closed',
      sentenceTranslation: 'Ofis yopiq',
    },
    {
      word: 'teacher',
      translation: "o'qituvchi",
      language: 'en',
      topic: 'Ish',
      level: 'A2',
      sentence: 'Our teacher is kind',
      sentenceTranslation: "O'qituvchimiz mehribon",
    },
    {
      word: 'doctor',
      translation: 'shifokor',
      language: 'en',
      topic: 'Ish',
      level: 'A2',
      sentence: 'The doctor is busy',
      sentenceTranslation: 'Shifokor band',
    },
    {
      word: 'meeting',
      translation: 'uchrashuv',
      language: 'en',
      topic: 'Ish',
      level: 'A2',
      sentence: 'The meeting starts now',
      sentenceTranslation: 'Uchrashuv hozir boshlanadi',
    },
    {
      word: 'company',
      translation: 'kompaniya',
      language: 'en',
      topic: 'Ish',
      level: 'A2',
      sentence: 'The company is new',
      sentenceTranslation: 'Kompaniya yangi',
    },
    {
      word: 'health',
      translation: 'salomatlik',
      language: 'en',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'Health is important',
      sentenceTranslation: 'Salomatlik muhim',
    },
    {
      word: 'medicine',
      translation: 'dori',
      language: 'en',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'Take this medicine',
      sentenceTranslation: 'Bu dorini iching',
    },
    {
      word: 'hospital',
      translation: 'kasalxona',
      language: 'en',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'The hospital is near',
      sentenceTranslation: 'Kasalxona yaqin',
    },
    {
      word: 'pain',
      translation: "og'riq",
      language: 'en',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'The pain is gone',
      sentenceTranslation: "Og'riq o'tdi",
    },
    {
      word: 'tired',
      translation: 'charchagan',
      language: 'en',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'I am very tired',
      sentenceTranslation: 'Men juda charchaganman',
    },
    {
      word: 'weather',
      translation: 'ob-havo',
      language: 'en',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'The weather is nice',
      sentenceTranslation: 'Ob-havo yaxshi',
    },
    {
      word: 'rain',
      translation: "yomg'ir",
      language: 'en',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'The rain stopped',
      sentenceTranslation: "Yomg'ir to'xtadi",
    },
    {
      word: 'snow',
      translation: 'qor',
      language: 'en',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'Snow covers the city',
      sentenceTranslation: 'Qor shaharni qopladi',
    },
    {
      word: 'wind',
      translation: 'shamol',
      language: 'en',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'The wind is strong',
      sentenceTranslation: 'Shamol kuchli',
    },
    {
      word: 'sun',
      translation: 'quyosh',
      language: 'en',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'The sun is warm',
      sentenceTranslation: 'Quyosh iliq',
    },
    {
      word: 'cold',
      translation: 'sovuq',
      language: 'en',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'The water is cold',
      sentenceTranslation: 'Suv sovuq',
    },
    {
      word: 'week',
      translation: 'hafta',
      language: 'en',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'I work every week',
      sentenceTranslation: 'Men har hafta ishlayman',
    },
    {
      word: 'year',
      translation: 'yil',
      language: 'en',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'This year is better',
      sentenceTranslation: 'Bu yil yaxshiroq',
    },
    {
      word: 'hour',
      translation: 'soat',
      language: 'en',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'Wait one hour',
      sentenceTranslation: 'Bir soat kuting',
    },
    {
      word: 'day',
      translation: 'kun',
      language: 'en',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'The day was long',
      sentenceTranslation: "Kun uzoq bo'ldi",
    },
    {
      word: 'tomorrow',
      translation: 'ertaga',
      language: 'en',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'We meet tomorrow',
      sentenceTranslation: 'Biz ertaga uchrashamiz',
    },
    {
      word: 'always',
      translation: 'doim',
      language: 'en',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'She always helps',
      sentenceTranslation: 'U doim yordam beradi',
    },
  ],

  B1: [
    {
      word: 'decision',
      translation: 'qaror',
      language: 'en',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'It was a hard decision',
      sentenceTranslation: 'Bu qiyin qaror edi',
    },
    {
      word: 'opinion',
      translation: 'fikr',
      language: 'en',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'Give me your opinion',
      sentenceTranslation: 'Fikringizni ayting',
    },
    {
      word: 'agree',
      translation: "rozi bo'lmoq",
      language: 'en',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'I agree with you',
      sentenceTranslation: 'Men siz bilan roziman',
    },
    {
      word: 'explain',
      translation: 'tushuntirmoq',
      language: 'en',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'Please explain the rule',
      sentenceTranslation: 'Iltimos, qoidani tushuntiring',
    },
    {
      word: 'suggest',
      translation: 'taklif qilmoq',
      language: 'en',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'I suggest another plan',
      sentenceTranslation: 'Men boshqa reja taklif qilaman',
    },
    {
      word: 'happy',
      translation: 'baxtli',
      language: 'en',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'She looks happy today',
      sentenceTranslation: "U bugun baxtli ko'rinadi",
    },
    {
      word: 'sad',
      translation: 'xafa',
      language: 'en',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'He was sad then',
      sentenceTranslation: "U o'shanda xafa edi",
    },
    {
      word: 'fear',
      translation: "qo'rquv",
      language: 'en',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'Fear stops many people',
      sentenceTranslation: "Qo'rquv ko'p odamni to'xtatadi",
    },
    {
      word: 'joy',
      translation: 'quvonch',
      language: 'en',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'Her joy was real',
      sentenceTranslation: 'Uning quvonchi chin edi',
    },
    {
      word: 'surprise',
      translation: 'hayrat',
      language: 'en',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'The news caused surprise',
      sentenceTranslation: "Yangilik hayrat uyg'otdi",
    },
    {
      word: 'society',
      translation: 'jamiyat',
      language: 'en',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'Society changes slowly',
      sentenceTranslation: "Jamiyat sekin o'zgaradi",
    },
    {
      word: 'law',
      translation: 'qonun',
      language: 'en',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'The law is clear',
      sentenceTranslation: 'Qonun aniq',
    },
    {
      word: 'government',
      translation: 'hukumat',
      language: 'en',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'The government made rules',
      sentenceTranslation: 'Hukumat qoidalar chiqardi',
    },
    {
      word: 'citizen',
      translation: 'fuqaro',
      language: 'en',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'Every citizen has duties',
      sentenceTranslation: 'Har bir fuqaroning burchi bor',
    },
    {
      word: 'freedom',
      translation: 'erkinlik',
      language: 'en',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'Freedom needs responsibility',
      sentenceTranslation: "Erkinlik mas'uliyat talab qiladi",
    },
    {
      word: 'computer',
      translation: 'kompyuter',
      language: 'en',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'My computer is slow',
      sentenceTranslation: 'Kompyuterim sekin',
    },
    {
      word: 'network',
      translation: 'tarmoq',
      language: 'en',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'The network is down',
      sentenceTranslation: 'Tarmoq ishlamayapti',
    },
    {
      word: 'data',
      translation: "ma'lumot",
      language: 'en',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'We lost the data',
      sentenceTranslation: "Biz ma'lumotni yo'qotdik",
    },
    {
      word: 'screen',
      translation: 'ekran',
      language: 'en',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'The screen is bright',
      sentenceTranslation: 'Ekran yorqin',
    },
    {
      word: 'device',
      translation: 'qurilma',
      language: 'en',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'This device is useful',
      sentenceTranslation: 'Bu qurilma foydali',
    },
    {
      word: 'idea',
      translation: "g'oya",
      language: 'en',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'That is a good idea',
      sentenceTranslation: "Bu yaxshi g'oya",
    },
    {
      word: 'reason',
      translation: 'sabab',
      language: 'en',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Tell me the reason',
      sentenceTranslation: 'Menga sababni ayting',
    },
    {
      word: 'experience',
      translation: 'tajriba',
      language: 'en',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Experience teaches us',
      sentenceTranslation: "Tajriba bizni o'rgatadi",
    },
    {
      word: 'knowledge',
      translation: 'bilim',
      language: 'en',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Knowledge grows slowly',
      sentenceTranslation: "Bilim sekin o'sadi",
    },
    {
      word: 'change',
      translation: "o'zgarish",
      language: 'en',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Change takes time',
      sentenceTranslation: "O'zgarish vaqt talab qiladi",
    },
  ],
}
