import type { NewCardRecordInput } from '@/core/db'
import type { LevelCode } from '@/core/types'

/**
 * AVTOMATIK YARATILGAN — qo'lda tahrirlamang.
 * Manba: scripts/import-vocab.mjs. Import qilingan lug'at (jumlasiz).
 */
export const EN_IMPORTED: Record<LevelCode, NewCardRecordInput[]> = {
  A1: [
    {
      word: 'living',
      translation: 'yashash',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'works',
      translation: 'ishlaydi',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'talking',
      translation: 'gaplashish',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'study',
      translation: "o'rganish",
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'march',
      translation: 'marsh',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'gets',
      translation: 'oladi',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'self',
      translation: "o'zini",
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'wants',
      translation: 'istaydi',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'held',
      translation: "o'tkazildi",
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'points',
      translation: 'ball',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'shows',
      translation: "ko'rsatadi",
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'rest',
      translation: 'dam olish',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'department',
      translation: "bo'limi",
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'played',
      translation: "o'ynadi",
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'goes',
      translation: 'ketadi',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'shot',
      translation: 'otish',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'june',
      translation: 'iyun',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'total',
      translation: 'jami',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'personal',
      translation: 'shaxsiy',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'english',
      translation: 'ingliz',
      language: 'en',
      topic: 'Enterprise A1-1',
      level: 'A1',
    },
    {
      word: 'happen',
      translation: "sodir bo'ladi",
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'problems',
      translation: 'muammolar',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'weeks',
      translation: 'haftalar',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'april',
      translation: 'aprel',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'middle',
      translation: "o'rtada",
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'july',
      translation: 'iyul',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'tried',
      translation: 'harakat qildi',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'sent',
      translation: 'yuborilgan',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'received',
      translation: 'olingan',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'longer',
      translation: 'uzoqroq',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'giving',
      translation: 'berish',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'september',
      translation: 'sentyabr',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'fast',
      translation: 'tez',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'countries',
      translation: 'mamlakatlar',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'england',
      translation: 'Angliya',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'groups',
      translation: 'guruhlar',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'looked',
      translation: 'qaradi',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'language',
      translation: 'til',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'august',
      translation: 'avgust',
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'related',
      translation: "bog'liq",
      language: 'en',
      topic: 'Enterprise A1-2',
      level: 'A1',
    },
    {
      word: 'french',
      translation: 'fransuz',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'decided',
      translation: 'qaror qildi',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'january',
      translation: 'yanvar',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'turned',
      translation: 'aylantirildi',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'seven',
      translation: 'etti',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'events',
      translation: 'voqealar',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'washington',
      translation: 'Vashington',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'writing',
      translation: 'yozish',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'parts',
      translation: 'qismlar',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'daughter',
      translation: 'qizim',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'built',
      translation: 'qurilgan',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'began',
      translation: 'boshlandi',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'december',
      translation: 'dekabr',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'ones',
      translation: 'birlar',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'rules',
      translation: 'qoidalar',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'australia',
      translation: 'avstraliya',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'ways',
      translation: "yo'llari",
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'base',
      translation: 'asos',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'schools',
      translation: 'maktablar',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'followed',
      translation: 'ergashdi',
      language: 'en',
      topic: 'Enterprise A1-3',
      level: 'A1',
    },
    {
      word: 'dark',
      translation: "qorong'i",
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'europe',
      translation: 'Yevropa',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'india',
      translation: 'Hindiston',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'places',
      translation: 'joylar',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'speak',
      translation: 'gapirish',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'shall',
      translation: 'qiladi',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'provided',
      translation: 'taqdim etilgan',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'chinese',
      translation: 'xitoy',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'station',
      translation: 'stantsiya',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'moved',
      translation: "ko'chirildi",
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'sort',
      translation: 'saralash',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'miles',
      translation: 'mil',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'jobs',
      translation: "ish o'rinlari",
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'leaving',
      translation: 'ketish',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'canada',
      translation: 'kanada',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'teams',
      translation: 'jamoalar',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'heavy',
      translation: "og'ir",
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'friday',
      translation: 'juma',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'asking',
      translation: "so'rab",
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'costs',
      translation: 'xarajatlar',
      language: 'en',
      topic: 'Enterprise A1-4',
      level: 'A1',
    },
    {
      word: 'wow',
      translation: 'Voy-buy',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'includes',
      translation: "o'z ichiga oladi",
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'pre',
      translation: 'oldindan',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'dad',
      translation: 'dada',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'stories',
      translation: 'hikoyalar',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'france',
      translation: 'fransiya',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'opening',
      translation: 'ochilish',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'features',
      translation: 'Xususiyatlari',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'reach',
      translation: 'erishish',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'reasons',
      translation: 'sabablari',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'russia',
      translation: 'Rossiya',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'sunday',
      translation: 'yakshanba',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'wear',
      translation: 'kiyish',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'older',
      translation: 'yoshi kattaroq',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'telling',
      translation: 'aytib',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'africa',
      translation: 'afrika',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'speaking',
      translation: 'Gapirmoqda',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'names',
      translation: 'ismlar',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'activities',
      translation: 'tadbirlar',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'christmas',
      translation: 'Rojdestvo',
      language: 'en',
      topic: 'Enterprise A1-5',
      level: 'A1',
    },
    {
      word: 'indian',
      translation: 'hind',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'driving',
      translation: 'haydash',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'germany',
      translation: 'Germaniya',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'feels',
      translation: 'his qiladi',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'shown',
      translation: "ko'rsatilgan",
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'japan',
      translation: 'Yaponiya',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'parties',
      translation: 'partiyalar',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'lived',
      translation: 'yashagan',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'broken',
      translation: 'buzilgan',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'saturday',
      translation: 'shanba',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'ran',
      translation: 'yugurdi',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'comments',
      translation: 'sharhlar',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'stars',
      translation: 'yulduzlar',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'eating',
      translation: 'ovqatlanish',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'royal',
      translation: 'qirollik',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'opened',
      translation: 'ochildi',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'learned',
      translation: "o'rgangan",
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'types',
      translation: 'turlari',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'cities',
      translation: 'shaharlar',
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'plays',
      translation: "o'ynaydi",
      language: 'en',
      topic: 'Enterprise A1-6',
      level: 'A1',
    },
    {
      word: 'starts',
      translation: 'boshlanadi',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'mentioned',
      translation: 'qayd etilgan',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'photos',
      translation: 'fotosuratlar',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'paris',
      translation: 'parij',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'actions',
      translation: 'harakatlar',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'metal',
      translation: 'metall',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'rose',
      translation: 'atirgul',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'japanese',
      translation: 'yapon',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'monday',
      translation: 'dushanba',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'happening',
      translation: "sodir bo'lmoqda",
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'usa',
      translation: 'AQSh',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'leaves',
      translation: 'barglari',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'arrived',
      translation: 'yetib keldi',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'till',
      translation: 'gacha',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'items',
      translation: 'buyumlar',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'thinks',
      translation: "o'ylaydi",
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'shut',
      translation: 'yoping',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'units',
      translation: 'birliklar',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'dogs',
      translation: 'itlar',
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'copy',
      translation: "nusxa ko'chirish",
      language: 'en',
      topic: 'Enterprise A1-7',
      level: 'A1',
    },
    {
      word: 'turns',
      translation: 'aylanadi',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'birthday',
      translation: "tug'ilgan kun",
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'stick',
      translation: 'tayoq',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'ends',
      translation: 'tugaydi',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'mexico',
      translation: 'meksika',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'buying',
      translation: 'sotib olish',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'offers',
      translation: 'taklif qiladi',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'bigger',
      translation: 'kattaroq',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'teachers',
      translation: "o'qituvchilar",
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'models',
      translation: 'modellar',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'discovered',
      translation: 'kashf etilgan',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'likes',
      translation: 'yoqtiradi',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'spanish',
      translation: 'ispancha',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'angeles',
      translation: 'farishtalar',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'lee',
      translation: 'li',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'orders',
      translation: 'buyurtmalar',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'houses',
      translation: 'uylar',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'britain',
      translation: 'Britaniya',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'windows',
      translation: 'derazalar',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'decisions',
      translation: 'qarorlar',
      language: 'en',
      topic: 'Enterprise A1-8',
      level: 'A1',
    },
    {
      word: 'pieces',
      translation: 'dona',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'fantastic',
      translation: 'fantastik',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'flying',
      translation: 'uchish',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'discussion',
      translation: 'muhokama',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'drinking',
      translation: 'ichish',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'articles',
      translation: 'maqolalar',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'wins',
      translation: "g'alaba qozonadi",
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'canadian',
      translation: 'kanadalik',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'fixed',
      translation: 'belgilangan',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'trees',
      translation: 'daraxtlar',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'ray',
      translation: 'nur',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'banks',
      translation: 'banklar',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'scotland',
      translation: 'Shotlandiya',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'walked',
      translation: 'yurdi',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'adding',
      translation: "qo'shish",
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
    {
      word: 'tests',
      translation: 'testlar',
      language: 'en',
      topic: 'Enterprise A1-9',
      level: 'A1',
    },
  ],
  A2: [
    {
      word: 'saved',
      translation: 'saqlangan',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'listening',
      translation: 'tinglash',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'italy',
      translation: 'Italiya',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'italian',
      translation: 'italyan',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'ireland',
      translation: 'irlandiya',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'lay',
      translation: 'yotish',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'films',
      translation: 'filmlar',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'sat',
      translation: "o'tirdi",
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'faster',
      translation: 'tezroq',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'tuesday',
      translation: 'seshanba',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'falls',
      translation: 'tushadi',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'thursday',
      translation: 'payshanba',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'alex',
      translation: 'aleks',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'spoke',
      translation: 'gapirdi',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'scared',
      translation: "qo'rqib ketdi",
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'wales',
      translation: 'Uels',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'tickets',
      translation: 'chiptalar',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'scottish',
      translation: 'shotland',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'spain',
      translation: 'Ispaniya',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'wednesday',
      translation: 'chorshanba',
      language: 'en',
      topic: 'Enterprise A2-1',
      level: 'A2',
    },
    {
      word: 'faces',
      translation: 'yuzlar',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'sees',
      translation: "ko'radi",
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'singing',
      translation: 'kuylash',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'brazil',
      translation: 'Braziliya',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'tips',
      translation: 'maslahatlar',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'replace',
      translation: 'almashtiring',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'independence',
      translation: 'mustaqillik',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'stood',
      translation: 'turdi',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'turkey',
      translation: 'turkiya',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'excuse',
      translation: 'uzr',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'sleeping',
      translation: 'uxlash',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'staying',
      translation: 'qolish',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'ban',
      translation: 'taqiqlash',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'exciting',
      translation: 'hayajonli',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'dates',
      translation: 'sanalar',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'driven',
      translation: 'haydalgan',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'sydney',
      translation: 'Sidney',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'wilson',
      translation: 'Vilson',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'seasons',
      translation: 'fasllar',
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'balls',
      translation: "to'plar",
      language: 'en',
      topic: 'Enterprise A2-2',
      level: 'A2',
    },
    {
      word: 'hollywood',
      translation: 'gollivud',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'statements',
      translation: 'bayonotlar',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'objects',
      translation: "ob'ektlar",
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'visited',
      translation: 'tashrif buyurdi',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'dancing',
      translation: 'raqsga tushish',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'sons',
      translation: "o'g'illari",
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'greek',
      translation: 'yunoncha',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'memories',
      translation: 'xotiralar',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'mountains',
      translation: "tog'lar",
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'repeat',
      translation: 'takrorlang',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'visitors',
      translation: 'tashrif buyuruvchilar',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'davis',
      translation: 'Devis',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'cabinet',
      translation: 'kabinet',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'offices',
      translation: 'idoralar',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'cats',
      translation: 'mushuklar',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'threw',
      translation: 'tashladi',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'rome',
      translation: 'Rim',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'mistakes',
      translation: 'xatolar',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'egypt',
      translation: 'Misr',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'babies',
      translation: 'chaqaloqlar',
      language: 'en',
      topic: 'Enterprise A2-3',
      level: 'A2',
    },
    {
      word: 'waters',
      translation: 'suvlar',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'visiting',
      translation: 'tashrif buyurish',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'tag',
      translation: 'teg',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'asks',
      translation: "so'radi",
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'episodes',
      translation: 'epizodlar',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'moscow',
      translation: 'moskva',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'mum',
      translation: 'onam',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'mexican',
      translation: 'meksikalik',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'anthony',
      translation: 'entoni',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'sweden',
      translation: 'shved',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'atlantic',
      translation: 'atlantika',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'gary',
      translation: 'gari',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'arrive',
      translation: 'yetib kelish',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'lessons',
      translation: 'darslar',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'lists',
      translation: "ro'yxatlar",
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'oxford',
      translation: 'Oksford',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'publishing',
      translation: 'nashr qilish',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'meets',
      translation: 'uchrashadi',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'jean',
      translation: 'jan',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'writes',
      translation: 'yozadi',
      language: 'en',
      topic: 'Enterprise A2-4',
      level: 'A2',
    },
    {
      word: 'wishes',
      translation: 'tilaklar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'ties',
      translation: 'rishtalar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'restaurants',
      translation: 'restoranlar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'ate',
      translation: 'yedi',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'maria',
      translation: 'mariya',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'hospitals',
      translation: 'kasalxonalar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'jokes',
      translation: 'hazillar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'computers',
      translation: 'kompyuterlar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'crossing',
      translation: "kesib o'tish",
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'walks',
      translation: 'yuradi',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'packed',
      translation: 'qadoqlangan',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'sec',
      translation: 'sek',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'invite',
      translation: 'taklif qiling',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'visits',
      translation: 'tashriflar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'rivers',
      translation: 'daryolar',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'lisa',
      translation: 'liza',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'delhi',
      translation: 'Dehli',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'polish',
      translation: 'jilo',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'dec',
      translation: 'dek',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'edinburgh',
      translation: 'edinburg',
      language: 'en',
      topic: 'Enterprise A2-5',
      level: 'A2',
    },
    {
      word: 'greece',
      translation: 'Gretsiya',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'drives',
      translation: 'haydovchilar',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'requests',
      translation: "so'rovlar",
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'topics',
      translation: 'mavzular',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'tokyo',
      translation: 'tokio',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'bold',
      translation: 'jasur',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'jerry',
      translation: 'jerri',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'waited',
      translation: 'kutdi',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'indians',
      translation: 'hindular',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'reads',
      translation: "o'qiydi",
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'jumped',
      translation: 'sakrab tushdi',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'poland',
      translation: 'Polsha',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'oldest',
      translation: 'eng qadimgi',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'terry',
      translation: 'terri',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'steven',
      translation: 'Stiven',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'suggestions',
      translation: 'takliflar',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'belongs',
      translation: 'tegishli',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'switzerland',
      translation: 'Shveytsariya',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'describing',
      translation: 'tasvirlab berish',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'leo',
      translation: 'arslon',
      language: 'en',
      topic: 'Enterprise A2-6',
      level: 'A2',
    },
    {
      word: 'barcelona',
      translation: 'barselona',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'hotels',
      translation: 'mehmonxonalar',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'holidays',
      translation: 'bayramlar',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'dig',
      translation: 'qazish',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'woke',
      translation: "uyg'ondi",
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'eagles',
      translation: 'burgutlar',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'habits',
      translation: 'odatlar',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'correctly',
      translation: "to'g'ri",
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'egyptian',
      translation: 'misrlik',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'hung',
      translation: 'osilgan',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'stole',
      translation: "o'g'irlagan",
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'abilities',
      translation: 'qobiliyatlar',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'arc',
      translation: 'yoy',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'paintings',
      translation: 'rasmlar',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'amy',
      translation: 'emi',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'cave',
      translation: "g'or",
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'meals',
      translation: 'ovqatlar',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'taxi',
      translation: 'taksi',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'jennifer',
      translation: 'Jenifer',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'mississippi',
      translation: 'Missisipi',
      language: 'en',
      topic: 'Enterprise A2-7',
      level: 'A2',
    },
    {
      word: 'lions',
      translation: 'sherlar',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'slept',
      translation: 'uxlab qoldi',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'oak',
      translation: 'eman',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'earl',
      translation: 'graf',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'dressing',
      translation: 'kiyinish',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'clouds',
      translation: 'bulutlar',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'introducing',
      translation: 'tanishtirish',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'belgium',
      translation: 'belgiya',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'dishes',
      translation: 'idishlar',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'eaten',
      translation: 'yeydi',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'eleven',
      translation: "o'n bir",
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'climbing',
      translation: 'toqqa chiqish',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'intentions',
      translation: 'niyatlar',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'cooked',
      translation: 'pishirilgan',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'arrives',
      translation: 'keladi',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'catherine',
      translation: 'Ketrin',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'holland',
      translation: 'Gollandiya',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'ore',
      translation: 'ruda',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'pine',
      translation: "qarag'ay",
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'sang',
      translation: 'kuyladi',
      language: 'en',
      topic: 'Enterprise A2-8',
      level: 'A2',
    },
    {
      word: 'cam',
      translation: 'kamera',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'flies',
      translation: 'chivinlar',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'wears',
      translation: 'kiyadi',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'pets',
      translation: 'uy hayvonlari',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'forests',
      translation: "o'rmonlar",
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'montreal',
      translation: 'Monreal',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'spencer',
      translation: 'Spenser',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'saves',
      translation: 'saqlaydi',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'magazines',
      translation: 'jurnallar',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'tourists',
      translation: 'sayyohlar',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'rides',
      translation: 'minish',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'achievements',
      translation: 'yutuqlar',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'freezing',
      translation: 'muzlash',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'booked',
      translation: 'band qilingan',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'travels',
      translation: 'sayohatlar',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'ranges',
      translation: 'diapazonlari',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'hannah',
      translation: 'xanna',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'dot',
      translation: 'nuqta',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'symbols',
      translation: 'belgilar',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'clips',
      translation: 'kliplar',
      language: 'en',
      topic: 'Enterprise A2-9',
      level: 'A2',
    },
    {
      word: 'sunset',
      translation: 'quyosh botishi',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'smells',
      translation: 'hidlaydi',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'aliens',
      translation: 'musofirlar',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'carol',
      translation: 'Kerol',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'cleaned',
      translation: 'tozalangan',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'ordering',
      translation: 'buyurtma berish',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'doug',
      translation: 'dug',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'reporters',
      translation: 'muxbirlar',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'posters',
      translation: 'plakatlar',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'expressing',
      translation: 'ifodalash',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'pal',
      translation: "do'stim",
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'mediterranean',
      translation: "o'rta er dengizi",
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'travelled',
      translation: 'sayohat qilgan',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'ottawa',
      translation: 'Ottava',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'shining',
      translation: 'porlash',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'linking',
      translation: "bog'lash",
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'pee',
      translation: 'siyish',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'boarding',
      translation: 'bortga chiqish',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'toes',
      translation: 'oyoq barmoqlari',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'bees',
      translation: 'asalarilar',
      language: 'en',
      topic: 'Enterprise A2-10',
      level: 'A2',
    },
    {
      word: 'sharks',
      translation: 'akulalar',
      language: 'en',
      topic: 'Enterprise A2-11',
      level: 'A2',
    },
    {
      word: 'beaches',
      translation: 'plyajlar',
      language: 'en',
      topic: 'Enterprise A2-11',
      level: 'A2',
    },
    {
      word: 'sixteen',
      translation: "o'n olti",
      language: 'en',
      topic: 'Enterprise A2-11',
      level: 'A2',
    },
    {
      word: 'pierre',
      translation: 'Per',
      language: 'en',
      topic: 'Enterprise A2-11',
      level: 'A2',
    },
    {
      word: 'appointments',
      translation: 'uchrashuvlar',
      language: 'en',
      topic: 'Enterprise A2-11',
      level: 'A2',
    },
    {
      word: 'predictions',
      translation: 'bashoratlar',
      language: 'en',
      topic: 'Enterprise A2-11',
      level: 'A2',
    },
  ],
  B1: [
    {
      word: 'annie',
      translation: 'enni',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'decorated',
      translation: 'bezatilgan',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'seas',
      translation: 'dengizlar',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'sixty',
      translation: 'oltmish',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'venice',
      translation: 'venetsiya',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'cows',
      translation: 'sigirlar',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'expressions',
      translation: 'ifodalar',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'descriptions',
      translation: 'tavsiflar',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'athens',
      translation: 'Afina',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'hungary',
      translation: 'vengriya',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'rode',
      translation: 'minib',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'sophie',
      translation: 'sofi',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'finishes',
      translation: 'tugatadi',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'cardinal',
      translation: 'kardinal',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'dancers',
      translation: 'raqqosalar',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'jenny',
      translation: 'Jenni',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'costumes',
      translation: 'kostyumlar',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'rex',
      translation: 'reks',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'museums',
      translation: 'muzeylar',
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'fourteen',
      translation: "o'n to'rt",
      language: 'en',
      topic: 'Enterprise B1-1',
      level: 'B1',
    },
    {
      word: 'masks',
      translation: 'maskalar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'wee',
      translation: 'vay',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'seventeen',
      translation: "o'n etti",
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'festivals',
      translation: 'festivallar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'browns',
      translation: 'jigarranglar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'mon',
      translation: 'dus',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'inviting',
      translation: 'taklif qiluvchi',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'para',
      translation: 'paragraf',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'seals',
      translation: 'muhrlar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'cakes',
      translation: 'keklar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'heavier',
      translation: "og'irroq",
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'cairo',
      translation: 'Qohira',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'sights',
      translation: 'diqqatga sazovor joylar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'elephants',
      translation: 'fillar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'eighteen',
      translation: "o'n sakkiz",
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'alt',
      translation: 'muqobil',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'bubbles',
      translation: 'pufakchalar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'dances',
      translation: 'raqslar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'seventy',
      translation: 'yetmish',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'flats',
      translation: 'kvartiralar',
      language: 'en',
      topic: 'Enterprise B1-2',
      level: 'B1',
    },
    {
      word: 'sandwiches',
      translation: 'sendvichlar',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'oceans',
      translation: 'okeanlar',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'recycling',
      translation: 'qayta ishlash',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'cons',
      translation: 'kamchiliklari',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'sundays',
      translation: 'yakshanba kunlari',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'advertisements',
      translation: 'reklamalar',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'eighty',
      translation: 'sakson',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'screamed',
      translation: 'qichqirdi',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'sleeps',
      translation: 'uxlaydi',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'warsaw',
      translation: 'Varshava',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'theo',
      translation: 'teo',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'cooks',
      translation: 'oshpazlar',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'statues',
      translation: 'haykallar',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'evenings',
      translation: 'kechqurunlari',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'ridden',
      translation: 'minilgan',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'biscuits',
      translation: 'pechene',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'shines',
      translation: 'porlaydi',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'mare',
      translation: 'toychoq',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'nineteen',
      translation: "o'n to'qqiz",
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'cindy',
      translation: 'Sindi',
      language: 'en',
      topic: 'Enterprise B1-3',
      level: 'B1',
    },
    {
      word: 'paragraphs',
      translation: 'paragraflar',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'erie',
      translation: 'eri',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'pubs',
      translation: 'pablar',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'emergencies',
      translation: 'favqulodda vaziyatlar',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'sect',
      translation: 'mazhab',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'antarctica',
      translation: 'antarktida',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'practise',
      translation: 'amaliyot',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'dickens',
      translation: 'dikens',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'routines',
      translation: 'tartiblar',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'canoe',
      translation: 'kanoe',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'hee',
      translation: 'he',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'reese',
      translation: 'ris',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'strauss',
      translation: 'Shtraus',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'heed',
      translation: "e'tibor bering",
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'roe',
      translation: "qoraqarag'ali",
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'pronouns',
      translation: 'olmoshlar',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'invitations',
      translation: 'taklifnomalar',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'indefinite',
      translation: 'noaniq',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'bicycles',
      translation: 'velosipedlar',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'mandy',
      translation: 'mandi',
      language: 'en',
      topic: 'Enterprise B1-4',
      level: 'B1',
    },
    {
      word: 'pizzas',
      translation: 'pizzalar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'pyramids',
      translation: 'piramidalar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'nationalities',
      translation: 'millatlar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'woe',
      translation: 'voy',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'salads',
      translation: 'salatlar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'vinci',
      translation: 'Vinchi',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'postcards',
      translation: 'otkritkalar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'presley',
      translation: 'presli',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'eiffel',
      translation: 'eyfel',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'synonyms',
      translation: 'sinonimlar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'eth',
      translation: 'et',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'antwerp',
      translation: 'antverpen',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'rung',
      translation: 'qadam',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'cushions',
      translation: 'yostiqlar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'som',
      translation: "so'm",
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'telephones',
      translation: 'telefonlar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'spelt',
      translation: 'yozilgan',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'possessive',
      translation: 'egalik qiluvchi',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'teas',
      translation: 'choylar',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'seine',
      translation: 'sein',
      language: 'en',
      topic: 'Enterprise B1-5',
      level: 'B1',
    },
    {
      word: 'opposites',
      translation: 'qarama-qarshiliklar',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'coe',
      translation: 'koe',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'scorpio',
      translation: 'chayon',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'louvre',
      translation: 'luvr',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'danube',
      translation: 'dunay',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'dunkirk',
      translation: 'dunkerk',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'himalayas',
      translation: 'Himalaylar',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'sprang',
      translation: 'otilib chiqdi',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'nightclubs',
      translation: 'tungi klublar',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'canes',
      translation: 'qamishlar',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'vases',
      translation: 'vazalar',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'coy',
      translation: 'uyatchan',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'soups',
      translation: "sho'rvalar",
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'mow',
      translation: 'eymoq',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'consonant',
      translation: 'undosh',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'pane',
      translation: 'panel',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'melrose',
      translation: 'melroz',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'brazilians',
      translation: 'braziliyaliklar',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'coon',
      translation: 'qaqshatqich',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'gorillas',
      translation: 'gorillalar',
      language: 'en',
      topic: 'Enterprise B1-6',
      level: 'B1',
    },
    {
      word: 'virgo',
      translation: 'bokira',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'trams',
      translation: 'tramvaylar',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'forgave',
      translation: 'kechirdi',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'roared',
      translation: 'baqirdi',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'wot',
      translation: 'vot',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'forbade',
      translation: 'taqiqlagan',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'kangaroos',
      translation: 'kengurular',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'mee',
      translation: 'meni',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'seer',
      translation: "ko'ruvchi",
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'newbury',
      translation: 'Nyuberi',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'canoes',
      translation: 'kanoelar',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'swims',
      translation: 'suzadi',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'parrots',
      translation: "to'tiqushlar",
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'sphinx',
      translation: 'sfenks',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'sieve',
      translation: 'elak',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'sill',
      translation: 'tokcha',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'sora',
      translation: "so'ra",
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'smelt',
      translation: 'hidlash',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'hamburgers',
      translation: 'gamburgerlar',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'kirsty',
      translation: 'kirsti',
      language: 'en',
      topic: 'Enterprise B1-7',
      level: 'B1',
    },
    {
      word: 'chimpanzees',
      translation: 'shimpanzelar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'snows',
      translation: 'qorlar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'ores',
      translation: 'rudalar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'ame',
      translation: 'omin',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'pisces',
      translation: 'baliqlar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'firework',
      translation: 'salyut',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'consonants',
      translation: 'undosh tovushlar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'ets',
      translation: 'va boshqalar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'auth',
      translation: 'autent',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'headings',
      translation: 'sarlavhalar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'eases',
      translation: 'osonlashtiradi',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'hos',
      translation: 'xos',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'paddling',
      translation: 'eshkak eshish',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'scat',
      translation: 'skat',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'ied',
      translation: 'ed',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'giraffes',
      translation: 'jirafalar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'cupboards',
      translation: 'shkaflar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'oat',
      translation: "jo'xori",
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'highlander',
      translation: "tog'li",
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'cassettes',
      translation: 'kassetalar',
      language: 'en',
      topic: 'Enterprise B1-8',
      level: 'B1',
    },
    {
      word: 'sewed',
      translation: 'tikilgan',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'curie',
      translation: 'kuri',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'lain',
      translation: 'yotgan',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'cig',
      translation: 'sigaret',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'colosseum',
      translation: 'kolizey',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'zebras',
      translation: 'zebralar',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'picnics',
      translation: 'pikniklar',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'cuss',
      translation: "g'iybat",
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'wane',
      translation: 'susaydi',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'sunbathing',
      translation: 'quyoshga botish',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'aeroplanes',
      translation: 'samolyotlar',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'pag',
      translation: 'sahifa',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'chica',
      translation: 'chika',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'backstreet',
      translation: "orqa ko'cha",
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'stank',
      translation: 'hidlamoq',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'sacs',
      translation: 'qoplar',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'cava',
      translation: 'kava',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'ene',
      translation: 'en',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'aerosols',
      translation: 'aerozollar',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'cots',
      translation: 'karyolalar',
      language: 'en',
      topic: 'Enterprise B1-9',
      level: 'B1',
    },
    {
      word: 'ordinal',
      translation: 'tartibli',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'participle',
      translation: 'kesim',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'tenses',
      translation: 'zamonlar',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'folkestone',
      translation: 'xalq tosh',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'oas',
      translation: 'voha',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'ies',
      translation: 'es',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'whe',
      translation: 'qachon',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'johnsons',
      translation: 'Jonsons',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'snowballs',
      translation: "qor to'plari",
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'sate',
      translation: "to'yingan",
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'phe',
      translation: 'ph',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'auc',
      translation: 'auk',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'ices',
      translation: 'muzlar',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'pees',
      translation: 'pesh',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'prepositions',
      translation: 'predloglar',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'eck',
      translation: 'ek',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'prue',
      translation: 'toza',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'armchairs',
      translation: 'kreslolar',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'settee',
      translation: 'choyshab',
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'seers',
      translation: "ko'ruvchilar",
      language: 'en',
      topic: 'Enterprise B1-10',
      level: 'B1',
    },
    {
      word: 'nessie',
      translation: 'nesi',
      language: 'en',
      topic: 'Enterprise B1-11',
      level: 'B1',
    },
    {
      word: 'sess',
      translation: 'seans',
      language: 'en',
      topic: 'Enterprise B1-11',
      level: 'B1',
    },
    {
      word: 'alittle',
      translation: 'ozroq',
      language: 'en',
      topic: 'Enterprise B1-11',
      level: 'B1',
    },
    {
      word: 'shee',
      translation: 'shi',
      language: 'en',
      topic: 'Enterprise B1-11',
      level: 'B1',
    },
    {
      word: 'wana',
      translation: 'vana',
      language: 'en',
      topic: 'Enterprise B1-11',
      level: 'B1',
    },
    {
      word: 'wher',
      translation: 'qayerda',
      language: 'en',
      topic: 'Enterprise B1-11',
      level: 'B1',
    },
    {
      word: 'iwas',
      translation: 'men edi',
      language: 'en',
      topic: 'Enterprise B1-11',
      level: 'B1',
    },
  ],
}
