import type { NewCardRecordInput } from '@/core/db'
import type { LevelCode } from '@/core/types'

/**
 * Qo'lda tanlangan qo'shimcha ruscha lug'at (jumlasiz).
 * Manba: scripts/make-ru-extra.mjs.
 */
export const RU_EXTRA: Record<LevelCode, NewCardRecordInput[]> = {
  A1: [
    {
      word: 'читать',
      translation: "o'qimoq",
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'писать',
      translation: 'yozmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'говорить',
      translation: 'gapirmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'слушать',
      translation: 'tinglamoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'работать',
      translation: 'ishlamoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'играть',
      translation: "o'ynamoq",
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'петь',
      translation: 'kuylamoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'бежать',
      translation: 'yugurmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'прыгать',
      translation: 'sakramoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'открыть',
      translation: 'ochmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'закрыть',
      translation: 'yopmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'давать',
      translation: 'bermoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'любить',
      translation: 'sevmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'знать',
      translation: 'bilmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'думать',
      translation: "o'ylamoq",
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'помнить',
      translation: 'eslamoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'забыть',
      translation: 'unutmoq',
      language: 'ru',
      topic: "Fe'llar",
      level: 'A1',
    },
    {
      word: 'большой',
      translation: 'katta',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'маленький',
      translation: 'kichik',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'новый',
      translation: 'yangi',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'длинный',
      translation: 'uzun',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'короткий',
      translation: 'qisqa',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'быстрый',
      translation: 'tez',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'медленный',
      translation: 'sekin',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'сильный',
      translation: 'kuchli',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'слабый',
      translation: 'zaif',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'лёгкий',
      translation: 'yengil',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'тяжёлый',
      translation: "og'ir",
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'чистый',
      translation: 'toza',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'грязный',
      translation: 'iflos',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'горячий',
      translation: 'issiq',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'полный',
      translation: "to'la",
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'высокий',
      translation: 'baland',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'низкий',
      translation: 'past',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'широкий',
      translation: 'keng',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'узкий',
      translation: 'tor',
      language: 'ru',
      topic: 'Sifatlar',
      level: 'A1',
    },
    {
      word: 'мужчина',
      translation: 'erkak',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'женщина',
      translation: 'ayol',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'брат',
      translation: 'aka',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'сестра',
      translation: 'opa',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'дедушка',
      translation: 'bobo',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'бабушка',
      translation: 'buvi',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'сын',
      translation: "o'g'il",
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'дочь',
      translation: 'qiz',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'муж',
      translation: 'er',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'жена',
      translation: 'xotin',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'сосед',
      translation: "qo'shni",
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
    {
      word: 'человек',
      translation: 'odam',
      language: 'ru',
      topic: 'Odamlar',
      level: 'A1',
    },
  ],
  A2: [
    {
      word: 'улица',
      translation: "ko'cha",
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'площадь',
      translation: 'maydon',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'парк',
      translation: "bog'",
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'мост',
      translation: "ko'prik",
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'вокзал',
      translation: 'bekat',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'аптека',
      translation: 'dorixona',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'банк',
      translation: 'bank',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'почта',
      translation: 'pochta',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'рынок',
      translation: 'bozor',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'музей',
      translation: 'muzey',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'театр',
      translation: 'teatr',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'ресторан',
      translation: 'restoran',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'библиотека',
      translation: 'kutubxona',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'школа',
      translation: 'maktab',
      language: 'ru',
      topic: 'Shahar',
      level: 'A2',
    },
    {
      word: 'суп',
      translation: "sho'rva",
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'сыр',
      translation: 'pishloq',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'масло',
      translation: "sariyog'",
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'сахар',
      translation: 'shakar',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'фрукты',
      translation: 'meva',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'овощи',
      translation: 'sabzavot',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'картофель',
      translation: 'kartoshka',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'помидор',
      translation: 'pomidor',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'лук',
      translation: 'piyoz',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'морковь',
      translation: 'sabzi',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'яйцо',
      translation: 'tuxum',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'мёд',
      translation: 'asal',
      language: 'ru',
      topic: 'Ovqat 2',
      level: 'A2',
    },
    {
      word: 'вечер',
      translation: 'kechqurun',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'ночь',
      translation: 'tun',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'минута',
      translation: 'daqiqa',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'секунда',
      translation: 'soniya',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'месяц',
      translation: 'oy',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'сегодня',
      translation: 'bugun',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'понедельник',
      translation: 'dushanba',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'вторник',
      translation: 'seshanba',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'среда',
      translation: 'chorshanba',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'пятница',
      translation: 'juma',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'суббота',
      translation: 'shanba',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
    {
      word: 'воскресенье',
      translation: 'yakshanba',
      language: 'ru',
      topic: 'Vaqt 2',
      level: 'A2',
    },
  ],
  B1: [
    {
      word: 'любовь',
      translation: 'muhabbat',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'надежда',
      translation: 'umid',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'гнев',
      translation: "g'azab",
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'гордость',
      translation: "g'urur",
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'стыд',
      translation: 'uyat',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'зависть',
      translation: 'hasad',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'доверие',
      translation: 'ishonch',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'терпение',
      translation: 'sabr',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'смелость',
      translation: 'jasorat',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'мечта',
      translation: 'orzu',
      language: 'ru',
      topic: "His-tuyg'u 2",
      level: 'B1',
    },
    {
      word: 'зарплата',
      translation: 'maosh',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'начальник',
      translation: 'boshliq',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'коллега',
      translation: 'hamkasb',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'проект',
      translation: 'loyiha',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'задача',
      translation: 'vazifa',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'успех',
      translation: 'muvaffaqiyat',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'ошибка',
      translation: 'xato',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'договор',
      translation: 'shartnoma',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'клиент',
      translation: 'mijoz',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'продукт',
      translation: 'mahsulot',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'услуга',
      translation: 'xizmat',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'цель',
      translation: 'maqsad',
      language: 'ru',
      topic: 'Ish 2',
      level: 'B1',
    },
    {
      word: 'наука',
      translation: 'fan',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'история',
      translation: 'tarix',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'математика',
      translation: 'matematika',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'язык',
      translation: 'til',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'слово',
      translation: "so'z",
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'предложение',
      translation: 'gap',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'правило',
      translation: 'qoida',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'пример',
      translation: 'misol',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'страница',
      translation: 'sahifa',
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
    {
      word: 'словарь',
      translation: "lug'at",
      language: 'ru',
      topic: "Ta'lim 2",
      level: 'B1',
    },
  ],
}
