import type { NewCardRecordInput } from '@/core/db'
import type { LevelCode } from '@/core/types'

/**
 * Rus tili to'plami, CEFR darajalari bo'yicha.
 *
 * Tushunchalar ingliz to'plami bilan bir xil: foydalanuvchi tillar
 * o'rtasida almashganda bir xil mavzular ketma-ketligini ko'radi.
 *
 * `normalize.ts` javobda `ё` ni `е` ga aylantiradi, shuning uchun `ё` li
 * so'zlar xavfsiz: foydalanuvchi ikkala shaklda yozsa ham to'g'ri sanaladi.
 * Urg'u belgisi qo'yilmaydi — u yozuvda ishlatilmaydi.
 */
export const RU_DECK: Record<LevelCode, NewCardRecordInput[]> = {
  A1: [
    {
      word: 'привет',
      translation: 'salom',
      language: 'ru',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Привет мой друг',
      sentenceTranslation: "Salom, do'stim",
    },
    {
      word: 'спасибо',
      translation: 'rahmat',
      language: 'ru',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Большое спасибо',
      sentenceTranslation: 'Katta rahmat',
    },
    {
      word: 'до свидания',
      translation: 'xayr',
      language: 'ru',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'До свидания, до встречи',
      sentenceTranslation: "Xayr, ko'rishguncha",
    },
    {
      word: 'пожалуйста',
      translation: 'iltimos',
      language: 'ru',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Пожалуйста, помогите мне',
      sentenceTranslation: 'Iltimos, menga yordam bering',
    },
    {
      word: 'извините',
      translation: 'kechirasiz',
      language: 'ru',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Извините, я опоздал',
      sentenceTranslation: 'Kechirasiz, men kechikdim',
    },
    {
      word: 'да',
      translation: 'ha',
      language: 'ru',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Да, я готов',
      sentenceTranslation: 'Ha, men tayyorman',
    },
    {
      word: 'нет',
      translation: "yo'q",
      language: 'ru',
      topic: 'Salomlashish',
      level: 'A1',
      sentence: 'Нет, спасибо',
      sentenceTranslation: "Yo'q, rahmat",
    },
    {
      word: 'друг',
      translation: "do'st",
      language: 'ru',
      topic: 'Oila',
      level: 'A1',
      sentence: 'Он мой друг',
      sentenceTranslation: "U mening do'stim",
    },
    {
      word: 'дом',
      translation: 'uy',
      language: 'ru',
      topic: 'Oila',
      level: 'A1',
      sentence: 'Это мой дом',
      sentenceTranslation: 'Bu mening uyim',
    },
    {
      word: 'мама',
      translation: 'ona',
      language: 'ru',
      topic: 'Oila',
      level: 'A1',
      sentence: 'Мама дома',
      sentenceTranslation: 'Onam uyda',
    },
    {
      word: 'папа',
      translation: 'ota',
      language: 'ru',
      topic: 'Oila',
      level: 'A1',
      sentence: 'Папа работает здесь',
      sentenceTranslation: 'Otam shu yerda ishlaydi',
    },
    {
      word: 'ребёнок',
      translation: 'bola',
      language: 'ru',
      topic: 'Oila',
      level: 'A1',
      sentence: 'Ребёнок маленький',
      sentenceTranslation: 'Bola kichkina',
    },
    {
      word: 'один',
      translation: 'bir',
      language: 'ru',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'У меня одна книга',
      sentenceTranslation: 'Menda bitta kitob bor',
    },
    {
      word: 'два',
      translation: 'ikki',
      language: 'ru',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Два друга ждут',
      sentenceTranslation: "Ikki do'st kutmoqda",
    },
    {
      word: 'три',
      translation: 'uch',
      language: 'ru',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'У нас три комнаты',
      sentenceTranslation: 'Bizda uchta xona bor',
    },
    {
      word: 'четыре',
      translation: "to'rt",
      language: 'ru',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Четыре человека здесь',
      sentenceTranslation: "To'rt kishi shu yerda",
    },
    {
      word: 'пять',
      translation: 'besh',
      language: 'ru',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Пять минут, пожалуйста',
      sentenceTranslation: 'Besh daqiqa, iltimos',
    },
    {
      word: 'десять',
      translation: "o'n",
      language: 'ru',
      topic: 'Raqamlar',
      level: 'A1',
      sentence: 'Десять студентов здесь',
      sentenceTranslation: "O'n talaba shu yerda",
    },
    {
      word: 'вода',
      translation: 'suv',
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Я пью воду',
      sentenceTranslation: 'Men suv ichaman',
    },
    {
      word: 'хлеб',
      translation: 'non',
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Хлеб свежий',
      sentenceTranslation: 'Non yangi',
    },
    {
      word: 'молоко',
      translation: 'sut',
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Молоко холодное',
      sentenceTranslation: 'Sut sovuq',
    },
    {
      word: 'яблоко',
      translation: 'olma',
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Это яблоко сладкое',
      sentenceTranslation: 'Bu olma shirin',
    },
    {
      word: 'рис',
      translation: 'guruch',
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Мы едим рис сегодня',
      sentenceTranslation: 'Biz bugun guruch yeymiz',
    },
    {
      word: 'мясо',
      translation: "go'sht",
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Мясо готово',
      sentenceTranslation: "Go'sht tayyor",
    },
    {
      word: 'чай',
      translation: 'choy',
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Я люблю зелёный чай',
      sentenceTranslation: "Menga ko'k choy yoqadi",
    },
    {
      word: 'соль',
      translation: 'tuz',
      language: 'ru',
      topic: 'Ovqat',
      level: 'A1',
      sentence: 'Добавьте немного соли',
      sentenceTranslation: "Ozgina tuz qo'shing",
    },
    {
      word: 'красный',
      translation: 'qizil',
      language: 'ru',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'Яблоко красное',
      sentenceTranslation: 'Olma qizil',
    },
    {
      word: 'синий',
      translation: "ko'k",
      language: 'ru',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'Небо синее',
      sentenceTranslation: "Osmon ko'k",
    },
    {
      word: 'зелёный',
      translation: 'yashil',
      language: 'ru',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'Трава зелёная',
      sentenceTranslation: "O't yashil",
    },
    {
      word: 'чёрный',
      translation: 'qora',
      language: 'ru',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'У меня чёрные туфли',
      sentenceTranslation: 'Menda qora tufli bor',
    },
    {
      word: 'белый',
      translation: 'oq',
      language: 'ru',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'Дом белый',
      sentenceTranslation: 'Uy oq',
    },
    {
      word: 'жёлтый',
      translation: 'sariq',
      language: 'ru',
      topic: 'Ranglar',
      level: 'A1',
      sentence: 'Солнце жёлтое',
      sentenceTranslation: 'Quyosh sariq',
    },
    {
      word: 'есть',
      translation: 'yemoq',
      language: 'ru',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Мы едим вместе',
      sentenceTranslation: 'Biz birga yeymiz',
    },
    {
      word: 'пить',
      translation: 'ichmoq',
      language: 'ru',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Я пью холодную воду',
      sentenceTranslation: 'Men sovuq suv ichaman',
    },
    {
      word: 'идти',
      translation: 'bormoq',
      language: 'ru',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Я иду в школу',
      sentenceTranslation: 'Men maktabga boraman',
    },
    {
      word: 'прийти',
      translation: 'kelmoq',
      language: 'ru',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Он должен прийти рано',
      sentenceTranslation: 'U erta kelishi kerak',
    },
    {
      word: 'видеть',
      translation: "ko'rmoq",
      language: 'ru',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Я вижу друга',
      sentenceTranslation: "Men do'stimni ko'raman",
    },
    {
      word: 'спать',
      translation: 'uxlamoq',
      language: 'ru',
      topic: "Kundalik fe'llar",
      level: 'A1',
      sentence: 'Дети спят рано',
      sentenceTranslation: 'Bolalar erta uxlaydi',
    },
    {
      word: 'книга',
      translation: 'kitob',
      language: 'ru',
      topic: 'Maktab',
      level: 'A1',
      sentence: 'Я читаю книгу',
      sentenceTranslation: "Men kitob o'qiyman",
    },
    {
      word: 'утро',
      translation: 'ertalab',
      language: 'ru',
      topic: 'Vaqt',
      level: 'A1',
      sentence: 'Доброе утро',
      sentenceTranslation: 'Xayrli tong',
    },
    {
      word: 'дорога',
      translation: "yo'l",
      language: 'ru',
      topic: 'Sayohat',
      level: 'A1',
      sentence: 'Дорога длинная',
      sentenceTranslation: "Yo'l uzoq",
    },
    {
      word: 'город',
      translation: 'shahar',
      language: 'ru',
      topic: 'Sayohat',
      level: 'A1',
      sentence: 'Город большой',
      sentenceTranslation: 'Shahar katta',
    },
    {
      word: 'кошка',
      translation: 'mushuk',
      language: 'ru',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'Кошка маленькая',
      sentenceTranslation: 'Mushuk kichkina',
    },
    {
      word: 'собака',
      translation: 'it',
      language: 'ru',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'Собака быстро бегает',
      sentenceTranslation: 'It tez yuguradi',
    },
    {
      word: 'птица',
      translation: 'qush',
      language: 'ru',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'Птица поёт',
      sentenceTranslation: 'Qush sayraydi',
    },
    {
      word: 'рыба',
      translation: 'baliq',
      language: 'ru',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'Рыба плавает',
      sentenceTranslation: 'Baliq suzadi',
    },
    {
      word: 'корова',
      translation: 'sigir',
      language: 'ru',
      topic: 'Hayvonlar',
      level: 'A1',
      sentence: 'Корова даёт молоко',
      sentenceTranslation: 'Sigir sut beradi',
    },
    {
      word: 'рука',
      translation: "qo'l",
      language: 'ru',
      topic: 'Tana',
      level: 'A1',
      sentence: 'Я поднял руку',
      sentenceTranslation: "Men qo'limni ko'tardim",
    },
    {
      word: 'глаз',
      translation: "ko'z",
      language: 'ru',
      topic: 'Tana',
      level: 'A1',
      sentence: 'Закрой глаза',
      sentenceTranslation: "Ko'zingizni yuming",
    },
    {
      word: 'голова',
      translation: 'bosh',
      language: 'ru',
      topic: 'Tana',
      level: 'A1',
      sentence: 'У меня болит голова',
      sentenceTranslation: 'Boshim og’riyapti',
    },
    {
      word: 'нога',
      translation: 'oyoq',
      language: 'ru',
      topic: 'Tana',
      level: 'A1',
      sentence: 'Моя нога холодная',
      sentenceTranslation: 'Oyog’im sovuq',
    },
    {
      word: 'ухо',
      translation: 'quloq',
      language: 'ru',
      topic: 'Tana',
      level: 'A1',
      sentence: 'Ухо слышит звук',
      sentenceTranslation: 'Quloq tovushni eshitadi',
    },
  ],

  A2: [
    {
      word: 'аэропорт',
      translation: 'aeroport',
      language: 'ru',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'Аэропорт далеко',
      sentenceTranslation: 'Aeroport uzoqda',
    },
    {
      word: 'билет',
      translation: 'chipta',
      language: 'ru',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'Я купил билет',
      sentenceTranslation: 'Men chipta sotib oldim',
    },
    {
      word: 'поезд',
      translation: 'poyezd',
      language: 'ru',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'Поезд опаздывает',
      sentenceTranslation: 'Poyezd kechikmoqda',
    },
    {
      word: 'отель',
      translation: 'mehmonxona',
      language: 'ru',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'Отель чистый',
      sentenceTranslation: 'Mehmonxona toza',
    },
    {
      word: 'чемодан',
      translation: 'chamadon',
      language: 'ru',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'Мой чемодан тяжёлый',
      sentenceTranslation: "Chamadonim og'ir",
    },
    {
      word: 'карта',
      translation: 'xarita',
      language: 'ru',
      topic: 'Sayohat',
      level: 'A2',
      sentence: 'Посмотрите на карту',
      sentenceTranslation: 'Xaritaga qarang',
    },
    {
      word: 'магазин',
      translation: "do'kon",
      language: 'ru',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'Магазин открыт',
      sentenceTranslation: "Do'kon ochiq",
    },
    {
      word: 'деньги',
      translation: 'pul',
      language: 'ru',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'Мне нужно больше денег',
      sentenceTranslation: "Menga ko'proq pul kerak",
    },
    {
      word: 'цена',
      translation: 'narx',
      language: 'ru',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'Цена высокая',
      sentenceTranslation: 'Narx baland',
    },
    {
      word: 'купить',
      translation: 'sotib olmoq',
      language: 'ru',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'Я хочу купить хлеб',
      sentenceTranslation: 'Men non sotib olmoqchiman',
    },
    {
      word: 'дешёвый',
      translation: 'arzon',
      language: 'ru',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'Эта сумка дешёвая',
      sentenceTranslation: 'Bu sumka arzon',
    },
    {
      word: 'дорогой',
      translation: 'qimmat',
      language: 'ru',
      topic: 'Xarid',
      level: 'A2',
      sentence: 'Эта машина дорогая',
      sentenceTranslation: 'Bu mashina qimmat',
    },
    {
      word: 'работа',
      translation: 'ish',
      language: 'ru',
      topic: 'Ish',
      level: 'A2',
      sentence: 'Моя работа интересная',
      sentenceTranslation: 'Mening ishim qiziqarli',
    },
    {
      word: 'офис',
      translation: 'ofis',
      language: 'ru',
      topic: 'Ish',
      level: 'A2',
      sentence: 'Офис закрыт',
      sentenceTranslation: 'Ofis yopiq',
    },
    {
      word: 'учитель',
      translation: "o'qituvchi",
      language: 'ru',
      topic: 'Ish',
      level: 'A2',
      sentence: 'Наш учитель добрый',
      sentenceTranslation: "O'qituvchimiz mehribon",
    },
    {
      word: 'врач',
      translation: 'shifokor',
      language: 'ru',
      topic: 'Ish',
      level: 'A2',
      sentence: 'Врач занят',
      sentenceTranslation: 'Shifokor band',
    },
    {
      word: 'встреча',
      translation: 'uchrashuv',
      language: 'ru',
      topic: 'Ish',
      level: 'A2',
      sentence: 'Встреча начинается сейчас',
      sentenceTranslation: 'Uchrashuv hozir boshlanadi',
    },
    {
      word: 'компания',
      translation: 'kompaniya',
      language: 'ru',
      topic: 'Ish',
      level: 'A2',
      sentence: 'Компания новая',
      sentenceTranslation: 'Kompaniya yangi',
    },
    {
      word: 'здоровье',
      translation: 'salomatlik',
      language: 'ru',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'Здоровье важно',
      sentenceTranslation: 'Salomatlik muhim',
    },
    {
      word: 'лекарство',
      translation: 'dori',
      language: 'ru',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'Примите это лекарство',
      sentenceTranslation: 'Bu dorini iching',
    },
    {
      word: 'больница',
      translation: 'kasalxona',
      language: 'ru',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'Больница рядом',
      sentenceTranslation: 'Kasalxona yaqin',
    },
    {
      word: 'боль',
      translation: "og'riq",
      language: 'ru',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'Боль прошла',
      sentenceTranslation: "Og'riq o'tdi",
    },
    {
      word: 'усталый',
      translation: 'charchagan',
      language: 'ru',
      topic: "Sog'liq",
      level: 'A2',
      sentence: 'Я очень усталый',
      sentenceTranslation: 'Men juda charchaganman',
    },
    {
      word: 'погода',
      translation: 'ob-havo',
      language: 'ru',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'Погода хорошая',
      sentenceTranslation: 'Ob-havo yaxshi',
    },
    {
      word: 'дождь',
      translation: "yomg'ir",
      language: 'ru',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'Дождь закончился',
      sentenceTranslation: "Yomg'ir to'xtadi",
    },
    {
      word: 'снег',
      translation: 'qor',
      language: 'ru',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'Снег покрыл город',
      sentenceTranslation: 'Qor shaharni qopladi',
    },
    {
      word: 'ветер',
      translation: 'shamol',
      language: 'ru',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'Ветер сильный',
      sentenceTranslation: 'Shamol kuchli',
    },
    {
      word: 'солнце',
      translation: 'quyosh',
      language: 'ru',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'Солнце тёплое',
      sentenceTranslation: 'Quyosh iliq',
    },
    {
      word: 'холодный',
      translation: 'sovuq',
      language: 'ru',
      topic: 'Ob-havo',
      level: 'A2',
      sentence: 'Вода холодная',
      sentenceTranslation: 'Suv sovuq',
    },
    {
      word: 'неделя',
      translation: 'hafta',
      language: 'ru',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'Я работаю каждую неделю',
      sentenceTranslation: 'Men har hafta ishlayman',
    },
    {
      word: 'год',
      translation: 'yil',
      language: 'ru',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'Этот год лучше',
      sentenceTranslation: 'Bu yil yaxshiroq',
    },
    {
      word: 'час',
      translation: 'soat',
      language: 'ru',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'Подождите один час',
      sentenceTranslation: 'Bir soat kuting',
    },
    {
      word: 'день',
      translation: 'kun',
      language: 'ru',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'День был долгий',
      sentenceTranslation: "Kun uzoq bo'ldi",
    },
    {
      word: 'завтра',
      translation: 'ertaga',
      language: 'ru',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'Мы встретимся завтра',
      sentenceTranslation: 'Biz ertaga uchrashamiz',
    },
    {
      word: 'всегда',
      translation: 'doim',
      language: 'ru',
      topic: 'Vaqt',
      level: 'A2',
      sentence: 'Она всегда помогает',
      sentenceTranslation: 'U doim yordam beradi',
    },
    {
      word: 'дверь',
      translation: 'eshik',
      language: 'ru',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'Закрой дверь',
      sentenceTranslation: "Eshikni yoping",
    },
    {
      word: 'окно',
      translation: 'deraza',
      language: 'ru',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'Открой окно',
      sentenceTranslation: 'Derazani oching',
    },
    {
      word: 'стол',
      translation: 'stol',
      language: 'ru',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'Стол чистый',
      sentenceTranslation: 'Stol toza',
    },
    {
      word: 'стул',
      translation: 'stul',
      language: 'ru',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'Сядь на стул',
      sentenceTranslation: "Stulga o'tiring",
    },
    {
      word: 'ключ',
      translation: 'kalit',
      language: 'ru',
      topic: "Uy-ro'zg'or",
      level: 'A2',
      sentence: 'Я потерял ключ',
      sentenceTranslation: "Kalitimni yo'qotdim",
    },
    {
      word: 'рубашка',
      translation: "ko'ylak",
      language: 'ru',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'Эта рубашка новая',
      sentenceTranslation: "Bu ko'ylak yangi",
    },
    {
      word: 'обувь',
      translation: 'poyabzal',
      language: 'ru',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'Моя обувь чёрная',
      sentenceTranslation: 'Poyabzalim qora',
    },
    {
      word: 'шапка',
      translation: 'shapka',
      language: 'ru',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'Он носит шапку',
      sentenceTranslation: 'U shapka kiyadi',
    },
    {
      word: 'пальто',
      translation: 'palto',
      language: 'ru',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'Пальто тёплое',
      sentenceTranslation: 'Palto issiq',
    },
    {
      word: 'платье',
      translation: 'libos',
      language: 'ru',
      topic: 'Kiyim',
      level: 'A2',
      sentence: 'Её платье красное',
      sentenceTranslation: 'Uning libosi qizil',
    },
  ],

  B1: [
    {
      word: 'решение',
      translation: 'qaror',
      language: 'ru',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'Это было трудное решение',
      sentenceTranslation: 'Bu qiyin qaror edi',
    },
    {
      word: 'мнение',
      translation: 'fikr',
      language: 'ru',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'Скажите ваше мнение',
      sentenceTranslation: 'Fikringizni ayting',
    },
    {
      word: 'согласиться',
      translation: "rozi bo'lmoq",
      language: 'ru',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'Я согласен с вами',
      sentenceTranslation: 'Men siz bilan roziman',
    },
    {
      word: 'объяснить',
      translation: 'tushuntirmoq',
      language: 'ru',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'Пожалуйста, объясните правило',
      sentenceTranslation: 'Iltimos, qoidani tushuntiring',
    },
    {
      word: 'предложить',
      translation: 'taklif qilmoq',
      language: 'ru',
      topic: 'Fikr bildirish',
      level: 'B1',
      sentence: 'Я предлагаю другой план',
      sentenceTranslation: 'Men boshqa reja taklif qilaman',
    },
    {
      word: 'счастливый',
      translation: 'baxtli',
      language: 'ru',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'Она сегодня счастливая',
      sentenceTranslation: 'U bugun baxtli',
    },
    {
      word: 'грустный',
      translation: 'xafa',
      language: 'ru',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'Он был грустный',
      sentenceTranslation: 'U xafa edi',
    },
    {
      word: 'страх',
      translation: "qo'rquv",
      language: 'ru',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'Страх останавливает многих',
      sentenceTranslation: "Qo'rquv ko'p odamni to'xtatadi",
    },
    {
      word: 'радость',
      translation: 'quvonch',
      language: 'ru',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'Её радость была настоящей',
      sentenceTranslation: 'Uning quvonchi chin edi',
    },
    {
      word: 'удивление',
      translation: 'hayrat',
      language: 'ru',
      topic: "His-tuyg'u",
      level: 'B1',
      sentence: 'Новость вызвала удивление',
      sentenceTranslation: "Yangilik hayrat uyg'otdi",
    },
    {
      word: 'общество',
      translation: 'jamiyat',
      language: 'ru',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'Общество меняется медленно',
      sentenceTranslation: "Jamiyat sekin o'zgaradi",
    },
    {
      word: 'закон',
      translation: 'qonun',
      language: 'ru',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'Закон ясный',
      sentenceTranslation: 'Qonun aniq',
    },
    {
      word: 'правительство',
      translation: 'hukumat',
      language: 'ru',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'Правительство приняло правила',
      sentenceTranslation: 'Hukumat qoidalar chiqardi',
    },
    {
      word: 'гражданин',
      translation: 'fuqaro',
      language: 'ru',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'У каждого гражданина есть долг',
      sentenceTranslation: 'Har bir fuqaroning burchi bor',
    },
    {
      word: 'свобода',
      translation: 'erkinlik',
      language: 'ru',
      topic: 'Jamiyat',
      level: 'B1',
      sentence: 'Свобода требует ответственности',
      sentenceTranslation: "Erkinlik mas'uliyat talab qiladi",
    },
    {
      word: 'компьютер',
      translation: 'kompyuter',
      language: 'ru',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'Мой компьютер медленный',
      sentenceTranslation: 'Kompyuterim sekin',
    },
    {
      word: 'сеть',
      translation: 'tarmoq',
      language: 'ru',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'Сеть не работает',
      sentenceTranslation: 'Tarmoq ishlamayapti',
    },
    {
      word: 'данные',
      translation: "ma'lumot",
      language: 'ru',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'Мы потеряли данные',
      sentenceTranslation: "Biz ma'lumotni yo'qotdik",
    },
    {
      word: 'экран',
      translation: 'ekran',
      language: 'ru',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'Экран яркий',
      sentenceTranslation: 'Ekran yorqin',
    },
    {
      word: 'устройство',
      translation: 'qurilma',
      language: 'ru',
      topic: 'Texnologiya',
      level: 'B1',
      sentence: 'Это устройство полезное',
      sentenceTranslation: 'Bu qurilma foydali',
    },
    {
      word: 'идея',
      translation: "g'oya",
      language: 'ru',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Это хорошая идея',
      sentenceTranslation: "Bu yaxshi g'oya",
    },
    {
      word: 'причина',
      translation: 'sabab',
      language: 'ru',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Скажите мне причину',
      sentenceTranslation: 'Menga sababni ayting',
    },
    {
      word: 'опыт',
      translation: 'tajriba',
      language: 'ru',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Опыт учит нас',
      sentenceTranslation: "Tajriba bizni o'rgatadi",
    },
    {
      word: 'знание',
      translation: 'bilim',
      language: 'ru',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Знание растёт медленно',
      sentenceTranslation: "Bilim sekin o'sadi",
    },
    {
      word: 'изменение',
      translation: "o'zgarish",
      language: 'ru',
      topic: 'Mavhum tushunchalar',
      level: 'B1',
      sentence: 'Изменение требует времени',
      sentenceTranslation: "O'zgarish vaqt talab qiladi",
    },
    {
      word: 'дерево',
      translation: 'daraxt',
      language: 'ru',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'Дерево высокое',
      sentenceTranslation: 'Daraxt baland',
    },
    {
      word: 'река',
      translation: 'daryo',
      language: 'ru',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'Река глубокая',
      sentenceTranslation: 'Daryo chuqur',
    },
    {
      word: 'гора',
      translation: "tog'",
      language: 'ru',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'Гора высокая',
      sentenceTranslation: "Tog' baland",
    },
    {
      word: 'море',
      translation: 'dengiz',
      language: 'ru',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'Море спокойное',
      sentenceTranslation: 'Dengiz tinch',
    },
    {
      word: 'лес',
      translation: "o'rmon",
      language: 'ru',
      topic: 'Tabiat',
      level: 'B1',
      sentence: 'Лес зелёный',
      sentenceTranslation: "O'rmon yashil",
    },
    {
      word: 'университет',
      translation: 'universitet',
      language: 'ru',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'Она учится в университете',
      sentenceTranslation: 'U universitetda o’qiydi',
    },
    {
      word: 'студент',
      translation: 'talaba',
      language: 'ru',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'Студент прилежный',
      sentenceTranslation: 'Talaba tirishqoq',
    },
    {
      word: 'экзамен',
      translation: 'imtihon',
      language: 'ru',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'Экзамен трудный',
      sentenceTranslation: 'Imtihon qiyin',
    },
    {
      word: 'вопрос',
      translation: 'savol',
      language: 'ru',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'У меня есть вопрос',
      sentenceTranslation: 'Menda savol bor',
    },
    {
      word: 'ответ',
      translation: 'javob',
      language: 'ru',
      topic: "Ta'lim",
      level: 'B1',
      sentence: 'Ваш ответ правильный',
      sentenceTranslation: "Javobingiz to'g'ri",
    },
  ],
}
