/**
 * AVTOMATIK YARATILGAN — qo'lda tahrirlamang.
 * Manba: Tatoeba (tatoeba.org), CC-BY 2.0 FR. scripts/add-sentences.py
 *
 * So'z → o'sha so'z qatnashgan qisqa jumla. "Gap ichida" mashqi
 * shundan bo'sh joyli savol yasaydi. Tarjimasi yo'q — bu mashqqa
 * kerak emas ("jumla qurish" esa shu sababli berilmaydi).
 */
export const EN_SENTENCES: Record<string, string> = {
  'abbey': 'An abbey once stood here.',
  'abilities': 'I have many abilities.',
  'absence': 'He excused his absence.',
  'absent': 'I was absent.',
  'academy': 'Do you go to an academy?',
  'accept': 'I accept you.',
  'acceptance': 'Is Yanni seeking acceptance?',
  'accessories': 'What are accessories?',
  'accessory': "It's a fashion accessory.",
  'accident': 'I had an accident.',
  'accommodation': 'We need accommodation.',
  'achieve': 'Achieve your dreams.',
  'achievement': 'What an achievement!',
  'achievements': 'He played up his achievements.',
  'across': 'I came across one.',
  'act': 'He can act.',
  'actions': 'Actions, not words.',
  'active': 'I was active.',
  'activities': 'I completed the activities.',
  'activity': 'Finish that activity.',
  'actor': "I'm an actor.",
  'actress': "I'm an actress.",
  'actresses': 'You are actresses.',
  'actually': 'I actually cried.',
  'ad': 'Skip the ad.',
  'add': 'Add no more.',
  'adding': 'Thanks for adding me.',
  'address': "Here's my address.",
  'addresses': 'He has two email addresses.',
  'adjective': 'This is an adjective.',
  'adjectives': 'What do adjectives modify?',
  'admire': 'I admire you.',
  'adult': 'Be an adult.',
  'adults': 'Act like adults.',
  'adverb': 'This is an adverb.',
  'adverbs': 'What do adverbs modify?',
  'advertisement': 'I see the advertisement.',
  'advertisements': 'I hate advertisements.',
  'advise': 'Can you advise me?',
  'aeroplanes': 'Aeroplanes are expensive.',
  'affirmative': 'The response is affirmative.',
  'afford': 'I can afford it.',
  'afraid': 'I am afraid.',
  'africa': 'Africa is home.',
  'afternoon': 'Do it this afternoon.',
  'afterwards': 'Where to afterwards?',
  'aged': 'She has aged.',
  'aggressive': 'He is aggressive.',
  'agree': 'No, I agree.',
  'aircraft': 'Do you fly aircraft?',
  'airport': 'Go to the airport.',
  'album': "Here's my album.",
  'alex': 'I love Alex.',
  'alien': "I'm an alien.",
  'aliens': 'It was aliens.',
  'alive': 'I was alive.',
  'alligator': "That's his alligator.",
  'allowed': 'No fun allowed.',
  'alone': 'I am alone.',
  'along': 'I came along.',
  'alright': 'Is he alright?',
  'always': 'I always try.',
  'am': 'So am I!',
  'amazed': 'It amazed me.',
  'amazing': 'It was amazing.',
  'ambulance': 'Call an ambulance.',
  'america': 'America is bad.',
  'among': 'I sat among them.',
  'amy': 'Amy needs rest.',
  'ancient': 'This joke is ancient!',
  'and': 'Yes and no.',
  'angeles': 'How was Los Angeles?',
  'anger': 'You anger us.',
  'angry': 'I am angry.',
  'animal': "I'm an animal.",
  'animals': 'I love animals.',
  'annie': 'Annie ate nervously.',
  'answer': 'Answer me now.',
  'antarctica': 'Welcome to Antarctica.',
  'anthony': 'I am Anthony.',
  'antlers': 'Moose have antlers.',
  'antwerp': 'Antwerp is a city in Belgium.',
  'anxious': 'I was anxious.',
  'anxiously': 'I waited anxiously.',
  'any': 'At any cost!',
  'anyone': 'Is anyone in?',
  'anywhere': 'I sleep anywhere.',
  'appear': 'He does appear.',
  'appearance': "Appearance isn't all.",
  'appeared': 'He appeared busy.',
  'apple': 'Buy an apple.',
  'apples': 'I ate apples.',
  'appointments': 'Cancel all my appointments.',
  'april': "It's now April.",
  'aquarium': 'Buy me an aquarium.',
  'arc': 'I love his character arc.',
  'are': 'We are OK.',
  'area': 'I know the area.',
  'areas': 'Ziri hates rest areas.',
  'argument': 'An argument began.',
  'arm': 'My arm hurts.',
  'armchair': 'This is an armchair.',
  'armchairs': 'My father fixes broken armchairs.',
  'arrangements': "I'll make the arrangements.",
  'arrivals': 'Where is the arrivals hall?',
  'arrive': 'I will arrive.',
  'arrived': 'A car arrived.',
  'arrives': 'He arrives today.',
  'art': 'I like art.',
  'article': 'Read the article.',
  'articles': 'I like your articles.',
  'artist': "I'm an artist.",
  'asking': 'Who is asking?',
  'asks': 'He asks after you.',
  'asleep': 'He is asleep.',
  'assessment': 'Was that a fair assessment?',
  'astronaut': "He's an astronaut.",
  'astronauts': 'Astronauts wear spacesuits.',
  'ate': 'I ate it.',
  'athens': 'I live in Athens.',
  'atlantic': 'They crossed the Atlantic.',
  'atmosphere': 'What an atmosphere!',
  'attic': "I'm in the attic.",
  'attract': 'Flowers attract bees.',
  'attractive': 'I am attractive.',
  'audition': 'I had an audition.',
  'august': "It's now August.",
  'aunt': 'I am Aunt Wang.',
  'australia': 'I love Australia.',
  'author': "He's an author.",
  'autumn': 'It is autumn.',
  'avenue': 'They live on Third Avenue.',
  'babies': 'All babies cry.',
  'baby': "I'm a baby.",
  'bacon': 'I like bacon.',
  'bad': 'Is it bad?',
  'badly': 'I fight badly.',
  'bag': 'Get a bag.',
  'baker': "I'm a baker.",
  "baker's": "The baker's is open.",
  'balcony': "I'm on the balcony.",
  'ball': 'Get a ball.',
  'ballerina': "She's a ballerina.",
  'ballet': 'He does ballet.',
  'balloon': 'My balloon popped!',
  'balloons': 'I have balloons.',
  'balls': 'She has balls.',
  'ban': 'Ban this fag.',
  'banana': 'Eat a banana!',
  'bananas': 'I eat bananas.',
  'band': "We're a band.",
  'banker': "I'm a banker.",
  'banks': 'Yanni robs banks.',
  'barcelona': 'We went to Barcelona.',
  'bargain': "It's a bargain.",
  'barman': 'Ziri is a barman.',
  'base': 'I stole a base.',
  'basketball': 'I love basketball.',
  'bassoon': 'I play the bassoon.',
  'bath': 'Take a bath.',
  'bathroom': 'I need a bathroom.',
  'battle': 'Time to battle!',
  'bazaar': "Let's stroll around the bazaar!",
  'be': 'So be it.',
  'beach': 'Go to the beach.',
  'beaches': 'I like crowded beaches.',
  'beak': 'Shut your beak!',
  'beard': 'He has a beard.',
  'beat': 'I beat you.',
  'beautiful': 'I am beautiful.',
  'beautifully': 'It went beautifully.',
  'beauty': 'What a beauty!',
  'became': 'I became ill.',
  'because': 'Because of what?',
  'bed': 'Go to bed!',
  'bedroom': 'It is my bedroom.',
  'bedrooms': 'Sami had six bedrooms.',
  'beds': 'Make the beds.',
  'beef': 'I love beef.',
  'beep': "I'll beep him.",
  'beer': 'Get a beer.',
  'bees': 'Who eats bees?',
  'before': 'We met before.',
  'began': 'I began to cry.',
  'begin': 'Can I begin?',
  'behind': 'Get behind me.',
  'belgium': 'I live in Belgium.',
  'belief': "It's beyond belief.",
  'believe': 'I believe it.',
  'belongs': 'He belongs here.',
  'bench': 'Sit on the bench.',
  'benches': 'These benches are mine.',
  'better': 'I am better.',
  'between': "I'm between jobs.",
  'bicycle': "It's my bicycle.",
  'bicycles': 'These are bicycles.',
  'big': 'Is it big?',
  'bigger': 'He got bigger.',
  'biography': "I'm reading a biography.",
  'biologist': "I'm a biologist.",
  'biology': 'What is biology?',
  'bird': "I'm a bird!",
  'birds': 'I love birds.',
  'birthday': "It's my birthday.",
  'birthplace': 'Do you know his birthplace?',
  'biscuit': 'Have a biscuit.',
  'bit': 'I got bit.',
  'black': 'Is it black?',
  'blind': 'I am blind.',
  'blouse': 'I wash the blouse.',
  'blow': 'Blow me down!',
  'blue': 'Is it blue?',
  'board': 'Go on board.',
  'boarding': "I'm boarding this one.",
  'boat': 'Get a boat.',
  'boats': 'I sell boats.',
  'boil': 'Boil an egg.',
  'boiling': 'Jane was boiling.',
  'bold': 'Bold as brass.',
  'bonnet': 'Open the bonnet.',
  'book': 'Get a book.',
  'bookcase': 'I made a bookcase.',
  'booked': 'I booked one.',
  'books': 'I read books.',
  'boots': 'I need boots.',
  'bore': 'What a bore.',
  'bored': 'I am bored.',
  'boring': 'I am boring.',
  'born': 'Hope was born.',
  'borrow': 'I borrow money.',
  'boss': 'I am a boss.',
  'bossy': 'He was bossy.',
  'bought': 'I bought it.',
  'bouquet': 'Smell the bouquet.',
  'bowl': 'Get a bowl.',
  'box': 'Get a box.',
  'boxes': 'I need boxes.',
  'boy': "I'm a boy.",
  'boys': 'We are boys.',
  'brackets': 'Open the brackets in the equation.',
  'brave': 'He is brave.',
  'bravely': 'They fought bravely.',
  'bravery': 'I admire your bravery.',
  'brazil': "I'm from Brazil.",
  'brazilians': "We're all Brazilians.",
  'bread': 'I eat bread.',
  'break': 'Break a leg.',
  'break-in': 'Ziri reported a break-in.',
  'breakfast': 'I had breakfast.',
  'breath': 'Take a breath.',
  'breathe': "I can't breathe.",
  'bridge': 'He plays bridge.',
  'bright': 'He was bright.',
  'bring': 'Bring it on!',
  'britain': 'London is in Britain.',
  'brochure': 'Take this brochure.',
  'broke': 'I broke it.',
  'broken': 'Is it broken?',
  'brother': "I'm a brother.",
  'brothers': 'I have brothers.',
  'brown': 'Which is brown?',
  'browns': 'Sue may meet the Browns.',
  'brush': 'Brush your hair.',
  'brushes': 'Clean those brushes.',
  'bubbles': 'He blew soap bubbles.',
  'build': 'I build robots.',
  'building': 'That gray building?',
  'buildings': 'I love old buildings.',
  'built': 'I built it.',
  'buried': 'I buried it.',
  'burn': 'It will burn.',
  'burst': 'The ballon burst.',
  'bury': "We'll bury it.",
  'bus': 'Get a bus.',
  'buses': 'Do buses go here?',
  'busiest': 'Monday is my busiest day.',
  'business': 'Business is slow.',
  'businessman': "I'm a businessman.",
  'busy': 'I am busy.',
  'butcher': "He's a butcher.",
  "butcher's": "Let's have a butcher's.",
  'butter': 'I buy butter.',
  'butterflies': 'I like butterflies.',
  'butterfly': 'Oh, a butterfly!',
  'buy': 'Buy us it.',
  'buying': 'Are you buying?',
  'cabinet': 'The cabinet shook.',
  'cairo': 'I live in Cairo.',
  'cake': 'Buy a cake.',
  'cakes': 'I sell cakes.',
  'call': 'Call a cab!',
  'called': 'I called it!',
  'calm': 'I am calm.',
  'calmly': 'He sat calmly.',
  'cam': 'I have a dashboard cam.',
  'came': 'I came in.',
  'camel': 'He rode a camel.',
  'camera': 'Get the camera.',
  'camp': 'I camp often.',
  'camping': 'I love camping.',
  'can': 'I can go.',
  'canada': "I'm from Canada.",
  'canadian': 'He is Canadian.',
  'canal': 'I got a root canal.',
  'canes': 'We need our canes.',
  'cannot': 'I cannot say.',
  'canoe': 'I came to canoe.',
  'canoes': 'Canoes can be rented locally.',
  'cap': 'Get a cap.',
  'capital': 'We need capital.',
  'car': 'Get a car.',
  'cardinal': 'I want to become a cardinal.',
  'cards': 'Deal the cards.',
  'care': 'I do care.',
  'cared': 'No one cared.',
  'career': 'Fuck your career.',
  'careful': 'I am careful.',
  'carefully': 'Do it carefully.',
  'carol': 'Carol has a headache.',
  'carpet': 'This is a carpet.',
  'carpets': 'I sell carpets.',
  'carrot': 'Carrot or banana?',
  'carry': "I'll carry it.",
  'cars': 'I sell cars.',
  'cart': 'Get a cart.',
  'carton': 'Buy a carton of milk.',
  'cassettes': 'I bought several cassettes of the popular singers.',
  'castle': 'I see a castle.',
  'cat': "I'm a cat.",
  'catch': 'Catch a bus.',
  'cathedral': 'This is a cathedral.',
  'catherine': 'Catherine, or Cath for short.',
  'cats': 'I like cats.',
  'cave': 'This is a cave.',
  'celebrate': 'We must celebrate.',
  'celebration': "It's a celebration.",
  'celebrity': 'He is a celebrity.',
  'central': 'Where is Central Park?',
  'centre': 'They are in the centre.',
  'certain': 'I was certain.',
  'certainly': 'We certainly are.',
  'chair': 'Get a chair.',
  'chairs': 'Do chairs exist?',
  'chalet': 'We stayed in a chalet.',
  'chance': 'Not a chance!',
  'change': 'I can change.',
  'character': 'What a character.',
  'chart': "What's this chart?",
  'chase': "I won't chase.",
  'cheap': 'Is it cheap?',
  'cheaper': 'What is cheaper?',
  'cheapest': 'Which is the cheapest?',
  'checked': 'I checked one.',
  'cheek': 'What a cheek!',
  'cheeks': 'My cheeks burn.',
  'cheese': 'I eat cheese.',
  'cheetah': 'She runs like a cheetah.',
  'chef': "I'm a chef.",
  'chemist': "I'm a chemist.",
  "chemist's": "I work in a chemist's.",
  'chemistry': 'I hate chemistry.',
  'cherry': 'The cherry is red.',
  'chest': 'Open the chest.',
  'chew': 'I chew gum.',
  'chiefs': 'The Chiefs won the Super Bowl.',
  'child': "I'm a child.",
  'children': 'I want children.',
  'chilly': 'It was chilly.',
  'chimpanzee': "The chimpanzee is man's closest living relative.",
  'chimpanzees': 'Can chimpanzees swim?',
  'chin': 'My chin hurts.',
  'chinese': 'I am Chinese.',
  'chips': 'I eat chips.',
  'chocolate': 'I eat chocolate.',
  'christmas': 'I love Christmas.',
  'church': "I'm at church.",
  'churches': "I don't feel well in churches.",
  'cig': 'Can I bum a cig?',
  'cindy': 'Jimmy played footsies with Cindy.',
  'cinema': 'I love cinema.',
  'cities': 'I like cities.',
  'citizen': "I'm a citizen.",
  'city': 'I love my city.',
  'classic': "It's a classic.",
  'classroom': 'This is a classroom.',
  'claw': "Don't let him claw you.",
  'claws': 'He is hiding his claws.',
  'clean': 'Clean it up.',
  'cleaned': 'I cleaned one.',
  'cleaner': 'Ziri is a cleaner.',
  'cleaning': 'I was cleaning.',
  'clerk': 'Are you a clerk?',
  'clever': 'He is clever.',
  'cleverer': 'He is cleverer than I.',
  'cliff': 'Go jump off a cliff.',
  'cliffs': 'Stay away from cliffs.',
  'climate': 'So, what is climate?',
  'climb': 'I can climb.',
  'climber': "He's a climber.",
  'climbing': 'I like climbing.',
  'clips': 'Do we have paper clips?',
  'close': 'I was close.',
  'closer': 'I got closer.',
  'closest': "What's in this closest?",
  'clothes': 'I like clothes.',
  'cloud': 'On cloud seven.',
  'clouds': 'There are clouds.',
  'cloudy': 'Is it cloudy?',
  'club': 'Join the club!',
  'coach': "I'm a coach.",
  'coast': 'The coast is clear.',
  'coat': 'Get a coat.',
  'coconut': "That's a coconut.",
  'coffee': 'I had coffee.',
  'coke': 'I feel Coke.',
  'cold': 'I am cold.',
  'collect': 'I collect them.',
  'collection': 'What a collection!',
  'college': 'I miss college.',
  'collie': 'We keep a collie as a pet.',
  'colosseum': 'Gladiators fought in the Colosseum.',
  'colour': 'Red is a colour.',
  'colourful': 'Their flag was colourful.',
  'come': 'Do come in!',
  'comfort': "That's a comfort.",
  'comfortable': 'I was comfortable.',
  'comments': 'I made comments.',
  'communication': 'What is communication?',
  'company': 'I have company.',
  'comparative': 'My major is comparative religion.',
  'comparisons': 'Comparisons are difficult.',
  'completed': 'I completed one.',
  'complexion': 'She has a fair complexion.',
  'compose': 'I compose songs.',
  'composer': 'He is a composer.',
  'computer': "It's a computer.",
  'computers': 'I use computers.',
  'concert': 'Enjoy the concert.',
  'concerto': 'Can you write a concerto?',
  'conclude': "He didn't conclude his job.",
  'cons': 'What are the pros and cons?',
  'consonant': 'What is your favorite consonant?',
  'consonants': 'Midori sometimes drops consonants.',
  'continue': 'Can I continue?',
  'continued': 'To be continued.',
  'continuous': 'I have a continuous pain here.',
  'convenient': 'It was convenient.',
  'cook': 'I can cook.',
  'cooked': 'I cooked it.',
  'cooker': 'I have a rice cooker.',
  'cooking': 'I love cooking.',
  'cooks': 'He cooks well.',
  'cool': 'Am I cool?',
  'copy': 'Do you copy?',
  'corner': "I'm in the corner.",
  'correctly': 'I did it correctly.',
  'cost': 'At any cost!',
  'costs': 'It costs a lot.',
  'costumes': 'Do you like costumes?',
  'cosy': 'You look cosy.',
  'cottage': 'We live in a cottage.',
  'cotton': 'This is cotton.',
  'cough': 'I cough a lot.',
  "couldn't": "I couldn't go.",
  'count': 'Count me in.',
  'countable': "It's a countable noun.",
  'countries': 'All countries are fake.',
  'country': 'What a country!',
  'countryside': "I'm in the countryside.",
  'course': 'Of course not!',
  'cousin': "He's my cousin.",
  'cow': "It's a cow.",
  'cows': 'Cows give milk.',
  'coy': "Don't be coy.",
  'crash': 'We could crash.',
  'cream': "It's ice cream.",
  'crisps': 'I ate some crisps.',
  'crocodile': "That's a crocodile.",
  'crocodiles': 'She studies crocodiles.',
  'cross': 'I see a cross.',
  'crossing': "I'm crossing the river.",
  'crowd': 'What a crowd!',
  'crowded': 'It was crowded.',
  'cry': 'Can I cry?',
  'cucumber': 'I eat cucumber.',
  'cultural': "It's a cultural thing.",
  'culture': 'What is culture?',
  'cup': 'Get a cup.',
  'cupboard': 'The cupboard is full.',
  'cupboards': 'Our cupboards are empty.',
  'cups': 'We need three cups.',
  'curie': 'She is another Madame Curie.',
  'curiosity': 'He is all curiosity.',
  'curious': 'I am curious.',
  'curly': 'My hair is curly.',
  'curtains': 'Open the curtains.',
  'cushion': 'She hugged a cushion.',
  'cushions': 'I like well-padded cushions.',
  'cuss': "I don't cuss.",
  'customer': "I'm a customer.",
  'customers': 'We lost customers.',
  'cut': 'I got cut.',
  'cycle': 'I can cycle.',
  'cyclist': "I'm a cyclist.",
  'dad': "I'm a dad.",
  'daily': 'I cook daily.',
  'dance': 'I can dance.',
  'dancer': "I'm a dancer.",
  'dancers': 'We are dancers.',
  'dances': 'He also dances.',
  'dancing': 'I am dancing.',
  'danger': "I'm in danger.",
  'dangerous': 'Is it dangerous?',
  'danube': 'The River Danube rises.',
  'dark': 'It was dark.',
  'data': 'I saw the data.',
  'date': "It's a date.",
  'dates': 'I like dates.',
  'daughter': 'Call my daughter.',
  'davis': 'Mr Davis looks very tired.',
  'day': 'What a day!',
  'deaf': 'I am deaf.',
  'dear': "You're a dear.",
  'december': 'I love December.',
  'decide': 'Let me decide.',
  'decided': 'I have decided.',
  'decision': 'Make a decision.',
  'decisions': 'I make the decisions.',
  'decorate': "I didn't decorate it.",
  'decorated': 'I decorated it.',
  'deep': 'How deep is it?',
  'deer': 'Is it a deer?',
  'delhi': 'I live in Delhi.',
  'delicious': 'It is delicious.',
  'deliver': 'Do you deliver?',
  'dentist': "I'm a dentist.",
  'dentists': 'Mennad hates dentists.',
  'depart': 'I will depart soon.',
  'department': "That's your department.",
  'departures': 'Where is the departures hall?',
  'describe': 'Describe it to me.',
  'describing': 'Who are you describing?',
  'description': 'Check the description.',
  'descriptions': 'Yuri read the descriptions of the spells.',
  'desert': 'I do not desert.',
  'deserve': 'I deserve it.',
  'design': "It's a design flaw.",
  'designer': "I'm a designer.",
  'desk': 'I need a desk.',
  'desperate': 'I was desperate.',
  'desperately': "I'm desperately alone.",
  'destination': "What's our destination?",
  'destroy': "I'll destroy it.",
  'destruction': 'Why this destruction?',
  'develop': 'How did that develop?',
  'development': 'This is a huge development.',
  'device': 'I love this device.',
  'dickens': 'What the dickens?',
  'did': 'I did it.',
  'die': 'Do or die.',
  'died': 'No one died.',
  'diet': "I'm on a diet.",
  'difference': 'Difference is good.',
  'different': "I'm no different.",
  'difficult': 'Is it difficult?',
  'dig': 'Dig them out.',
  'dike': "Let's cut the dike.",
  'dine': 'I dine at seven.',
  'diner': 'Let us have diner.',
  'dining-room': 'Sami sat at the dining-room table.',
  'dinner': 'I had dinner.',
  'direct': 'Is it direct?',
  'direction': 'I changed direction.',
  'directions': 'We need directions.',
  'director': "I'm a director.",
  'dirt': 'Hit the dirt.',
  'dirty': 'Is it dirty?',
  'disappear': 'I want to disappear.',
  'disappointed': 'I am disappointed.',
  'disco': "Disco can't die.",
  'discover': 'Discover the world!',
  'discovered': 'I discovered one.',
  'discovery': 'What a discovery!',
  'discussion': 'End of discussion.',
  'disgusting': 'It was disgusting.',
  'dish': 'Is the dish hot?',
  'dishes': 'Do the dishes.',
  'dishwasher': 'I have a dishwasher.',
  'district': 'I know this district.',
  'districts': 'There are thirty districts in Izmir.',
  'dive': "Let's dive in.",
  'diver': 'Ziri is a diver.',
  'divorce': 'I want a divorce.',
  'divorced': 'I am divorced.',
  'do': 'So do I.',
  'doctor': "I'm a doctor.",
  'doctors': 'We are doctors.',
  'does': 'He does it.',
  'dog': "I'm a dog.",
  'dogs': 'I like dogs.',
  'doll': "It's a doll.",
  'dolphin': "What's a dolphin?",
  'dolphins': 'We saw dolphins.',
  "don'ts": "Here's a list of do's and don'ts.",
  'donkey': 'My donkey died.',
  'donkeys': 'Donkeys are so cute!',
  'door': 'Open a door.',
  'doorbell': 'The doorbell rang.',
  'dos': 'This program cannot be run in DOS mode.',
  'double': 'I see double.',
  'double-decker': 'A double-decker bus overtook us.',
  'doug': 'Doug, dab again and pay.',
  'down': 'I sat down.',
  'downstairs': 'I ran downstairs.',
  'drawing': 'He is drawing.',
  'drawings': 'I love your drawings.',
  'dream': 'Let me dream.',
  'dress': "That's my dress.",
  'dressed': 'I dressed up.',
  'dresses': 'He dresses well.',
  'dressing': 'Pass the dressing.',
  'drier': 'Algeria is drier than Spain.',
  'driest': 'July is the driest month of the year.',
  'drink': 'I drink tea.',
  'drinking': 'I am drinking.',
  'drinks': 'He drinks beer.',
  'drive': 'I can drive.',
  'driven': 'He is driven.',
  'driver': "He's a driver.",
  'drives': 'He drives now.',
  'driving': 'I am driving.',
  'drop': 'Just a drop.',
  'drove': 'I drove by.',
  'drown': "He didn't drown.",
  'drum': 'This is a drum.',
  'drummer': "I'm a drummer.",
  'drunk': 'I am drunk.',
  'dry': 'Let it dry.',
  'dryer': 'Do you have a hair dryer?',
  'duck': 'I am a duck.',
  'duckling': 'The duckling is ugly.',
  'dunkirk': 'The British Army was stranded at Dunkirk.',
  'during': 'I work during the day.',
  'each': 'Each in turn.',
  'eagles': "Eagles don't hunt flies.",
  'ear': 'I’m a good ear.',
  'earl': 'Do you like Earl Grey tea?',
  'early': 'Am I early?',
  'earn': 'I earn money.',
  'ears': 'He has ears.',
  'earthquake': 'I am an earthquake.',
  'eases': 'Love eases burdens.',
  'easier': 'Which is easier?',
  'easily': 'I cry easily.',
  'east': "He's going east.",
  'eastern': 'Japan is in eastern Asia.',
  'easy': 'It was easy.',
  'eat': 'I eat it.',
  'eaten': 'Has he eaten?',
  'eating': 'I am eating.',
  'eck': "Flippin' 'eck, the loo's blocked.",
  'edinburgh': 'Have fun in Edinburgh.',
  'edit': 'Click to edit!',
  'editor': "I'm the editor.",
  'educate': 'Please educate me.',
  'education': 'It lacks education.',
  'egg': 'Boil an egg.',
  'egypt': "I'm in Egypt.",
  'egyptian': 'I am Egyptian.',
  'eiffel': 'How old is the Eiffel Tower?',
  'eight': 'He is eight.',
  'eighteen': "I'm over eighteen.",
  'eighth': "I'm an eighth grader.",
  'eighty': 'He is eighty years old.',
  'elderly': 'I respect the elderly.',
  'electricity': 'We have no electricity.',
  'elephant': 'I have an elephant.',
  'elephants': 'I like elephants.',
  'eleven': "It's eleven now.",
  'embarrassed': 'I am embarrassed.',
  'emergencies': 'Are you prepared for emergencies?',
  'empty': 'It was empty.',
  'ending': "I'm ending it.",
  'ends': 'It never ends.',
  'engine': 'Cut the engine.',
  'engineer': "I'm an engineer.",
  'england': "I'm from England.",
  'english': 'I am English.',
  'enjoy': 'I enjoy it.',
  'enjoyable': 'It was enjoyable.',
  'enjoyed': 'I enjoyed it.',
  'enjoying': "I'm enjoying it.",
  'enough': 'I am enough.',
  'enterprise': 'He is a man with enterprise.',
  'entertain': 'I love to entertain.',
  'entertainer': 'Are you an entertainer?',
  'entertainment': 'Sami was into entertainment.',
  'entrance': "Where's the entrance?",
  'envelope': 'I need an envelope.',
  'environment': 'Protect the environment!',
  'environmental': "It's an environmental disaster.",
  'episode': 'I saw that episode.',
  'episodes': "I've seen a few episodes.",
  'equipment': 'This is my equipment.',
  'erase': 'We can erase it.',
  'erie': 'Cleveland is on Lake Erie.',
  'err': 'I often err.',
  'eucalyptus': 'Koalas eat eucalyptus leaves.',
  'europe': "It's in Europe.",
  'evening': 'It was evening.',
  'evenings': 'I miss those evenings.',
  'event': 'I won the event.',
  'events': 'He loves sports events.',
  'ever': 'Did you ever?',
  'everyone': 'Is everyone OK?',
  'everything': 'Everything is OK.',
  'exactly': 'Exactly, my dear.',
  'exam': 'I did my exam!',
  'excellent': 'This is excellent.',
  'excited': 'I excited her.',
  'exciting': 'Is it exciting?',
  'excuse': "It's an excuse.",
  'exercise': 'I often exercise.',
  'exercising': 'I am exercising.',
  'exit': 'Enter or exit.',
  'expand': 'We want to expand.',
  'expedition': 'He was going on an expedition.',
  'expense': 'Hang the expense.',
  'expensive': 'Is it expensive?',
  'experience': 'I lack experience.',
  'explain': 'I can explain.',
  'explanation': 'Add an explanation.',
  'express': 'Is this an express?',
  'expressions': 'Both expressions are correct.',
  'extra': "I'll pay extra.",
  'extremely': "I'm extremely fat.",
  'eye': 'My eye hurts.',
  'eyes': 'I have eyes.',
  'fabulous': 'He is fabulous.',
  'face': 'I lost face.',
  'faces': "Don't make faces.",
  'factory': 'I work in a factory.',
  'fair': 'I was fair.',
  'fall': 'I love fall.',
  'falls': 'The tree falls.',
  'false': 'True or false?',
  'fame': 'I aspire to fame.',
  'family': 'We are family.',
  'famous': 'I am famous.',
  'fan': "I'm a fan.",
  'fans': 'The fans cheered.',
  'fantastic': 'It is fantastic.',
  'far': 'Is it far?',
  'farm': 'He has a farm.',
  'farmer': "I'm a farmer.",
  'farmers': 'We were farmers.',
  'farmhouse': 'I love farmhouse cheese.',
  'fascinate': 'Bugs fascinate me.',
  'fashion': "It's the fashion!",
  'fashionable': 'He is fashionable.',
  'fast': 'I eat fast.',
  'faster': 'I was faster.',
  'fastest': "I'm the fastest.",
  'fat': 'Am I fat?',
  'father': "I'm a father.",
  'favourite': 'This is my favourite.',
  'fear': 'I fear so.',
  'feather': 'He has a huge feather.',
  'feathers': 'The bird has feathers.',
  'features': 'She has fine features.',
  'fee': 'Is there a fee?',
  'feed': 'Feed the dog.',
  'feel': 'I feel OK.',
  'feelings': 'No hard feelings!',
  'feels': 'He feels fat.',
  'feet': 'My feet hurt.',
  'fell': 'I fell ill.',
  'felt': 'I felt it.',
  'female': 'The bear is female.',
  'festival': 'Happy Moon Festival!',
  'festivals': 'Do you attend music festivals?',
  'field': 'Go in the field.',
  'fields': 'No fields changed.',
  'fifteen': "She's only fifteen.",
  'fifth': 'Is it fifth period?',
  'fifty': 'I am fifty.',
  'file': 'Select a file.',
  'film': 'Pick a film.',
  'films': 'I like films.',
  'final': 'Death is final.',
  'finally': 'I finally won.',
  'find': 'Find a job.',
  'finger': 'I cut my finger.',
  'fingers': 'My fingers hurt.',
  'finish': 'Can I finish?',
  'finishes': 'The lesson finishes at noon.',
  'fins': 'Fish have gills and fins.',
  'fire': 'Fire it up!',
  'firecrackers': 'Lorenzo lit up the firecrackers.',
  'firefighter': "I'm a firefighter.",
  'firemen': 'How many firemen were there?',
  'fireplace': 'They sat by the fireplace.',
  'fires': 'I fight forest fires.',
  'firework': 'We went to a firework festival.',
  'first': 'Am I first?',
  'fish': 'I eat fish.',
  'fishing': 'I go fishing.',
  'fit': 'I feel fit.',
  'five': 'Give me five!',
  'fix': 'You fix it.',
  'fixed': 'I fixed it.',
  'flame': 'The flame went out.',
  'flat': 'It was flat.',
  'flats': 'I live in a block of flats.',
  'flea': "It's a flea.",
  'flies': 'I eat flies.',
  'flock': 'I saw a flock of sheep.',
  'flood': 'We had a flood.',
  'floor': 'Wax the floor.',
  'flour': 'I need flour.',
  'flow': 'Let it flow.',
  'flower': 'Pick the flower.',
  'flowers': 'I buy flowers.',
  'flu': 'I got the flu.',
  'flute': 'I have a flute.',
  'flying': 'I am flying.',
  'fog': 'Is that fog?',
  'foggy': 'Is it foggy?',
  'follow': 'I follow him!',
  'followed': 'I followed it.',
  'fonder': 'Absence makes the heart grow fonder.',
  'food': 'I am food.',
  'foot': 'Go on foot.',
  'football': 'I like football.',
  'footprint': "There's a footprint.",
  'forbade': 'Ziri forbade it.',
  'forbidden': 'Dogs are forbidden.',
  'forest': 'I was a forest.',
  'forests': 'Forests store water.',
  'forever': 'Forever is now.',
  'forgave': 'He forgave me.',
  'forget': 'Do not forget!',
  'fork': 'Get a fork.',
  'forty': 'She was forty.',
  'found': 'I found it!',
  'four': 'At least four!',
  'fourteen': 'Ziri was fourteen.',
  'fourth': 'Ziri is fourth.',
  'fox': "It's a fox.",
  'foxes': 'Foxes eat hens.',
  'france': 'I love France.',
  'freedom': 'I like freedom.',
  'freezing': 'I am freezing.',
  'french': 'I am French.',
  'frequency': 'We can finetune the frequency.',
  'fresh': 'Eat fresh food.',
  'friday': 'Is it Friday?',
  'friend': "I'm a friend.",
  'friendlier': 'I used to be much friendlier.',
  'friendliest': "You're one of the friendliest people I know.",
  'friendly': 'I am friendly.',
  'frightened': 'I was frightened.',
  'frightening': 'It was frightening.',
  'front': "He's in front.",
  'frozen': 'He stood frozen.',
  'fruit': 'I eat fruit.',
  'fry': 'Fry me an egg.',
  'frying-pan': 'My grandmother has an iron frying-pan.',
  'full': 'I am full.',
  'fun': 'Am I fun?',
  'funny': 'Am I funny?',
  'fur': 'This is fur.',
  'furniture': 'I make furniture.',
  'future': 'To your future!',
  'garage': 'Go to the garage.',
  'garden': 'Do you garden?',
  'garlic': 'I love garlic.',
  'gary': 'He tried to scare Gary.',
  'gate': 'Lock the gate.',
  'geese': 'I feed geese.',
  'generosity': 'I love your generosity.',
  'generous': 'He was generous.',
  'germany': 'Go to Germany.',
  'gets': 'He gets it.',
  'getting': "I'm getting by.",
  'gift': "It's a gift.",
  'giraffe': 'I see a giraffe.',
  'giraffes': 'I love giraffes.',
  'girl': "I'm a girl.",
  'girls': 'I like girls.',
  'give': 'I give up.',
  'giving': "I'm giving up.",
  'glass': 'I cut glass.',
  'glasses': 'I wear glasses.',
  'gloves': 'I wore gloves.',
  'go': 'Go on in.',
  'goes': 'So it goes.',
  'goldfish': 'I hate goldfish.',
  'gone': 'I am gone.',
  'good': 'I am good.',
  'good-looking': 'He was good-looking.',
  'goodbye': 'Goodbye to you.',
  'goose': 'I have a goose.',
  'gorgeous': 'You are gorgeous.',
  'gorillas': 'They are gorillas.',
  'gosling': 'A gosling is a baby goose.',
  'got': 'I got it.',
  'govern': 'They govern themselves.',
  'government': 'The government fell.',
  'graduate': "He's a graduate.",
  'grammar': 'I hate grammar.',
  'gramophone': 'I just bought an antique gramophone.',
  'grandchild': 'My grandchild is eight.',
  'grandchildren': 'I want grandchildren.',
  'granddaughter': 'I know my granddaughter.',
  'grandfather': "I'm a grandfather.",
  'grandmother': "I'm a grandmother.",
  'grandparent': 'The parent of a parent is a grandparent.',
  'grandparents': 'I had grandparents.',
  'grandson': 'He has a grandson.',
  'grapes': 'I like grapes.',
  'grease': 'Grease the pan.',
  'greasy': 'My hair is greasy.',
  'great-grandfather': 'He is my great-grandfather.',
  'greece': "I'm from Greece.",
  'greek': 'I am Greek.',
  'green': 'It is green.',
  'greengrocer': 'This is the cheapest greengrocer in town.',
  "greengrocer's": "I met him outside the greengrocer's.",
  'greenish': 'Seawater is greenish.',
  'greetings': 'Greetings to you.',
  'grey': 'I turned grey.',
  'greyer': 'His moustache is greyer than his beard.',
  'grill': 'The grill is hot.',
  'groups': 'Study in groups.',
  'grow': 'Grow a pair.',
  'guess': 'I guess so.',
  'guest': 'Be my guest.',
  'guide': "I'm a guide.",
  'guitar': 'I want a guitar.',
  'guitarist': "I'm a guitarist.",
  'guitars': 'Do you like guitars?',
  'gum': 'I chew gum.',
  'gun': 'Buy a gun.',
  'guns': 'I know guns.',
  'gym': 'Go to the gym.',
  'habits': 'Build good habits.',
  'hair': 'Bad hair day.',
  'haircut': 'Get a haircut.',
  'hairdresser': "I'm a hairdresser.",
  "hairdresser's": "Go to the hairdresser's.",
  'half': 'Cut in half.',
  'ham': 'I eat ham.',
  'hamburger': 'I ate a hamburger.',
  'hamburgers': 'I love hamburgers.',
  'hand': 'Need a hand?',
  'hand-made': 'Zines are hand-made and photocopied books.',
  'handmade': 'It was handmade.',
  'handprint': 'Sami saw a handprint on the ceiling.',
  'hands': 'Feel my hands.',
  'hannah': 'Hannah is a Reform Jew.',
  'happen': 'It did happen.',
  'happened': 'It has happened.',
  'happening': 'Is it happening?',
  'happens': 'It just happens.',
  'happier': "I'm happier now.",
  'happily': "I'll go happily!",
  'happiness': 'I seek happiness.',
  'happy': 'I am happy.',
  'harbour': 'Where is the harbour?',
  'hard': 'Is it hard?',
  'hard-working': 'Are you hard-working?',
  'hardly': 'I hardly work.',
  'has': 'He has it.',
  'hat': 'Get a hat.',
  'hate': 'I hate it.',
  'hats': 'I hate hats.',
  'have': 'I have it.',
  'he': 'It is he.',
  "he'll": "He'll be OK.",
  'head': 'My head hums.',
  'headlight': "The headlight doesn't work.",
  'health': 'To good health.',
  'healthy': 'I am healthy.',
  'hear': 'I hear it.',
  'heard': 'I heard it.',
  'heating': 'Heating is dear.',
  'heavier': "I'm heavier than you.",
  'heavily': 'He drank heavily.',
  'heavy': 'I was heavy.',
  'heed': 'Heed all warnings.',
  'height': "I'm average height.",
  'held': 'He held a ball.',
  'helicopter': 'Take a helicopter.',
  'hello': 'Hello to you.',
  'help': 'I help him.',
  'helpful': 'He was helpful.',
  'hen': "That's a hen.",
  'hero': "I'm a hero.",
  'hers': 'I ate hers.',
  'hid': 'I hid one.',
  'hide': 'I must hide.',
  'high': 'Is it high?',
  'higher': 'Ziri climbed higher.',
  'highest': 'Highest possible weight.',
  'hill': "It's a hill.",
  'him': 'I am him.',
  'himalayas': 'I want to visit the Himalayas.',
  'himself': 'He cut himself.',
  'hire': 'Hire a guide.',
  'his': 'I ate his.',
  'hold': 'Now hold it.',
  'hole': 'Make a hole!',
  'holiday': "I'm on holiday.",
  'holidays': 'I hate holidays.',
  'holland': "I'm from Holland.",
  'hollywood': 'He is a Hollywood star.',
  'home-made': 'Home-made cookies are the best.',
  'homework': 'I have homework.',
  'honest': 'He is honest.',
  'honey': 'I got honey.',
  'hope': 'I hope so.',
  'horn': 'Honk the horn.',
  'horoscope': 'I read my horoscope today.',
  'horrible': 'Am I horrible?',
  'horror': 'Horror has a name.',
  'horse': "It's a horse.",
  'horses': 'I like horses.',
  'hospital': 'Go to hospital.',
  'hospitals': 'I hate hospitals.',
  'host': 'I can host.',
  'hostess': 'Layla is a hostess.',
  'hot': 'I am hot.',
  'hotel': "That's a hotel.",
  'hotels': 'Who rates hotels?',
  'hotter': "It's getting hotter.",
  'hottest': 'Summer is the hottest season.',
  'hour': "It's rush hour.",
  'house': "It's a house.",
  'houseboat': 'They live on a houseboat.',
  'houses': 'I plan houses.',
  'housework': 'We share the housework.',
  'how': 'How is it?',
  'huge': 'It was huge.',
  'hunchback': 'He is a hunchback.',
  'hung': 'I hung up.',
  'hungary': "I'm from Hungary.",
  'hungry': 'Am I hungry!',
  'hunt': 'Do you hunt?',
  'hunter': "I'm a hunter.",
  'hunting': 'I was hunting.',
  'hurdle': 'The initial cost is a hurdle.',
  'hurdles': 'He succeeded in spite of major hurdles.',
  'hurt': 'I am hurt.',
  'husband': 'Call my husband.',
  'ice': 'I need ice.',
  'ice-cream': 'I am licking an ice-cream.',
  'ice-skate': 'Can you ice-skate?',
  'icy': 'The road is icy.',
  'idea': 'Oh, no idea!',
  'ideal': 'That was ideal.',
  'igloo': "The igloo isn't small.",
  'imagine': 'I imagine not.',
  'immediate': 'Was it that immediate?',
  'immediately': 'Do it immediately.',
  'impatient': 'He is impatient.',
  'imperative': "It's the imperative mood.",
  'in': 'I am in.',
  'includes': 'The price includes tax.',
  'indefinite': "It's an indefinite pronoun.",
  'independence': 'I want independence.',
  'india': "I'm in India.",
  'indian': 'I am Indian.',
  'indians': 'They call you Indians.',
  'infinitive': 'I’m studying infinitive verbs.',
  'inn': 'We met in an inn.',
  'insect': 'I ate an insect.',
  'insects': 'I hate insects.',
  'instead': 'Ask him instead.',
  'instructions': 'I obey instructions.',
  'intend': 'I intend to.',
  'intention': "That's my intention.",
  'intentions': 'I have intentions.',
  'interest': 'I lost interest.',
  'interested': 'I am interested.',
  'interesting': 'Am I interesting?',
  'interrogative': 'Do I like interrogative inversions?',
  'interview': 'I saw the interview.',
  'into': 'Into the fog!',
  'introduce': "I'll introduce you.",
  'introducing': "I'll begin by introducing myself.",
  'introduction': 'What an introduction!',
  'invent': 'We will invent it.',
  'inventor': 'Man is an inventor.',
  'inventors': 'I enjoy hearing stories about inventors.',
  'invitations': 'I accepted the invitations.',
  'invite': 'I invite you.',
  'inviting': "I'm inviting you.",
  'ireland': "I'll go to Ireland.",
  'ironing': 'I hate ironing.',
  'irregular': 'This is irregular.',
  'island': 'I own that island.',
  'islander': "I'm an islander.",
  "isn't": "Isn't it so?",
  'it': 'It is I.',
  "it's": "It's a TV.",
  'italian': 'I am Italian.',
  'italy': 'I miss Italy.',
  'item': 'Are we an item?',
  'items': 'No items were taken.',
  'jacket': 'Take a jacket.',
  'january': "It's now January.",
  'japan': 'This is Japan.',
  'japanese': 'I am Japanese.',
  'jean': 'Are you Jean?',
  'jeans': 'I had jeans on.',
  'jeep': 'I drive a jeep.',
  'jennifer': 'Take Jennifer for example.',
  'jenny': 'Jenny has a gun.',
  'jerry': 'My name is Ziri, not Jerry.',
  'jewellery': 'Do you sell jewellery?',
  'jobs': 'We want jobs.',
  'jog': 'Shall we jog?',
  'johnsons': 'The Johnsons love to have parties.',
  'join': 'Can I join?',
  'jokes': 'I love jokes.',
  'journey': 'Life is a journey.',
  'joy': 'What is joy?',
  'juice': 'I need juice.',
  'july': "It's now July.",
  'jump': 'I can jump.',
  'jumped': 'I jumped up.',
  'jumper': 'I like his jumper.',
  'june': "It's now June.",
  'jungle': 'What a jungle!',
  'kangaroos': 'Can kangaroos get rabies?',
  'kayak': 'Ziri had a small kayak.',
  'keep': 'I keep it.',
  'keeper': "He's a keeper.",
  'key': 'Use my key.',
  'keys': 'Get your keys.',
  'kill': 'You kill me!',
  'killer': "He's a killer.",
  'kilo': 'How much for half a kilo?',
  'kind': 'I am kind.',
  'kinder': 'Be a little kinder!',
  'kindness': 'Kindness is free.',
  'king': 'We are King.',
  'kiss': 'Kiss my ass.',
  'kitchen': 'In the kitchen.',
  'kitten': "I'm a kitten.",
  'knew': 'I knew it.',
  'knife': 'Get a knife.',
  'knives': 'There are no knives.',
  'knock': 'Knock it off.',
  'know': 'I know it.',
  'knowledge': 'I give knowledge.',
  'koalas': 'Koalas are cute.',
  'ladder': 'Get a ladder.',
  'ladybird': 'The two-spotted ladybird is very rare.',
  'lain': 'Lain killed herself.',
  'lake': 'Drain the lake.',
  'lamb': 'I hate lamb.',
  'lamp': 'I need a lamp.',
  'lamps': 'Put your fog lamps on.',
  'land': 'I see land!',
  'lane': 'Stay in your lane.',
  'language': 'Choose a language.',
  'large': 'It is large.',
  'larger': 'Make it larger.',
  'late': 'Am I late?',
  'lately': 'He died lately.',
  'laugh': 'Let me laugh.',
  'laughed': 'No one laughed.',
  'law': "I'm the law.",
  'lawyer': "I'm a lawyer.",
  'lay': 'He lay down.',
  'laze': 'We can laze around on the weekend.',
  'lazy': 'I am lazy.',
  'lead': 'May I lead?',
  'leaf': 'A leaf is falling.',
  'leaflet': 'Ziri showed the leaflet to Rima.',
  'learn': 'I will learn.',
  'learned': 'I learned a lot.',
  'leather': 'Is it leather?',
  'leaves': 'The leaves fell.',
  'leaving': 'I am leaving.',
  'lecture': "Don't lecture me.",
  'lee': 'I met him through Lee.',
  'left': 'I left one.',
  'leg': 'Ow, my leg!',
  'legal': 'Is it legal?',
  'lemon': 'Take a lemon.',
  'lemons': 'Lemons are sour.',
  'lend': 'I lend money.',
  'length': "What's the length?",
  'lens': 'She used a zoom lens.',
  'leo': "I'm a Leo.",
  'less': 'I want less.',
  'lesson': 'Lesson Two is easy.',
  'lessons': 'Do you give lessons?',
  'let': 'Let me go!',
  'lettuce': 'Lettuce is OK.',
  'leukaemia': 'I have leukaemia.',
  'library': 'At the library.',
  'life': 'Get a life.',
  'light': 'Light it up.',
  'like': 'I like it.',
  'likes': 'He likes me.',
  'lion': "I'm a lion.",
  'lioness': "I'm a lioness.",
  'lions': 'Lviv for lions!',
  'lip': 'I bit my lip.',
  'lips': 'Ask my lips.',
  'lisa': 'Lisa is German.',
  'listen': 'Listen to me.',
  'listening': 'I am listening.',
  'lists': 'We all love lists.',
  'litter': 'Tidy up the litter!',
  'little': 'Try a little.',
  'live': 'I live it.',
  'lived': 'I lived here.',
  'lives': 'He lives here.',
  'living': 'I like living.',
  'loaf': 'Use your loaf!',
  'loaves': 'Buy a few loaves of bread.',
  'local': 'He is a local.',
  'location': "What's your location?",
  'loch': 'The Loch Ness monster is an urban myth.',
  'lodger': 'Layla took her lodger, Fadil, as her lover.',
  'long': 'Is it long?',
  'longer': 'How much longer?',
  'longest': 'Which line is longest?',
  'look': 'Look at me.',
  'looked': 'I looked up.',
  'looking': 'Is he looking?',
  'loose': 'The top is loose.',
  'lose': 'We may lose.',
  'lost': 'I am lost.',
  'loud': 'It was loud.',
  'loudly': 'Say it loudly.',
  'louvre': 'The Louvre is closed.',
  'love': 'I love u.',
  'loved': 'I loved it.',
  'lovelier': "You're even lovelier in a Kabyle dress.",
  'lovely': 'I was lovely.',
  'loves': 'He loves us.',
  'loving': "I'm loving it.",
  'luck': "I'm in luck.",
  'luckily': 'Luckily, it worked.',
  'lucky': 'I am lucky.',
  'lunch': 'Lunch is on.',
  'luxurious': 'He wore luxurious clothes.',
  'made': 'I made it.',
  'magazine': 'I bought a magazine.',
  'magazines': 'I collect magazines.',
  'magic': 'It was magic.',
  'magician': "I'm a magician.",
  'main': "It's my main job.",
  'make': 'Make it so.',
  'making': "I'm making it.",
  'male': 'I saw a male lion.',
  'mammal': "It's a mammal.",
  'mammals': 'Are bats mammals?',
  'man': 'Be a man.',
  'mane': 'Lionesses have no mane.',
  'maniac': "I'm a maniac.",
  'many': 'Many will die.',
  'map': 'Get a map.',
  'march': 'March is over.',
  'mare': "What's a mare?",
  'maria': 'Is Maria gone?',
  'mark': "I'm not Mark.",
  'marks': 'On your marks.',
  'marriage': 'Marriage is holy.',
  'married': 'I am married.',
  'marry': "I'll marry you.",
  'masks': 'Put your masks on.',
  'match': 'I lit a match.',
  'mathematician': "I'm a mathematician.",
  'maths': 'I like maths.',
  'me': 'I am me.',
  'meal': 'I had a meal.',
  'meals': 'Eat meals slowly.',
  'meaning': 'It has no meaning.',
  'meat': 'I eat meat.',
  'mechanic': "I'm a mechanic.",
  'medical': 'I need medical help.',
  'medicine': 'I sell medicine.',
  'mediterranean': 'Mediterranean weather is mild.',
  'meet': 'We can meet.',
  'meeting': 'What a meeting!',
  'meets': 'The family meets often.',
  'member': "I'm a member.",
  'memorable': 'It was a memorable night.',
  'memories': "I've got memories.",
  'men': 'We are men.',
  'mentioned': 'Am I mentioned?',
  'menu': 'It is a menu.',
  'mess': "I'm a mess.",
  'met': 'I met him.',
  'metal': 'Lead is metal.',
  'metres': 'Where are the metres?',
  'mexican': 'I love Mexican food.',
  'mexico': 'Am I from Mexico?',
  'mice': 'I hate mice.',
  'midday': 'It is midday.',
  'middle': "I'm middle class.",
  'middle-aged': 'He was middle-aged.',
  'midnight': 'It was midnight.',
  'mile': 'Ben ran a mile.',
  'military': 'Sami was a military.',
  'milk': 'I had milk.',
  'milkshake': 'I got you a milkshake.',
  'mind': 'I do mind.',
  'mine': 'It is mine.',
  'minute': 'Got a minute?',
  'miss': 'I miss it.',
  'mississippi': 'Where is Mississippi?',
  'mistakes': 'I made mistakes.',
  'mister': 'Yes, mister deputy!',
  'mistress': 'She is my mistress!',
  'models': 'Who are your role models?',
  'modern': "He's a modern boy.",
  'moment': 'Wait a moment.',
  'monday': 'Do it Monday.',
  'money': 'I want money.',
  'monkey': 'I saw a monkey.',
  'monkeys': 'I love monkeys.',
  'monster': "I'm a monster.",
  'monsters': 'You are monsters!',
  'montreal': 'Layla was from Montreal.',
  'moon': 'The moon rose.',
  'moose': 'He saw a moose.',
  'more': 'I pay more.',
  'morning': 'It is morning.',
  'moscow': "He's in Moscow.",
  'mother': "I'm a mother.",
  'motorcycle': 'I have a motorcycle.',
  'mountain': 'This is my mountain.',
  'mountains': 'I climb mountains.',
  'mouse': "I'm a mouse.",
  'moustache': 'He has a moustache.',
  'mouth': 'It is my mouth.',
  'move': 'Move it up.',
  'moved': 'I moved on.',
  'movement': 'Movement is sensual.',
  'mow': 'Mow the lawn.',
  'mud': 'My name is mud.',
  'mum': 'Mum is home.',
  'museum': 'Go to the museum.',
  'museums': "I don't go to museums.",
  'music': 'I hear music.',
  'musician': "I'm a musician.",
  'must': 'I must go.',
  'my': 'Oh my God!',
  'myself': 'I see myself.',
  'names': 'I want names.',
  'nanny': 'I was a nanny.',
  'narrow': "It's too narrow.",
  'nationalities': "Let's learn nationalities and countries in Berber.",
  'nationality': "What's her nationality?",
  'near': 'Come near me.',
  'nearly': 'I nearly died.',
  'necessary': 'It is necessary.',
  'neck': 'My neck hurts.',
  'need': 'I need it.',
  'neighbour': "He's my neighbour.",
  'neighbourhood': 'Visit your neighbourhood.',
  'nephew': "He's my nephew.",
  'nervous': 'I got nervous.',
  'nervously': 'Annie ate nervously.',
  'nessie': 'Have you ever heard of Nessie?',
  'network': "It's a network.",
  'never': 'I never lie.',
  'new': 'Is it new?',
  'newer': 'Which one is newer?',
  'news': 'I have news.',
  "newsagent's": "Newspapers are sold at a newsagent's.",
  'newspaper': 'I have a newspaper.',
  'next': 'Am I next?',
  'nice': 'He is nice.',
  'nicer': 'Be nicer to him.',
  'niece': 'I know my niece.',
  'night': 'It is night.',
  'nightclubs': 'He loves nightclubs.',
  'nightlife': 'We enjoyed the nightlife.',
  'nine': "It's ten to nine.",
  'nineteen': 'She was nineteen then.',
  'ninth': 'I am the ninth one.',
  'no': 'Yes or no?',
  'nobody': "I'm a nobody.",
  'noise': 'I made noise.',
  'noises': 'I heard noises.',
  'noisier': 'Our street is noisier than yours.',
  'noisy': 'I got noisy.',
  'noodles': 'I eat noodles.',
  'noon': 'Come at noon.',
  'north': 'He moved north.',
  'north-east': 'Estonia is in north-east Europe.',
  'north-west': 'I am located on the North-west side.',
  'northern': 'I speak Northern Kurdish.',
  'nose': 'His nose bled.',
  'notebook': 'It is a notebook.',
  'notebooks': 'Open your notebooks.',
  'noticeboard': 'The information is posted on the noticeboard.',
  'noun': "It's a countable noun.",
  'now': 'Do it now.',
  'nowadays': "I'm not busy nowadays.",
  'nowhere': 'Nowhere is safe.',
  'nurse': "I'm a nurse.",
  'nursing': 'Layla was nursing.',
  'nuts': 'I am nuts.',
  "o'clock": "It's pi o'clock.",
  'oak': 'Strong as an oak.',
  'oat': 'Oat porridge tastes best with milk.',
  'object': 'Do you object?',
  'objects': 'Women are not objects.',
  'obligation': "It's my obligation.",
  'oblige': 'I was happy to oblige.',
  'occupation': "What's her occupation?",
  'ocean': 'I love the ocean.',
  'oceans': 'Mars once had oceans.',
  'offers': "I've had worse offers.",
  'office': 'Lock the office.',
  'offices': "They're in their offices.",
  'often': 'I go often.',
  'okay': 'I am okay.',
  'old': 'I am old.',
  'old-fashioned': 'Mom is old-fashioned.',
  'older': 'I got older.',
  'oldest': "I'm the oldest.",
  'olive': 'Add an olive.',
  'on': 'Go on in.',
  'once': 'Once a year.',
  'one': 'I got one!',
  'ones': "We'll get new ones.",
  'onion': 'I like onion.',
  'opened': 'I opened one.',
  'opening': "I'm opening a box.",
  'opinion': 'Have an opinion.',
  'opposite': "It's the opposite.",
  'opposites': "We're total opposites.",
  'optician': 'Sami is an optician.',
  'orange': 'Is it orange?',
  'oranges': 'I like oranges.',
  'order': 'As you order!',
  'ordering': "I'm ordering pizza.",
  'orders': 'I have orders.',
  'ore': 'Ore is enriched here.',
  'origin': "I'm of Berber origin.",
  'ottawa': 'Go to Ottawa!',
  'our': 'Our team won.',
  'ours': 'Is it ours?',
  'ourselves': 'We fed ourselves.',
  'out': 'Is it out?',
  'outside': 'I am outside.',
  'over': 'Is it over?',
  'overweight': 'He is overweight.',
  'owl': 'The owl hoots.',
  'own': 'I own a car.',
  'owner': "I'm the owner.",
  'ox': 'Strong as an ox.',
  'oxen': 'We trade in oxen.',
  'oxford': 'Is this the bus to Oxford?',
  'oxygen': 'I need oxygen.',
  'pack': 'Pack your bags.',
  'packed': 'I packed up.',
  'packet': 'It costs a packet.',
  'paddle': "You'll paddle, right?",
  'pain': 'What a pain!',
  'paint': 'I need paint.',
  'painting': 'I was painting.',
  'paintings': 'I saw your paintings.',
  'pal': "You're my pal.",
  'pale': 'Am I pale?',
  'pane': 'Who broke that window pane?',
  'panic': 'Can I panic?',
  'papers': 'I lost my papers.',
  'parade': "Let's join the parade.",
  'paragraph': 'Read this paragraph.',
  'paragraphs': 'I like to write short paragraphs.',
  'parent': "I'm a parent.",
  'parents': 'The parents die.',
  'paris': "I'm in Paris.",
  'park': "It's a park.",
  'parrots': 'Parrots can sing.',
  'participle': 'This sentence contains a participle.',
  'particular': "I'm not particular.",
  'parties': 'I love parties.',
  'partner': 'I made partner.',
  'parts': 'He stole car parts.',
  'pass': 'Pass it on.',
  'passport': 'I have a passport.',
  'past': "I'm your past.",
  'pasta': 'I eat pasta.',
  'patience': 'I lost patience.',
  'patient': 'I am patient.',
  'paw': 'He has a broken paw.',
  'paws': 'A dog has four paws.',
  'peace': 'Go in peace.',
  'peaceful': 'It was peaceful.',
  'peach': "He's a peach.",
  'pear': 'Eat a pear.',
  'pebble': 'This is a pebble.',
  'pee': 'I had to pee.',
  'pees': 'He pees in bed.',
  'pen': 'Get a pen.',
  'pencil': "It's a pencil.",
  'pencils': 'Do you have pencils?',
  'penguin': "I'm not a penguin.",
  'penguins': 'I like penguins.',
  'penicillin': "I'm allergic to penicillin.",
  'penny': 'Is Penny lying?',
  'people': 'People got up.',
  'pepper': 'I like pepper.',
  'per': "It's one per customer.",
  'perfect': 'I am perfect.',
  'perform': 'I perform my duty.',
  'performance': 'What a performance!',
  'perfume': 'I sell perfume.',
  'perhaps': 'Perhaps he can.',
  'permission': 'We need permission.',
  'person': "I'm a person.",
  'personal': 'It was personal.',
  'pet': 'Get a pet.',
  'philosopher': 'He became a philosopher.',
  'photograph': "It's a photograph.",
  'photographer': "I'm a photographer.",
  'photographs': 'Sami has photographs.',
  'photos': 'I took photos.',
  'physicist': "I'm a physicist.",
  'physics': 'Physics is hard.',
  'pianist': "He's a pianist.",
  'piano': 'I play piano.',
  'pianos': 'Pianos are heavy.',
  'pick': 'Pick it up.',
  'picnic': "It's no picnic.",
  'picnics': 'I like picnics.',
  'pie': 'I like pie.',
  'piece': 'Piece of cake!',
  'pieces': "It's in pieces.",
  'pierre': 'Pierre got sick.',
  'pill': 'Take your pill.',
  'pillow': 'Get me a pillow.',
  'pilots': 'They are pilots.',
  'pine': 'I pine for you.',
  'pineapple': 'I ate pineapple.',
  'pisces': "I'm a Pisces.",
  'pizzas': 'I deliver pizzas.',
  'place': 'Use my place.',
  'places': 'Take your places.',
  'plan': 'Plan on it.',
  'planned': 'It was planned.',
  'plans': 'I have plans.',
  'plant': "It's a plant.",
  'plants': 'I have plants.',
  'play': 'I can play.',
  'played': 'He played it.',
  'player': "He's a player.",
  'playing': 'I am playing.',
  'plays': 'He plays well.',
  'pleasant': 'He is pleasant.',
  'please': 'Please do it.',
  'pleased': 'I was pleased.',
  'plumber': "I'm a plumber.",
  'plural': 'It is plural.',
  'pm': 'Could you PM me?',
  'pneumonia': 'I have pneumonia.',
  'points': 'We need points.',
  'poland': 'Poland is next.',
  'police': 'Call the police!',
  'policeman': "I'm a policeman.",
  'policemen': 'Are you policemen?',
  'polish': 'I love Polish!',
  'polite': 'He was polite.',
  'politely': 'I bowed politely.',
  'politician': "I'm a politician.",
  'politics': 'I hate politics.',
  'pollute': 'Cars pollute a lot.',
  'polluted': 'Our air is polluted.',
  'pollution': "It's noise pollution.",
  'pool': "It's a pool.",
  'poor': 'I am poor.',
  'possession': 'This is his only possession.',
  'possessive': 'Are you possessive?',
  'post': 'Post No Bills.',
  'postcard': 'Send me a postcard.',
  'postcards': 'She sold postcards.',
  'poster': 'Yuri saw the poster.',
  'posters': 'Did you see the posters?',
  'postman': 'Ziri is a postman.',
  'postmen': 'The postmen sort the mail each morning.',
  'potato': 'I am a potato.',
  'potatoes': 'I like potatoes.',
  'pouch': 'Santiago put the money in his pouch.',
  'pound': 'Give me a pound of ham.',
  'pour': 'Just pour in!',
  'practise': 'Practise or lose.',
  'predict': 'Did you predict it?',
  'prediction': 'Make a prediction.',
  'predictions': 'Many predictions fail.',
  'preposition': 'Some verbs have a fixed preposition.',
  'prepositions': 'All prepositions take the nominative.',
  'present': 'I was present.',
  'presenter': "He's a presenter.",
  'preside': 'Tom will preside.',
  'president': 'Run for president.',
  'presley': 'Elvis Presley lives!',
  'prettier': 'That is prettier.',
  'prettiest': 'My wife is the prettiest.',
  'price': 'The price rose.',
  'prices': 'Prices went up.',
  'priest': "I'm a priest.",
  'prince': "He's a prince.",
  'princess': 'Be my princess.',
  'prize': "What's my prize?",
  'probable': 'It seems probable.',
  'probably': "I'm probably OK.",
  'problems': 'He has problems.',
  'produce': 'I produce music.',
  'producer': "I'm the producer.",
  'programme': 'Aging is a programme.',
  'progress': 'Progress was slow.',
  'prohibit': 'One should prohibit it.',
  'prohibition': 'The boy smoked despite the prohibition.',
  'project': 'Fork the project.',
  'pronoun': "What's a pronoun?",
  'pronounced': 'How is it pronounced?',
  'pronouns': 'I detest pronouns.',
  'pronunciation': 'His pronunciation is good.',
  'proper': 'Sami talks proper.',
  'properly': 'Do it properly.',
  'protect': 'God protect you.',
  'protection': 'I need protection.',
  'proud': "I'm so proud.",
  'provided': 'They provided support.',
  'psychologist': "I'm a psychologist.",
  'pub': "Where's the pub?",
  'publish': 'Click to publish.',
  'publisher': 'I met my publisher.',
  'publishing': 'Stop publishing bullshit.',
  'pubs': 'The pubs were packed.',
  'pun': 'This is a pun.',
  'puppy': 'I got a puppy.',
  'push': 'Push it in.',
  'put': 'Put it on.',
  'puzzle': 'What a puzzle.',
  'pyjamas': 'He wears pyjamas.',
  'pyramids': 'The pyramids are tombs.',
  'quarter': "It's quarter of.",
  'queen': 'Be my queen.',
  'question': 'Ask a question.',
  'queue': 'Join the queue.',
  'quick': 'Do it quick!',
  'quickly': 'I go quickly.',
  'quiet': 'I am quiet.',
  'quieter': 'Things are quieter.',
  'quite': "I'm quite up.",
  'rain': 'It may rain.',
  'rainbow': 'Sun and rain, rainbow.',
  'raincoat': 'I have a raincoat.',
  'rainforest': 'Save the rainforest!',
  'rainy': 'Is it rainy?',
  'ran': 'I ran out.',
  'ranges': 'He ranges with the great writers.',
  'rarely': 'I rarely cry.',
  'raspberry': 'This is raspberry.',
  'ray': 'In the sky appeared a ray of light.',
  'reach': 'Can you reach?',
  'react': "I didn't react.",
  'reaction': 'I fear his reaction.',
  'read': 'I read it.',
  'reader': "I'm a slow reader.",
  'reading': 'I am reading.',
  'reads': 'It reads well.',
  'ready': 'I am ready.',
  'reason': 'I see no reason.',
  'reasonable': 'Now be reasonable.',
  'reasons': 'I had my reasons.',
  'received': 'I received one.',
  'receptionist': 'Sami is a receptionist.',
  'record': 'Record all of it.',
  'recycle': 'Do you recycle?',
  'recycling': 'Are you against recycling?',
  'red': 'Is it red?',
  'reddish': 'The sky is reddish.',
  'reed': 'Man is a thinking reed.',
  'refrigerator': 'Close the refrigerator.',
  'refusal': 'He gave a flat refusal.',
  'refuse': 'But I refuse.',
  'rehearsal': 'I hate rehearsal.',
  'related': 'Are you related?',
  'relative': "I'm a relative.",
  'relativity': 'Who invented the theory of relativity?',
  'relax': 'Try to relax.',
  'relaxed': 'I was relaxed.',
  'relaxing': 'It was relaxing.',
  'relieved': 'I am relieved.',
  'rent': 'Pay the rent.',
  'repeat': "It's a repeat.",
  'replace': "I'll replace it.",
  'report': 'Write a report.',
  'reporter': "I'm a reporter.",
  'reporters': 'Are you reporters?',
  'reptile': 'This is a reptile.',
  'reptiles': 'I hate reptiles.',
  'requests': "I don't do requests.",
  'require': 'I require one.',
  'reservation': 'I have a reservation.',
  'reserve': 'Did you reserve a table?',
  'rest': 'I can rest.',
  'restaurant': 'I run the restaurant.',
  'restaurants': 'Restaurants are expensive.',
  'result': 'It is a result.',
  'return': 'I can return.',
  'returned': 'I have returned.',
  'revision': 'Today is revision day.',
  'rewrite': "I'll rewrite it.",
  'rex': 'I named my dog Rex.',
  'rice': 'I eat rice.',
  'rich': 'I am rich.',
  'ridden': "Yaks can't be ridden.",
  'ride': 'Want a ride?',
  'rider': 'The rider is not careful.',
  'rides': 'He rides a horse.',
  'riding': 'Ziri was riding.',
  'ring': 'Ring me up.',
  'river': 'A river flows.',
  'rivers': 'Why do we have rivers?',
  'riverside': 'The right riverside is steep.',
  'road': 'The road ends.',
  'roar': 'The lion goes roar.',
  'roared': 'The thunder roared.',
  'roast': "I'll roast meat.",
  'rock': "I'm a rock.",
  'rocky': 'This path is rocky.',
  'rode': 'I rode one.',
  'roe': 'What she liked best was herring roe.',
  'role': "What's my role?",
  'roll': 'Have a roll.',
  'romantic': 'Am I romantic?',
  'rome': "I'm in Rome.",
  'roof': 'Fix the roof.',
  'roofs': 'The roofs are modular.',
  'room': 'Get a room.',
  'rooms': 'Rooms are black.',
  'rooster': 'The rooster crows.',
  'rose': "It's a rose.",
  'round': 'It was round.',
  'routine': 'This was routine.',
  'routines': 'Routines are not my thing.',
  'royal': "It's a royal letter.",
  'rubber': "This isn't rubber.",
  'rubbish': 'This is rubbish.',
  'rude': 'I was rude.',
  'rug': 'She has a rug.',
  'rules': 'I hate rules.',
  'run': 'I do run.',
  'rung': 'She has rung.',
  'runner': "I'm a runner.",
  'running': 'I am running.',
  'rush': 'Do not rush!',
  'russia': 'Russia is big.',
  'sad': 'I was sad.',
  'sadness': 'What is sadness?',
  'safe': 'Am I safe?',
  'safer': 'It is safer.',
  'safest': 'Suspenders are safest.',
  'safety': 'Safety comes first.',
  'said': 'I said so.',
  'sail': 'He set sail.',
  'sailing': 'Sailing is fun.',
  'salads': 'She likes salads.',
  'salami': 'I like salami.',
  'sale': "It's for sale.",
  'salt': 'Is it salt?',
  'salty': 'This is salty.',
  'same': 'Same for me.',
  'sand': 'I ate sand.',
  'sandals': 'I bought sandals.',
  'sandcastle': "Let's make a sandcastle.",
  'sandwich': 'I had a sandwich.',
  'sandwiches': 'I like sandwiches.',
  'sandy': 'I date Sandy.',
  'sang': 'I sang one.',
  'sat': 'I sat up.',
  'satisfied': 'I am satisfied.',
  'satisfy': "He's hard to satisfy.",
  'satisfying': 'It felt satisfying.',
  'saturday': 'It is Saturday.',
  'sauce': 'Try this sauce.',
  'sausage': 'I like sausage.',
  'save': 'What a save!',
  'saved': 'I saved it.',
  'saves': 'Seitan saves lives.',
  'saw': 'I saw it.',
  'say': 'Let me say.',
  'scare': 'I scare him.',
  'scared': 'I am scared.',
  'scary': 'Am I scary?',
  'scat': "Tom became concerned about Mary's scat fetish.",
  'school': 'Go to school.',
  'schools': 'Our schools stink.',
  'science': 'Science is fun.',
  'scientist': "I'm a scientist.",
  'scissors': 'I need scissors.',
  'scorpio': "I'm a Scorpio.",
  'scotland': "He's in Scotland.",
  'scottish': 'Are you Scottish?',
  'screamed': 'I screamed again.',
  'screen': 'Look at the screen.',
  'sculptor': "I'm a sculptor.",
  'sculpture': "I'm a sculpture.",
  'sea': 'The sea roars.',
  'seabed': 'Diverse life forms live on the seabed.',
  'seal': 'I am a seal.',
  'seals': 'I like seals!',
  'seas': 'What are the seven seas?',
  'season': "It's tax season.",
  'seasons': 'Why is there seasons?',
  'seat': 'Have a seat.',
  'sec': 'Wait a sec.',
  'second': 'I was second.',
  'sect': 'The elite is a sect.',
  'see': 'I see it.',
  'seems': 'It seems so.',
  'seer': 'Mary is a seer.',
  'sees': 'It sees me.',
  'seine': 'The Seine crosses Paris.',
  'self': "He's self centered.",
  'sell': 'I sell art.',
  'send': 'Send him in.',
  'sent': 'I sent one.',
  'september': "It's now September.",
  'serious': 'Is it serious?',
  'servant': "I'm your servant.",
  'serve': 'I serve no one.',
  'service': 'I had service.',
  'settee': "That's my settee.",
  'seven': 'On cloud seven.',
  'seventeen': 'She is aged seventeen.',
  'seventy': 'She weighs seventy kilos.',
  'sewed': 'I sewed one on.',
  'shadow': "It's a shadow.",
  'shall': 'Shall we go?',
  'shallow': 'I am shallow.',
  'sharks': 'I saw sharks.',
  'sharp': 'It is sharp.',
  'she': 'Is she OK?',
  'sheep': 'I got sheep.',
  'shelf': 'On which shelf?',
  'shelves': 'Dust the shelves.',
  'shine': 'Rise and shine.',
  'shines': 'The sun shines.',
  'shining': 'Stars are shining.',
  'shirt': 'I dry my shirt.',
  'shock': 'What a shock!',
  'shocked': 'I was shocked.',
  'shoes': 'I sell shoes.',
  'shop': 'Go to the shop.',
  'shopping': 'I go shopping.',
  'shops': 'He shops online.',
  'short': 'I am short.',
  'shorter': 'I am shorter than he.',
  'shorts': 'Eat my shorts!',
  'shot': 'I was shot.',
  'shout': "It's my shout.",
  'shouted': 'No one shouted.',
  'show': 'Show me it.',
  'shower': 'Take a shower.',
  'shown': "Sami hasn't shown up.",
  'shows': 'He always shows.',
  'shut': 'I shut up.',
  'sick': 'I am sick.',
  'sickness': 'What is her sickness?',
  'sieve': 'This is a sieve.',
  'sight': 'What a sight!',
  'sights': 'Adjust your sights.',
  'sightseeing': 'I went sightseeing.',
  'sign': "It's a sign.",
  'silk': 'We sell silk.',
  'sill': 'The ivy crawls along the window sill.',
  'silly': 'Am I silly?',
  'similar': 'It is similar.',
  'simple': 'It was simple.',
  'sing': 'I sing now.',
  'singer': "I'm a singer.",
  'singers': 'They are singers.',
  'singing': 'I am singing.',
  'single': 'I am single.',
  'sink': 'Boats can sink.',
  'sister': "I'm a sister.",
  'sisters': 'I have sisters.',
  'sit': 'Sit by me.',
  'sitting': 'He is sitting.',
  'six': 'On your six!',
  'sixteen': 'Sami was sixteen.',
  'sixth': 'Thomas got sixth.',
  'sixty': 'I have sixty ERN.',
  'size': 'What size is it?',
  'skate': 'I can skate.',
  'skater': "He's a skater.",
  'ski': 'I can ski.',
  'skid': 'Some of them went into a skid.',
  'skidded': 'I skidded to a stop.',
  'skiing': 'I was skiing.',
  'skin': 'My skin is dry.',
  'skirt': "Here's a skirt.",
  'sledge': 'Vladimir travels on his sledge.',
  'sleep': 'Go to sleep.',
  'sleepily': 'He opened the door sleepily.',
  'sleeping': 'I am sleeping.',
  'sleeps': 'A cat sleeps.',
  'sleepy': 'I am sleepy.',
  'slept': 'I slept OK.',
  'slice': 'Slice the bread.',
  'slide': 'Let it slide.',
  'slim': 'She is slim.',
  'slow': 'I was slow.',
  'small': 'I am small.',
  'smaller': 'Make it smaller.',
  'smell': 'Do I smell?',
  'smells': 'He smells bad.',
  'smelt': 'We smelt gas.',
  'smile': 'Try to smile.',
  'smoke': 'May I smoke?',
  'smoking': 'I am smoking.',
  'snake': "It's a snake.",
  'snapshot': 'Sami has saved the snapshot.',
  'snow': 'It may snow.',
  'snowball': 'We had a snowball fight.',
  'snowballs': "Ziri threw snowballs at Rima's window.",
  'snowing': 'It is snowing.',
  'snowman': "It's a snowman.",
  'snows': 'It snows hard.',
  'snowy': 'Is it snowy?',
  'so': 'So do I.',
  'society': 'Society is sick.',
  'socks': 'I wear socks.',
  'sofa': 'I have a sofa.',
  'sofas': "Sofas like that don't come cheap.",
  'some': 'I had some.',
  'something': 'Go do something.',
  'sometimes': 'I sometimes skate.',
  'son': "It's my son.",
  'sons': 'He had no sons.',
  'soon': 'Do it soon.',
  'sophie': 'They greeted Sophie.',
  'sorry': 'I am sorry.',
  'sort': "I'm sort of busy.",
  'sound': 'Make a sound.',
  'sounds': 'It sounds fun.',
  'soup': 'I want soup.',
  'soups': 'I love soups.',
  'south': 'To the south.',
  'southern': 'He has a Southern accent.',
  'souvenir': 'I want a souvenir.',
  'souvenirs': 'I collect souvenirs.',
  'space': 'I need space.',
  'spaceship': 'Ogo has a spaceship.',
  'spaghetti': 'Is spaghetti OK?',
  'spain': "I'm in Spain.",
  'spanish': 'He is Spanish.',
  'spare': 'Spare some change?',
  'speak': 'Speak to me.',
  'speaking': 'I am speaking.',
  'speech': 'What a speech!',
  'spell': 'Spell it for me!',
  'spelling': 'Spelling is fun.',
  'spencer': 'Tom punched Richard Spencer in the face.',
  'spend': 'I spend little.',
  'spent': 'I am spent.',
  'sphinx': 'What is a sphinx?',
  'spice': "That's a spice.",
  'spicy': 'Is it spicy?',
  'spoke': 'I spoke up.',
  'spoken': 'I have spoken.',
  'spoon': 'Get a spoon.',
  'sports': 'I like sports.',
  'spot': 'I was spot on.',
  'sprang': 'You sprang a trap.',
  'spring': 'It is spring.',
  'staff': 'We need more staff.',
  'stairs': 'Take the stairs.',
  'stand': 'Stand by me.',
  'stank': 'The house stank.',
  'star': "I'm a star.",
  'starred': 'The movie starred Yanni.',
  'stars': 'How many stars?',
  'start': 'Can I start?',
  'starter': 'Is there a starter?',
  'starts': 'The movie starts.',
  'statements': 'They both gave statements.',
  'station': 'Go to the station.',
  'statue': 'I see the statue.',
  'statues': 'Those statues are creepy.',
  'staying': 'I am staying.',
  'steak': 'I like steak.',
  'steven': 'Steven lives in Florida.',
  'stick': 'Stick to it!',
  'still': 'I sat still.',
  'stole': 'We stole it.',
  'stone': 'I see a stone.',
  'stood': 'I stood by.',
  'stop': 'Stop, I say.',
  'stopped': 'I stopped it.',
  'stopping': 'Try stopping me.',
  'store': 'Go to the store!',
  'stories': 'I like stories.',
  'storm': 'What a storm!',
  'stormy': "It's a stormy day.",
  'straight': 'I am straight.',
  'strange': 'I am strange.',
  'strangely': 'He acted strangely.',
  'strawberries': 'I ate strawberries.',
  'strawberry': 'I want a strawberry.',
  'street': 'Up the street.',
  'streets': "I'm on the streets.",
  'strength': 'Strength in unity.',
  'stress': 'Stress is a killer.',
  'stressed': 'He is stressed.',
  'stressful': 'It was stressful.',
  'strict': 'He was strict.',
  'strong': 'I am strong.',
  'student': "I'm a student.",
  'students': 'We are students.',
  'studied': 'I studied it.',
  'studio': 'I want a studio cat.',
  'study': 'Study a lot.',
  'stupid': 'Am I stupid?',
  'subject': "He's a subject.",
  'success': 'Dress for success.',
  'successful': 'He is successful.',
  'sudden': 'I felt a sudden pain.',
  'suddenly': 'He died suddenly.',
  'sugar': 'Is it sugar?',
  'suggest': 'I suggest we hurry.',
  'suggestion': 'I have a suggestion.',
  'suggestions': 'I have suggestions.',
  'suit': "It's a suit.",
  'suitcase': "It's my suitcase.",
  'suitcases': 'Open the suitcases.',
  'summary': 'Make a summary.',
  'summer': 'It is summer.',
  'sun': 'The sun set.',
  'sunbathe': 'I never sunbathe.',
  'sunbathing': 'Are you sunbathing?',
  'sunday': 'It is Sunday.',
  'sundays': 'I hate Sundays.',
  'sunglasses': 'I have sunglasses.',
  'sunny': 'It is sunny.',
  'sunset': 'Sunset drew near.',
  'sunshade': 'There was a sunshade over the sidewalk.',
  'superlative': "Harun's review was brimming with superlative adjectives.",
  'surgeon': "I'm a surgeon.",
  'surgeons': 'Are you surgeons?',
  'surgery': 'I had surgery.',
  'surprise': "It's a surprise.",
  'surprised': 'I am surprised.',
  'surprising': 'It was surprising.',
  'sweater': 'Take a sweater.',
  'sweden': "I'm from Sweden.",
  'sweet': 'It was sweet.',
  'sweets': 'I like sweets.',
  'swim': 'I can swim.',
  'swimmer': "I'm a swimmer.",
  'swimming': 'Is he swimming?',
  'swims': 'He swims here.',
  'switzerland': "I'm from Switzerland.",
  'sydney': 'Sydney is far from here.',
  'sympathetic': 'I was sympathetic.',
  'symphony': 'Can you write a symphony?',
  'synonyms': 'Find the synonyms.',
  'table': "It's a table.",
  'tables': "I'm waiting tables.",
  'tag': 'We played tag.',
  'tail': "It's a tail.",
  'take': 'I take it.',
  'tale': 'She told a tale.',
  'talk': 'Talk to me!',
  'talking': 'I am talking.',
  'tall': 'I am tall.',
  'taller': 'I am taller.',
  'taste': 'Have a taste.',
  'tasty': 'Is it tasty?',
  'taught': 'He taught me.',
  'taxi': 'Go by taxi.',
  'tea': 'I like tea.',
  'teach': 'I teach here.',
  'teacher': "I'm a teacher.",
  'teachers': 'We are teachers.',
  'teams': 'We beat three teams.',
  'teapot': 'The teapot broke.',
  'teas': 'Several teas are sold here.',
  'teeth': 'My teeth hurt.',
  'telephone': 'Use the telephone.',
  'telephones': 'I like your telephones.',
  'television': 'I watch television.',
  'telling': "I'm telling you.",
  'temperature': 'I have a temperature.',
  'temple': 'In the temple.',
  'ten': 'Atl is ten.',
  'tender': 'Love me tender.',
  'tense': 'I was tense.',
  'tenses': 'Does Berber have tenses?',
  'tenth': "I'm a tenth grader.",
  'terry': 'I want to speak to Terry.',
  'test': "It's a test.",
  'tests': 'I hate tests.',
  'that': 'I do that.',
  'theatre': 'I go to the theatre.',
  'their': 'Their lips met.',
  'theirs': 'This is theirs.',
  'them': 'I see them.',
  'themselves': 'They rule themselves.',
  'then': 'Then do it!',
  'theo': 'Theo has gotten fatter.',
  'theoretical': 'The theoretical exam is tomorrow.',
  'theory': 'I have a theory.',
  'there': 'I am there.',
  'these': 'Try these on.',
  'they': 'They do it.',
  'thin': 'I am thin.',
  'thing': 'Do the thing.',
  'think': 'I think so.',
  'thinks': 'Who thinks so?',
  'third': 'I was third.',
  'thirsty': 'I am thirsty.',
  'thirteen': "I'm thirteen now.",
  'thirteenth': "What's the thirteenth month?",
  'thirtieth': 'He died on his thirtieth birthday.',
  'thirty': 'I am thirty.',
  'this': 'I do this.',
  'those': 'I need those.',
  'though': 'Is he, though?',
  'thought': 'I thought so!',
  'three': 'All three died.',
  'threw': 'I threw up.',
  'throat': 'Cut his throat!',
  'through': 'Let me through.',
  'throw': 'Throw it out.',
  'thursday': 'It is Thursday.',
  'ticket': 'Take a ticket.',
  'tickets': 'I have tickets.',
  'tidy': 'Are you tidy?',
  'tie': 'Tie me up.',
  'ties': 'I sell ties.',
  'tiger': "That's a tiger.",
  'tigers': 'Do tigers purr?',
  'tight': 'Hug me tight.',
  'tightly': 'He held her tightly.',
  'tights': 'Her tights are grey.',
  'till': 'Wait till six.',
  'time': 'Time is up.',
  'tiny': 'I was tiny.',
  'tip': 'Should I tip?',
  'tips': 'I got tips.',
  'tire': 'I tire easily.',
  'tired': 'I am tired.',
  'tiring': 'It is tiring.',
  'to': 'Way to go.',
  'today': 'Do it today.',
  'toe': 'His toe bleeds.',
  'toes': 'My toes hurt.',
  'toilet': 'You are a toilet!',
  'tokyo': "He's in Tokyo.",
  'tomato': 'I ate a tomato.',
  'tomatoes': 'I eat tomatoes.',
  'tomorrow': 'Do it tomorrow.',
  'tonight': 'Meet me tonight.',
  'too': 'I do too.',
  'took': 'I took it.',
  'tooth': 'My tooth hurts.',
  'toothache': 'I have toothache.',
  'topics': 'Some topics are timeless.',
  'torch': 'I have a torch.',
  'torches': 'We all had torches.',
  'total': 'Total cash cow.',
  'touch': 'I touch you.',
  'tough': 'I am tough.',
  'tour': "We're on tour.",
  'tourist': "I'm a tourist.",
  'tourists': 'Are you tourists?',
  'towards': 'Run towards me!',
  'towel': 'Get a towel.',
  'towels': 'My towels faded.',
  'tower': "That's a tower.",
  'town': 'He left town.',
  'toy': 'Win a toy!',
  'toys': 'I sell toys.',
  'tradition': "It's a tradition.",
  'traditional': 'I bake traditional cakes.',
  'train': 'I train dogs.',
  'trainers': "We're dog trainers.",
  'trains': 'I like trains.',
  'trams': 'Our city has trams.',
  'travel': 'Do you travel?',
  'travelled': 'I travelled alone.',
  'travelling': 'I am travelling.',
  'travels': 'He travels around.',
  'tree': 'Hug a tree.',
  'trees': 'I love trees.',
  'tried': 'I tried it.',
  'trip': 'How was a trip?',
  'trousers': 'I want trousers.',
  'trumpet': 'I want a trumpet.',
  'trunk': 'Empty the trunk.',
  'try': 'Try it on.',
  'tuesday': 'It is Tuesday.',
  'tuna': 'I want tuna.',
  'turkey': 'Turkey is key.',
  'turned': 'I turned red.',
  'turning': "I'm turning red.",
  'turns': 'The worm turns.',
  'twelfth': "I'm a twelfth grader.",
  'twelve': 'He has twelve sons.',
  'twenty': 'She is over twenty.',
  'twenty-five': "It's twenty-five to one.",
  'twenty-second': 'I was born on March twenty-second.',
  'twenty-two': 'He was twenty-two.',
  'twice': 'I went twice.',
  'two': 'I made two.',
  'type': 'I can type.',
  'types': 'He types well.',
  'typewriter': 'Is this typewriter yours?',
  'typist': 'She is a typist.',
  'tyre': 'Pump up the tyre.',
  'ugly': 'Am I ugly?',
  'umbrella': "It's my umbrella.",
  'uncle': "He's my uncle.",
  'uncountable': 'The set of real numbers is uncountable.',
  'under': 'Under what name?',
  'underlined': 'Correct the underlined words.',
  'underwater': "Don't stay underwater.",
  'unforgettable': 'It was unforgettable.',
  'unfortunately': 'I do, unfortunately.',
  'unfriendly': 'Flavio is unfriendly.',
  'units': 'Attention, all units.',
  'university': "I'm at university.",
  'unkind': 'He was unkind.',
  'unpleasant': 'That was unpleasant.',
  'unpopular': 'She was unpopular.',
  'up': 'I got up.',
  'upon': 'Peace upon him.',
  'upset': 'I am upset.',
  'upstairs': 'I ran upstairs.',
  'us': 'Let us in.',
  'usa': "I'm from the USA.",
  'use': 'I use it.',
  'useful': 'It was useful.',
  'usually': 'I usually win.',
  'variety': 'Most men need variety.',
  'various': 'I have various projects.',
  'vase': 'This is a vase.',
  'vases': 'He smashed the vases into pieces.',
  'vegetables': 'I eat vegetables.',
  'vehicle': 'The vehicle left.',
  'venice': 'Did you go to Venice?',
  'very': "I'm very fat.",
  'vet': "I'm a vet.",
  'veterinarian': "I'm a veterinarian.",
  'veterinary': 'She became a veterinary surgeon.',
  'view': 'What a view!',
  'villa': 'The villa sleeps.',
  'village': 'To the village.',
  'villager': "I'm a villager.",
  'vinci': 'Da Vinci could see farther than others.',
  'violin': 'I play violin.',
  'violinist': 'Ziri is a violinist.',
  'virgo': "I'm a Virgo.",
  'visit': 'I visit Mina.',
  'visited': 'I visited Dan.',
  'visiting': "I'm just visiting.",
  'visitors': 'We have visitors.',
  'visits': 'He visits Mina.',
  'vocabulary': "What's that vocabulary?",
  'volleyball': 'I like volleyball.',
  'vowel': 'This is a vowel.',
  'wait': 'I can wait.',
  'waited': 'I waited up.',
  'waiter': "I'm a waiter.",
  'waiters': 'We need more waiters.',
  'waitress': "I'm a waitress.",
  'wake': 'I wake up.',
  'wales': 'He comes from Wales.',
  'walk': 'I can walk.',
  'walked': 'He walked in.',
  'walking': 'I am walking.',
  'walks': 'He walks fast.',
  'wall': "It's a wall.",
  'walls': 'Walls have ears.',
  'wane': 'His powers are on the wane.',
  'want': 'I want it.',
  'wants': 'He wants it.',
  'wardrobe': 'There was a wardrobe.',
  'warehouse': "Where's your warehouse?",
  'warm': 'I am warm.',
  'warsaw': 'I live in Warsaw.',
  'was': 'I was OK.',
  'wash': 'Go wash up!',
  'washbasin': 'The washbasin was full of hair!',
  'washer': 'We bought a washer.',
  'washing': "I'm washing up.",
  'washing-up': 'We do the washing-up.',
  'washington': 'Washington was worried.',
  "wasn't": "It wasn't I.",
  'waste': "It's a waste.",
  'watch': 'I watch TV.',
  'watched': 'I watched TV.',
  'watches': 'He watches PBS.',
  'watching': 'I am watching.',
  'water': 'Water is wet.',
  'waterfall': 'The waterfall is big.',
  'waters': 'The waters receded.',
  'wavy': 'My hair is wavy.',
  'way': 'Way to go.',
  'ways': 'Our ways differ.',
  'we': 'We do it.',
  "we'll": "We'll be OK.",
  'wealth': 'He wants wealth.',
  'wealthy': 'He is wealthy.',
  'wear': 'Wear a mask.',
  'wearing': "I'm wearing gray.",
  'wears': 'He wears ties.',
  'weather': 'What bad weather!',
  'wedding': "When's the wedding?",
  'wednesday': 'It is Wednesday.',
  'wee': 'I need a wee.',
  'week': 'I need a week.',
  'weekday': 'Ziri went there on a weekday.',
  'weekend': "It's the weekend.",
  'weeks': 'Two weeks went by.',
  'weigh': 'I weigh myself.',
  'weight': 'I lost weight.',
  'well': 'I am well.',
  'well-built': 'James was a well-built man.',
  'well-known': "She's very well-known.",
  'wells': 'Anger wells up inside me.',
  'went': 'I went on.',
  'west': 'He went west.',
  'western': "I'm watching a Western.",
  'wet': 'I was wet.',
  'whale': 'What is a whale?',
  'what': 'What am I?',
  'when': 'When is it?',
  'which': 'Which is new?',
  'while': 'Stay a while.',
  'whiskers': 'Cats have whiskers.',
  'white': 'I am white.',
  "who's": "Who's in it?",
  'whose': 'Whose is it?',
  'wide': 'They are wide.',
  'width': 'Measure the width.',
  'wife': 'Be my wife.',
  'wild': 'This is wild.',
  'will': 'I will go.',
  'wilson': 'Good night, Ms Wilson!',
  'win': 'Did I win?',
  'wind': 'I hate wind.',
  'window': 'Open a window.',
  'windows': 'Open the windows.',
  'windscreen': 'My windscreen was icy.',
  'windsurf': 'Do you windsurf?',
  'windsurfing': 'I am windsurfing.',
  'windy': 'Is it windy?',
  'wine': 'I have wine.',
  'wing': "Let's just wing it.",
  'wings': 'Truth has wings.',
  'winner': "I'm a winner!",
  'wins': 'He never wins.',
  'winter': 'It is winter.',
  'wisdom': 'What is wisdom?',
  'wise': 'Is that wise?',
  'wishes': 'He wishes it.',
  'wives': 'We left our wives.',
  'woe': 'Woe is me!',
  'woke': 'I woke up.',
  'woman': "I'm a woman.",
  'women': 'I like women.',
  'won': 'I won one.',
  "won't": "I won't go.",
  'wonder': 'I wonder who.',
  'wonderful': 'I was wonderful.',
  'wood': 'I sell wood.',
  'work': 'Go to work.',
  'workbook': 'Where is my workbook?',
  'worked': 'I worked hard.',
  'works': 'It works now.',
  'worry': 'I do worry.',
  'worse': 'It is worse.',
  'worst': 'Do your worst.',
  'wow': 'Wow, so cold!',
  'write': 'Write it up.',
  'writer': "I'm a writer.",
  'writes': 'He writes well.',
  'writing': 'I am writing.',
  'written': 'Has he written?',
  'wrong': 'Am I wrong?',
  'wrote': 'I wrote it.',
  'yawn': 'I yawn a lot.',
  'year': 'What a year!',
  'yellow': 'I like yellow.',
  'yellowish': 'This light is more yellowish.',
  'yes': 'Yes I am.',
  'yesterday': 'I came yesterday.',
  'you': 'You or I?',
  "you'll": "You'll be OK.",
  'young': 'I am young.',
  'younger': 'Who is younger?',
  'your': 'Do your job.',
  'yours': 'Is it yours?',
  'yourself': 'Do it yourself.',
  'zebras': 'Zebras have stripes.',
  'zoo': "It's a zoo.",
}
